/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  DtoCancelScheduleRequest,
  DtoCancelScheduleRequest$Outbound,
  DtoCancelScheduleRequest$outboundSchema,
} from "./dtocancelschedulerequest.js";

export type CancelSubscriptionScheduleRequest = {
  /**
   * Schedule ID (optional if using request body)
   */
  scheduleId: string;
  /**
   * Cancel request (optional if using path parameter)
   */
  dtoCancelScheduleRequest?: DtoCancelScheduleRequest | undefined;
};

/** @internal */
export type CancelSubscriptionScheduleRequest$Outbound = {
  schedule_id: string;
  "dto.CancelScheduleRequest"?: DtoCancelScheduleRequest$Outbound | undefined;
};

/** @internal */
export const CancelSubscriptionScheduleRequest$outboundSchema: z.ZodType<
  CancelSubscriptionScheduleRequest$Outbound,
  z.ZodTypeDef,
  CancelSubscriptionScheduleRequest
> = z.object({
  scheduleId: z.string(),
  dtoCancelScheduleRequest: DtoCancelScheduleRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    scheduleId: "schedule_id",
    dtoCancelScheduleRequest: "dto.CancelScheduleRequest",
  });
});

export function cancelSubscriptionScheduleRequestToJSON(
  cancelSubscriptionScheduleRequest: CancelSubscriptionScheduleRequest,
): string {
  return JSON.stringify(
    CancelSubscriptionScheduleRequest$outboundSchema.parse(
      cancelSubscriptionScheduleRequest,
    ),
  );
}
