/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$inboundSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CreateTaxAssociationResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

/** @internal */
export const CreateTaxAssociationResponse$inboundSchema: z.ZodType<
  CreateTaxAssociationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoTaxAssociationResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function createTaxAssociationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTaxAssociationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTaxAssociationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTaxAssociationResponse' from JSON`,
  );
}
