/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$inboundSchema,
} from "./dtoinvoiceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CreateInvoiceResponse = DtoInvoiceResponse | ErrorsErrorResponse;

/** @internal */
export const CreateInvoiceResponse$inboundSchema: z.ZodType<
  CreateInvoiceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoInvoiceResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function createInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateInvoiceResponse' from JSON`,
  );
}
