/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const CreditGrantCadence = {
  Onetime: "ONETIME",
  Recurring: "RECURRING",
} as const;
export type CreditGrantCadence = ClosedEnum<typeof CreditGrantCadence>;

/** @internal */
export const CreditGrantCadence$inboundSchema: z.ZodNativeEnum<
  typeof CreditGrantCadence
> = z.nativeEnum(CreditGrantCadence);
/** @internal */
export const CreditGrantCadence$outboundSchema: z.ZodNativeEnum<
  typeof CreditGrantCadence
> = CreditGrantCadence$inboundSchema;
