/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$inboundSchema,
} from "./dtotaxassociationresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DeleteTaxAssociationRequest = {
  /**
   * Tax Config ID
   */
  id: string;
};

export type DeleteTaxAssociationResponse =
  | DtoTaxAssociationResponse
  | ErrorsErrorResponse;

/** @internal */
export type DeleteTaxAssociationRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTaxAssociationRequest$outboundSchema: z.ZodType<
  DeleteTaxAssociationRequest$Outbound,
  z.ZodTypeDef,
  DeleteTaxAssociationRequest
> = z.object({
  id: z.string(),
});

export function deleteTaxAssociationRequestToJSON(
  deleteTaxAssociationRequest: DeleteTaxAssociationRequest,
): string {
  return JSON.stringify(
    DeleteTaxAssociationRequest$outboundSchema.parse(
      deleteTaxAssociationRequest,
    ),
  );
}

/** @internal */
export const DeleteTaxAssociationResponse$inboundSchema: z.ZodType<
  DeleteTaxAssociationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoTaxAssociationResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function deleteTaxAssociationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTaxAssociationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTaxAssociationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTaxAssociationResponse' from JSON`,
  );
}
