/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoDeleteSubscriptionLineItemRequest,
  DtoDeleteSubscriptionLineItemRequest$Outbound,
  DtoDeleteSubscriptionLineItemRequest$outboundSchema,
} from "./dtodeletesubscriptionlineitemrequest.js";
import {
  DtoSubscriptionLineItemResponse,
  DtoSubscriptionLineItemResponse$inboundSchema,
} from "./dtosubscriptionlineitemresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DeleteSubscriptionLineItemRequest = {
  /**
   * Line Item ID
   */
  id: string;
  /**
   * Delete Line Item Request
   */
  dtoDeleteSubscriptionLineItemRequest: DtoDeleteSubscriptionLineItemRequest;
};

export type DeleteSubscriptionLineItemResponse =
  | DtoSubscriptionLineItemResponse
  | ErrorsErrorResponse;

/** @internal */
export type DeleteSubscriptionLineItemRequest$Outbound = {
  id: string;
  "dto.DeleteSubscriptionLineItemRequest":
    DtoDeleteSubscriptionLineItemRequest$Outbound;
};

/** @internal */
export const DeleteSubscriptionLineItemRequest$outboundSchema: z.ZodType<
  DeleteSubscriptionLineItemRequest$Outbound,
  z.ZodTypeDef,
  DeleteSubscriptionLineItemRequest
> = z.object({
  id: z.string(),
  dtoDeleteSubscriptionLineItemRequest:
    DtoDeleteSubscriptionLineItemRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoDeleteSubscriptionLineItemRequest:
      "dto.DeleteSubscriptionLineItemRequest",
  });
});

export function deleteSubscriptionLineItemRequestToJSON(
  deleteSubscriptionLineItemRequest: DeleteSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    DeleteSubscriptionLineItemRequest$outboundSchema.parse(
      deleteSubscriptionLineItemRequest,
    ),
  );
}

/** @internal */
export const DeleteSubscriptionLineItemResponse$inboundSchema: z.ZodType<
  DeleteSubscriptionLineItemResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoSubscriptionLineItemResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function deleteSubscriptionLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSubscriptionLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSubscriptionLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSubscriptionLineItemResponse' from JSON`,
  );
}
