/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DownloadTaskExportRequest = {
  /**
   * Task ID
   */
  id: string;
};

export type DownloadTaskExportResponse =
  | { [k: string]: string }
  | ErrorsErrorResponse;

/** @internal */
export type DownloadTaskExportRequest$Outbound = {
  id: string;
};

/** @internal */
export const DownloadTaskExportRequest$outboundSchema: z.ZodType<
  DownloadTaskExportRequest$Outbound,
  z.ZodTypeDef,
  DownloadTaskExportRequest
> = z.object({
  id: z.string(),
});

export function downloadTaskExportRequestToJSON(
  downloadTaskExportRequest: DownloadTaskExportRequest,
): string {
  return JSON.stringify(
    DownloadTaskExportRequest$outboundSchema.parse(downloadTaskExportRequest),
  );
}

/** @internal */
export const DownloadTaskExportResponse$inboundSchema: z.ZodType<
  DownloadTaskExportResponse,
  z.ZodTypeDef,
  unknown
> = z.union([z.record(z.string()), ErrorsErrorResponse$inboundSchema]);

export function downloadTaskExportResponseFromJSON(
  jsonString: string,
): SafeParseResult<DownloadTaskExportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadTaskExportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadTaskExportResponse' from JSON`,
  );
}
