/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  AlertEntityType,
  AlertEntityType$inboundSchema,
} from "./alertentitytype.js";
import { AlertInfo, AlertInfo$inboundSchema } from "./alertinfo.js";
import { AlertState, AlertState$inboundSchema } from "./alertstate.js";
import { AlertType, AlertType$inboundSchema } from "./alerttype.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$inboundSchema,
} from "./dtocustomerresponse.js";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$inboundSchema,
} from "./dtofeatureresponse.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dtowalletresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoAlertLogResponse = {
  alertInfo?: AlertInfo | undefined;
  alertStatus?: AlertState | undefined;
  alertType?: AlertType | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  /**
   * Customer response object containing all customer information
   */
  customer?: DtoCustomerResponse | undefined;
  customerId?: string | undefined;
  entityId?: string | undefined;
  entityType?: AlertEntityType | undefined;
  environmentId?: string | undefined;
  feature?: DtoFeatureResponse | undefined;
  id?: string | undefined;
  parentEntityId?: string | undefined;
  parentEntityType?: string | undefined;
  status?: string | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
};

/** @internal */
export const DtoAlertLogResponse$inboundSchema: z.ZodType<
  DtoAlertLogResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  alert_info: AlertInfo$inboundSchema.optional(),
  alert_status: AlertState$inboundSchema.optional(),
  alert_type: AlertType$inboundSchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  customer: DtoCustomerResponse$inboundSchema.optional(),
  customer_id: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: AlertEntityType$inboundSchema.optional(),
  environment_id: z.string().optional(),
  feature: DtoFeatureResponse$inboundSchema.optional(),
  id: z.string().optional(),
  parent_entity_id: z.string().optional(),
  parent_entity_type: z.string().optional(),
  status: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  wallet: DtoWalletResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "alert_info": "alertInfo",
    "alert_status": "alertStatus",
    "alert_type": "alertType",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "customer_id": "customerId",
    "entity_id": "entityId",
    "entity_type": "entityType",
    "environment_id": "environmentId",
    "parent_entity_id": "parentEntityId",
    "parent_entity_type": "parentEntityType",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoAlertLogResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoAlertLogResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoAlertLogResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoAlertLogResponse' from JSON`,
  );
}
