/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  IntegrationEntityType,
  IntegrationEntityType$inboundSchema,
} from "./integrationentitytype.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { Status, Status$inboundSchema } from "./status.js";

export type DtoEntityIntegrationMappingResponse = {
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  entityId?: string | undefined;
  entityType?: IntegrationEntityType | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  providerEntityId?: string | undefined;
  providerType?: string | undefined;
  status?: Status | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoEntityIntegrationMappingResponse$inboundSchema: z.ZodType<
  DtoEntityIntegrationMappingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: IntegrationEntityType$inboundSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  provider_entity_id: z.string().optional(),
  provider_type: z.string().optional(),
  status: Status$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "created_by": "createdBy",
    "entity_id": "entityId",
    "entity_type": "entityType",
    "environment_id": "environmentId",
    "provider_entity_id": "providerEntityId",
    "provider_type": "providerType",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoEntityIntegrationMappingResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoEntityIntegrationMappingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DtoEntityIntegrationMappingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoEntityIntegrationMappingResponse' from JSON`,
  );
}
