/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { AlertSettings, AlertSettings$inboundSchema } from "./alertsettings.js";
import {
  DtoMeterResponse,
  DtoMeterResponse$inboundSchema,
} from "./dtometerresponse.js";
import { FeatureType, FeatureType$inboundSchema } from "./featuretype.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { Status, Status$inboundSchema } from "./status.js";

export type DtoFeatureResponse = {
  alertSettings?: AlertSettings | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  description?: string | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoMeterResponse | undefined;
  meterId?: string | undefined;
  name?: string | undefined;
  status?: Status | undefined;
  tenantId?: string | undefined;
  type?: FeatureType | undefined;
  unitPlural?: string | undefined;
  unitSingular?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoFeatureResponse$inboundSchema: z.ZodType<
  DtoFeatureResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  alert_settings: AlertSettings$inboundSchema.optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  meter: DtoMeterResponse$inboundSchema.optional(),
  meter_id: z.string().optional(),
  name: z.string().optional(),
  status: Status$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  type: FeatureType$inboundSchema.optional(),
  unit_plural: z.string().optional(),
  unit_singular: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "alert_settings": "alertSettings",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "environment_id": "environmentId",
    "lookup_key": "lookupKey",
    "meter_id": "meterId",
    "tenant_id": "tenantId",
    "unit_plural": "unitPlural",
    "unit_singular": "unitSingular",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoFeatureResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoFeatureResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoFeatureResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoFeatureResponse' from JSON`,
  );
}
