/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$inboundSchema,
} from "./dtopriceresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoListPricesResponse = {
  items?: Array<DtoPriceResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListPricesResponse$inboundSchema: z.ZodType<
  DtoListPricesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoPriceResponse$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});

export function dtoListPricesResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListPricesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListPricesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListPricesResponse' from JSON`,
  );
}
