/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$inboundSchema,
} from "./dtocreditgrantresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoListCreditGrantsResponse = {
  items?: Array<DtoCreditGrantResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListCreditGrantsResponse$inboundSchema: z.ZodType<
  DtoListCreditGrantsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoCreditGrantResponse$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});

export function dtoListCreditGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListCreditGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListCreditGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListCreditGrantsResponse' from JSON`,
  );
}
