/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoPaymentResponse,
  DtoPaymentResponse$inboundSchema,
} from "./dtopaymentresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoListPaymentsResponse = {
  items?: Array<DtoPaymentResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListPaymentsResponse$inboundSchema: z.ZodType<
  DtoListPaymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoPaymentResponse$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});

export function dtoListPaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListPaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListPaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListPaymentsResponse' from JSON`,
  );
}
