/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoSecretResponse,
  DtoSecretResponse$inboundSchema,
} from "./dtosecretresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoListSecretsResponse = {
  items?: Array<DtoSecretResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListSecretsResponse$inboundSchema: z.ZodType<
  DtoListSecretsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoSecretResponse$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});

export function dtoListSecretsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListSecretsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListSecretsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListSecretsResponse' from JSON`,
  );
}
