/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$inboundSchema,
} from "./dtosubscriptionresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoListSubscriptionsResponse = {
  items?: Array<DtoSubscriptionResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListSubscriptionsResponse$inboundSchema: z.ZodType<
  DtoListSubscriptionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoSubscriptionResponse$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});

export function dtoListSubscriptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListSubscriptionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListSubscriptionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListSubscriptionsResponse' from JSON`,
  );
}
