/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoTaxAssociationResponse,
  DtoTaxAssociationResponse$inboundSchema,
} from "./dtotaxassociationresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DtoListTaxAssociationsResponse = {
  items?: Array<DtoTaxAssociationResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const DtoListTaxAssociationsResponse$inboundSchema: z.ZodType<
  DtoListTaxAssociationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoTaxAssociationResponse$inboundSchema).optional(),
  pagination: PaginationResponse$inboundSchema.optional(),
});

export function dtoListTaxAssociationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListTaxAssociationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListTaxAssociationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListTaxAssociationsResponse' from JSON`,
  );
}
