/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  BillingCadence,
  BillingCadence$outboundSchema,
} from "./billingcadence.js";
import { BillingCycle, BillingCycle$outboundSchema } from "./billingcycle.js";
import {
  BillingPeriod,
  BillingPeriod$outboundSchema,
} from "./billingperiod.js";
import {
  ProrationBehavior,
  ProrationBehavior$outboundSchema,
} from "./prorationbehavior.js";
import { ScheduleType, ScheduleType$outboundSchema } from "./scheduletype.js";

/**
 * Request object for changing a subscription plan (upgrade/downgrade)
 */
export type DtoSubscriptionChangeRequest = {
  billingCadence: BillingCadence;
  billingCycle: BillingCycle;
  billingPeriod: BillingPeriod;
  /**
   * billing_period_count is the billing period count for the new subscription
   */
  billingPeriodCount?: number | undefined;
  changeAt?: ScheduleType | undefined;
  /**
   * metadata contains additional key-value pairs for storing extra information
   */
  metadata?: { [k: string]: string } | undefined;
  prorationBehavior: ProrationBehavior;
  /**
   * target_plan_id is the ID of the new plan to change to (required)
   */
  targetPlanId: string;
};

/** @internal */
export type DtoSubscriptionChangeRequest$Outbound = {
  billing_cadence: string;
  billing_cycle: string;
  billing_period: string;
  billing_period_count?: number | undefined;
  change_at?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  proration_behavior: string;
  target_plan_id: string;
};

/** @internal */
export const DtoSubscriptionChangeRequest$outboundSchema: z.ZodType<
  DtoSubscriptionChangeRequest$Outbound,
  z.ZodTypeDef,
  DtoSubscriptionChangeRequest
> = z.object({
  billingCadence: BillingCadence$outboundSchema,
  billingCycle: BillingCycle$outboundSchema,
  billingPeriod: BillingPeriod$outboundSchema,
  billingPeriodCount: z.number().int().optional(),
  changeAt: ScheduleType$outboundSchema.optional(),
  metadata: z.record(z.string()).optional(),
  prorationBehavior: ProrationBehavior$outboundSchema,
  targetPlanId: z.string(),
}).transform((v) => {
  return remap$(v, {
    billingCadence: "billing_cadence",
    billingCycle: "billing_cycle",
    billingPeriod: "billing_period",
    billingPeriodCount: "billing_period_count",
    changeAt: "change_at",
    prorationBehavior: "proration_behavior",
    targetPlanId: "target_plan_id",
  });
});

export function dtoSubscriptionChangeRequestToJSON(
  dtoSubscriptionChangeRequest: DtoSubscriptionChangeRequest,
): string {
  return JSON.stringify(
    DtoSubscriptionChangeRequest$outboundSchema.parse(
      dtoSubscriptionChangeRequest,
    ),
  );
}
