/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  SecretProvider,
  SecretProvider$inboundSchema,
} from "./secretprovider.js";
import { SecretType, SecretType$inboundSchema } from "./secrettype.js";
import { Status, Status$inboundSchema } from "./status.js";
import { UserType, UserType$inboundSchema } from "./usertype.js";

export type DtoSecretResponse = {
  createdAt?: string | undefined;
  displayId?: string | undefined;
  expiresAt?: string | undefined;
  id?: string | undefined;
  lastUsedAt?: string | undefined;
  name?: string | undefined;
  provider?: SecretProvider | undefined;
  /**
   * RBAC roles
   */
  roles?: Array<string> | undefined;
  status?: Status | undefined;
  type?: SecretType | undefined;
  updatedAt?: string | undefined;
  userType?: UserType | undefined;
};

/** @internal */
export const DtoSecretResponse$inboundSchema: z.ZodType<
  DtoSecretResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().optional(),
  display_id: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  last_used_at: z.string().optional(),
  name: z.string().optional(),
  provider: SecretProvider$inboundSchema.optional(),
  roles: z.array(z.string()).optional(),
  status: Status$inboundSchema.optional(),
  type: SecretType$inboundSchema.optional(),
  updated_at: z.string().optional(),
  user_type: UserType$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "display_id": "displayId",
    "expires_at": "expiresAt",
    "last_used_at": "lastUsedAt",
    "updated_at": "updatedAt",
    "user_type": "userType",
  });
});

export function dtoSecretResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoSecretResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoSecretResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoSecretResponse' from JSON`,
  );
}
