/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const FeatureType = {
  Metered: "metered",
  Boolean: "boolean",
  Static: "static",
} as const;
export type FeatureType = ClosedEnum<typeof FeatureType>;

/** @internal */
export const FeatureType$inboundSchema: z.ZodNativeEnum<typeof FeatureType> = z
  .nativeEnum(FeatureType);
/** @internal */
export const FeatureType$outboundSchema: z.ZodNativeEnum<typeof FeatureType> =
  FeatureType$inboundSchema;
