/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const FileType = {
  Csv: "CSV",
  Json: "JSON",
} as const;
export type FileType = ClosedEnum<typeof FileType>;

/** @internal */
export const FileType$inboundSchema: z.ZodNativeEnum<typeof FileType> = z
  .nativeEnum(FileType);
/** @internal */
export const FileType$outboundSchema: z.ZodNativeEnum<typeof FileType> =
  FileType$inboundSchema;
