/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { DataType, DataType$outboundSchema } from "./datatype.js";
import {
  FilterOperatorType,
  FilterOperatorType$outboundSchema,
} from "./filteroperatortype.js";
import {
  GithubComFlexpriceFlexpriceInternalTypesValue,
  GithubComFlexpriceFlexpriceInternalTypesValue$Outbound,
  GithubComFlexpriceFlexpriceInternalTypesValue$outboundSchema,
} from "./githubcomflexpriceflexpriceinternaltypesvalue.js";

export type FilterCondition = {
  dataType?: DataType | undefined;
  field?: string | undefined;
  operator?: FilterOperatorType | undefined;
  value?: GithubComFlexpriceFlexpriceInternalTypesValue | undefined;
};

/** @internal */
export type FilterCondition$Outbound = {
  data_type?: string | undefined;
  field?: string | undefined;
  operator?: string | undefined;
  value?: GithubComFlexpriceFlexpriceInternalTypesValue$Outbound | undefined;
};

/** @internal */
export const FilterCondition$outboundSchema: z.ZodType<
  FilterCondition$Outbound,
  z.ZodTypeDef,
  FilterCondition
> = z.object({
  dataType: DataType$outboundSchema.optional(),
  field: z.string().optional(),
  operator: FilterOperatorType$outboundSchema.optional(),
  value: GithubComFlexpriceFlexpriceInternalTypesValue$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    dataType: "data_type",
  });
});

export function filterConditionToJSON(
  filterCondition: FilterCondition,
): string {
  return JSON.stringify(FilterCondition$outboundSchema.parse(filterCondition));
}
