/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$inboundSchema,
} from "./dtocreditgrantresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetCreditGrantRequest = {
  /**
   * Credit Grant ID
   */
  id: string;
};

export type GetCreditGrantResponse =
  | DtoCreditGrantResponse
  | ErrorsErrorResponse;

/** @internal */
export type GetCreditGrantRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCreditGrantRequest$outboundSchema: z.ZodType<
  GetCreditGrantRequest$Outbound,
  z.ZodTypeDef,
  GetCreditGrantRequest
> = z.object({
  id: z.string(),
});

export function getCreditGrantRequestToJSON(
  getCreditGrantRequest: GetCreditGrantRequest,
): string {
  return JSON.stringify(
    GetCreditGrantRequest$outboundSchema.parse(getCreditGrantRequest),
  );
}

/** @internal */
export const GetCreditGrantResponse$inboundSchema: z.ZodType<
  GetCreditGrantResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoCreditGrantResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getCreditGrantResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditGrantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditGrantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditGrantResponse' from JSON`,
  );
}
