/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoCustomerResponse,
  DtoCustomerResponse$inboundSchema,
} from "./dtocustomerresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetCustomerRequest = {
  /**
   * Customer ID
   */
  id: string;
};

export type GetCustomerResponse = DtoCustomerResponse | ErrorsErrorResponse;

/** @internal */
export type GetCustomerRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomerRequest$outboundSchema: z.ZodType<
  GetCustomerRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerRequest
> = z.object({
  id: z.string(),
});

export function getCustomerRequestToJSON(
  getCustomerRequest: GetCustomerRequest,
): string {
  return JSON.stringify(
    GetCustomerRequest$outboundSchema.parse(getCustomerRequest),
  );
}

/** @internal */
export const GetCustomerResponse$inboundSchema: z.ZodType<
  GetCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoCustomerResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getCustomerResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerResponse' from JSON`,
  );
}
