/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoGroupResponse,
  DtoGroupResponse$inboundSchema,
} from "./dtogroupresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetGroupRequest = {
  /**
   * Group ID
   */
  id: string;
};

export type GetGroupResponse = DtoGroupResponse | ErrorsErrorResponse;

/** @internal */
export type GetGroupRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetGroupRequest$outboundSchema: z.ZodType<
  GetGroupRequest$Outbound,
  z.ZodTypeDef,
  GetGroupRequest
> = z.object({
  id: z.string(),
});

export function getGroupRequestToJSON(
  getGroupRequest: GetGroupRequest,
): string {
  return JSON.stringify(GetGroupRequest$outboundSchema.parse(getGroupRequest));
}

/** @internal */
export const GetGroupResponse$inboundSchema: z.ZodType<
  GetGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoGroupResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGroupResponse' from JSON`,
  );
}
