/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoGetHuggingFaceBillingDataResponse,
  DtoGetHuggingFaceBillingDataResponse$inboundSchema,
} from "./dtogethuggingfacebillingdataresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetHuggingfaceInferenceDataResponse =
  | DtoGetHuggingFaceBillingDataResponse
  | ErrorsErrorResponse;

/** @internal */
export const GetHuggingfaceInferenceDataResponse$inboundSchema: z.ZodType<
  GetHuggingfaceInferenceDataResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoGetHuggingFaceBillingDataResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getHuggingfaceInferenceDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetHuggingfaceInferenceDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetHuggingfaceInferenceDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHuggingfaceInferenceDataResponse' from JSON`,
  );
}
