/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$inboundSchema,
} from "./dtopriceresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetPriceByLookupKeyRequest = {
  /**
   * Lookup key
   */
  lookupKey: string;
};

export type GetPriceByLookupKeyResponse =
  | DtoPriceResponse
  | ErrorsErrorResponse;

/** @internal */
export type GetPriceByLookupKeyRequest$Outbound = {
  lookup_key: string;
};

/** @internal */
export const GetPriceByLookupKeyRequest$outboundSchema: z.ZodType<
  GetPriceByLookupKeyRequest$Outbound,
  z.ZodTypeDef,
  GetPriceByLookupKeyRequest
> = z.object({
  lookupKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    lookupKey: "lookup_key",
  });
});

export function getPriceByLookupKeyRequestToJSON(
  getPriceByLookupKeyRequest: GetPriceByLookupKeyRequest,
): string {
  return JSON.stringify(
    GetPriceByLookupKeyRequest$outboundSchema.parse(getPriceByLookupKeyRequest),
  );
}

/** @internal */
export const GetPriceByLookupKeyResponse$inboundSchema: z.ZodType<
  GetPriceByLookupKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoPriceResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getPriceByLookupKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPriceByLookupKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPriceByLookupKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPriceByLookupKeyResponse' from JSON`,
  );
}
