/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoListCreditGrantsResponse,
  DtoListCreditGrantsResponse$inboundSchema,
} from "./dtolistcreditgrantsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetPlanCreditGrantsRequest = {
  /**
   * Plan ID
   */
  id: string;
};

export type GetPlanCreditGrantsResponse =
  | DtoListCreditGrantsResponse
  | ErrorsErrorResponse;

/** @internal */
export type GetPlanCreditGrantsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPlanCreditGrantsRequest$outboundSchema: z.ZodType<
  GetPlanCreditGrantsRequest$Outbound,
  z.ZodTypeDef,
  GetPlanCreditGrantsRequest
> = z.object({
  id: z.string(),
});

export function getPlanCreditGrantsRequestToJSON(
  getPlanCreditGrantsRequest: GetPlanCreditGrantsRequest,
): string {
  return JSON.stringify(
    GetPlanCreditGrantsRequest$outboundSchema.parse(getPlanCreditGrantsRequest),
  );
}

/** @internal */
export const GetPlanCreditGrantsResponse$inboundSchema: z.ZodType<
  GetPlanCreditGrantsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoListCreditGrantsResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getPlanCreditGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPlanCreditGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPlanCreditGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPlanCreditGrantsResponse' from JSON`,
  );
}
