/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoGetUsageBySubscriptionResponse,
  DtoGetUsageBySubscriptionResponse$inboundSchema,
} from "./dtogetusagebysubscriptionresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetSubscriptionUsageResponse =
  | DtoGetUsageBySubscriptionResponse
  | ErrorsErrorResponse;

/** @internal */
export const GetSubscriptionUsageResponse$inboundSchema: z.ZodType<
  GetSubscriptionUsageResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoGetUsageBySubscriptionResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getSubscriptionUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubscriptionUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionUsageResponse' from JSON`,
  );
}
