/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoSubscriptionEntitlementsResponse,
  DtoSubscriptionEntitlementsResponse$inboundSchema,
} from "./dtosubscriptionentitlementsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetSubscriptionEntitlementsRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Feature IDs to filter by
   */
  featureIds?: Array<string> | undefined;
};

export type GetSubscriptionEntitlementsResponse =
  | DtoSubscriptionEntitlementsResponse
  | ErrorsErrorResponse;

/** @internal */
export type GetSubscriptionEntitlementsRequest$Outbound = {
  id: string;
  feature_ids?: Array<string> | undefined;
};

/** @internal */
export const GetSubscriptionEntitlementsRequest$outboundSchema: z.ZodType<
  GetSubscriptionEntitlementsRequest$Outbound,
  z.ZodTypeDef,
  GetSubscriptionEntitlementsRequest
> = z.object({
  id: z.string(),
  featureIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    featureIds: "feature_ids",
  });
});

export function getSubscriptionEntitlementsRequestToJSON(
  getSubscriptionEntitlementsRequest: GetSubscriptionEntitlementsRequest,
): string {
  return JSON.stringify(
    GetSubscriptionEntitlementsRequest$outboundSchema.parse(
      getSubscriptionEntitlementsRequest,
    ),
  );
}

/** @internal */
export const GetSubscriptionEntitlementsResponse$inboundSchema: z.ZodType<
  GetSubscriptionEntitlementsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoSubscriptionEntitlementsResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function getSubscriptionEntitlementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionEntitlementsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSubscriptionEntitlementsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionEntitlementsResponse' from JSON`,
  );
}
