/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type GetWalletsByCustomerIdRequest = {
  /**
   * Customer ID
   */
  id: string;
};

export type GetWalletsByCustomerIdResponse =
  | Array<DtoWalletResponse>
  | ErrorsErrorResponse;

/** @internal */
export type GetWalletsByCustomerIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWalletsByCustomerIdRequest$outboundSchema: z.ZodType<
  GetWalletsByCustomerIdRequest$Outbound,
  z.ZodTypeDef,
  GetWalletsByCustomerIdRequest
> = z.object({
  id: z.string(),
});

export function getWalletsByCustomerIdRequestToJSON(
  getWalletsByCustomerIdRequest: GetWalletsByCustomerIdRequest,
): string {
  return JSON.stringify(
    GetWalletsByCustomerIdRequest$outboundSchema.parse(
      getWalletsByCustomerIdRequest,
    ),
  );
}

/** @internal */
export const GetWalletsByCustomerIdResponse$inboundSchema: z.ZodType<
  GetWalletsByCustomerIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(DtoWalletResponse$inboundSchema),
  ErrorsErrorResponse$inboundSchema,
]);

export function getWalletsByCustomerIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWalletsByCustomerIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWalletsByCustomerIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWalletsByCustomerIdResponse' from JSON`,
  );
}
