/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type IngestEventResponse = { [k: string]: string } | ErrorsErrorResponse;

/** @internal */
export const IngestEventResponse$inboundSchema: z.ZodType<
  IngestEventResponse,
  z.ZodTypeDef,
  unknown
> = z.union([z.record(z.string()), ErrorsErrorResponse$inboundSchema]);

export function ingestEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<IngestEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestEventResponse' from JSON`,
  );
}
