/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const IntegrationEntityType = {
  Customer: "customer",
  Plan: "plan",
  Invoice: "invoice",
  Subscription: "subscription",
  Payment: "payment",
  CreditNote: "credit_note",
  Addon: "addon",
  Item: "item",
  ItemPrice: "item_price",
  Price: "price",
} as const;
export type IntegrationEntityType = ClosedEnum<typeof IntegrationEntityType>;

/** @internal */
export const IntegrationEntityType$inboundSchema: z.ZodNativeEnum<
  typeof IntegrationEntityType
> = z.nativeEnum(IntegrationEntityType);
/** @internal */
export const IntegrationEntityType$outboundSchema: z.ZodNativeEnum<
  typeof IntegrationEntityType
> = IntegrationEntityType$inboundSchema;
