/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoListSubscriptionPausesResponse,
  DtoListSubscriptionPausesResponse$inboundSchema,
} from "./dtolistsubscriptionpausesresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListSubscriptionPausesRequest = {
  /**
   * Subscription ID
   */
  id: string;
};

export type ListSubscriptionPausesResponse =
  | Array<DtoListSubscriptionPausesResponse>
  | ErrorsErrorResponse;

/** @internal */
export type ListSubscriptionPausesRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListSubscriptionPausesRequest$outboundSchema: z.ZodType<
  ListSubscriptionPausesRequest$Outbound,
  z.ZodTypeDef,
  ListSubscriptionPausesRequest
> = z.object({
  id: z.string(),
});

export function listSubscriptionPausesRequestToJSON(
  listSubscriptionPausesRequest: ListSubscriptionPausesRequest,
): string {
  return JSON.stringify(
    ListSubscriptionPausesRequest$outboundSchema.parse(
      listSubscriptionPausesRequest,
    ),
  );
}

/** @internal */
export const ListSubscriptionPausesResponse$inboundSchema: z.ZodType<
  ListSubscriptionPausesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(DtoListSubscriptionPausesResponse$inboundSchema),
  ErrorsErrorResponse$inboundSchema,
]);

export function listSubscriptionPausesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSubscriptionPausesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSubscriptionPausesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSubscriptionPausesResponse' from JSON`,
  );
}
