/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoListTaxAssociationsResponse,
  DtoListTaxAssociationsResponse$inboundSchema,
} from "./dtolisttaxassociationsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListTaxAssociationsRequest = {
  /**
   * Entity Type
   */
  entityType?: string | undefined;
  /**
   * Entity ID
   */
  entityId?: string | undefined;
  /**
   * External Customer ID
   */
  externalCustomerId?: string | undefined;
  /**
   * Tax Rate ID
   */
  taxRateId?: string | undefined;
};

export type ListTaxAssociationsResponse =
  | DtoListTaxAssociationsResponse
  | ErrorsErrorResponse;

/** @internal */
export type ListTaxAssociationsRequest$Outbound = {
  entity_type?: string | undefined;
  entity_id?: string | undefined;
  external_customer_id?: string | undefined;
  tax_rate_id?: string | undefined;
};

/** @internal */
export const ListTaxAssociationsRequest$outboundSchema: z.ZodType<
  ListTaxAssociationsRequest$Outbound,
  z.ZodTypeDef,
  ListTaxAssociationsRequest
> = z.object({
  entityType: z.string().optional(),
  entityId: z.string().optional(),
  externalCustomerId: z.string().optional(),
  taxRateId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    entityType: "entity_type",
    entityId: "entity_id",
    externalCustomerId: "external_customer_id",
    taxRateId: "tax_rate_id",
  });
});

export function listTaxAssociationsRequestToJSON(
  listTaxAssociationsRequest: ListTaxAssociationsRequest,
): string {
  return JSON.stringify(
    ListTaxAssociationsRequest$outboundSchema.parse(listTaxAssociationsRequest),
  );
}

/** @internal */
export const ListTaxAssociationsResponse$inboundSchema: z.ZodType<
  ListTaxAssociationsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoListTaxAssociationsResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function listTaxAssociationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTaxAssociationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTaxAssociationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTaxAssociationsResponse' from JSON`,
  );
}
