/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoListCouponsResponse,
  DtoListCouponsResponse$inboundSchema,
} from "./dtolistcouponsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type QueryCouponResponse = DtoListCouponsResponse | ErrorsErrorResponse;

/** @internal */
export const QueryCouponResponse$inboundSchema: z.ZodType<
  QueryCouponResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoListCouponsResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function queryCouponResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryCouponResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCouponResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCouponResponse' from JSON`,
  );
}
