/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoListGroupsResponse,
  DtoListGroupsResponse$inboundSchema,
} from "./dtolistgroupsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type QueryGroupResponse = DtoListGroupsResponse | ErrorsErrorResponse;

/** @internal */
export const QueryGroupResponse$inboundSchema: z.ZodType<
  QueryGroupResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoListGroupsResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function queryGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryGroupResponse' from JSON`,
  );
}
