/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoListPriceUnitsResponse,
  DtoListPriceUnitsResponse$inboundSchema,
} from "./dtolistpriceunitsresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type QueryPriceUnitResponse =
  | DtoListPriceUnitsResponse
  | ErrorsErrorResponse;

/** @internal */
export const QueryPriceUnitResponse$inboundSchema: z.ZodType<
  QueryPriceUnitResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoListPriceUnitsResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function queryPriceUnitResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryPriceUnitResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryPriceUnitResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryPriceUnitResponse' from JSON`,
  );
}
