/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SecretType = {
  PrivateKey: "private_key",
  PublishableKey: "publishable_key",
  Integration: "integration",
} as const;
export type SecretType = ClosedEnum<typeof SecretType>;

/** @internal */
export const SecretType$inboundSchema: z.ZodNativeEnum<typeof SecretType> = z
  .nativeEnum(SecretType);
/** @internal */
export const SecretType$outboundSchema: z.ZodNativeEnum<typeof SecretType> =
  SecretType$inboundSchema;
