/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TaxRateEntityType = {
  Customer: "customer",
  Subscription: "subscription",
  Invoice: "invoice",
  Tenant: "tenant",
} as const;
export type TaxRateEntityType = ClosedEnum<typeof TaxRateEntityType>;

/** @internal */
export const TaxRateEntityType$inboundSchema: z.ZodNativeEnum<
  typeof TaxRateEntityType
> = z.nativeEnum(TaxRateEntityType);
/** @internal */
export const TaxRateEntityType$outboundSchema: z.ZodNativeEnum<
  typeof TaxRateEntityType
> = TaxRateEntityType$inboundSchema;
