/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dtowalletresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type TerminateWalletRequest = {
  /**
   * Wallet ID
   */
  id: string;
};

export type TerminateWalletResponse = DtoWalletResponse | ErrorsErrorResponse;

/** @internal */
export type TerminateWalletRequest$Outbound = {
  id: string;
};

/** @internal */
export const TerminateWalletRequest$outboundSchema: z.ZodType<
  TerminateWalletRequest$Outbound,
  z.ZodTypeDef,
  TerminateWalletRequest
> = z.object({
  id: z.string(),
});

export function terminateWalletRequestToJSON(
  terminateWalletRequest: TerminateWalletRequest,
): string {
  return JSON.stringify(
    TerminateWalletRequest$outboundSchema.parse(terminateWalletRequest),
  );
}

/** @internal */
export const TerminateWalletResponse$inboundSchema: z.ZodType<
  TerminateWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoWalletResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function terminateWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<TerminateWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TerminateWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TerminateWalletResponse' from JSON`,
  );
}
