/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoAddonResponse,
  DtoAddonResponse$inboundSchema,
} from "./dtoaddonresponse.js";
import {
  DtoUpdateAddonRequest,
  DtoUpdateAddonRequest$Outbound,
  DtoUpdateAddonRequest$outboundSchema,
} from "./dtoupdateaddonrequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type UpdateAddonRequest = {
  /**
   * Addon ID
   */
  id: string;
  /**
   * Update Addon Request
   */
  dtoUpdateAddonRequest: DtoUpdateAddonRequest;
};

export type UpdateAddonResponse = DtoAddonResponse | ErrorsErrorResponse;

/** @internal */
export type UpdateAddonRequest$Outbound = {
  id: string;
  "dto.UpdateAddonRequest": DtoUpdateAddonRequest$Outbound;
};

/** @internal */
export const UpdateAddonRequest$outboundSchema: z.ZodType<
  UpdateAddonRequest$Outbound,
  z.ZodTypeDef,
  UpdateAddonRequest
> = z.object({
  id: z.string(),
  dtoUpdateAddonRequest: DtoUpdateAddonRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdateAddonRequest: "dto.UpdateAddonRequest",
  });
});

export function updateAddonRequestToJSON(
  updateAddonRequest: UpdateAddonRequest,
): string {
  return JSON.stringify(
    UpdateAddonRequest$outboundSchema.parse(updateAddonRequest),
  );
}

/** @internal */
export const UpdateAddonResponse$inboundSchema: z.ZodType<
  UpdateAddonResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoAddonResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function updateAddonResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAddonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAddonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAddonResponse' from JSON`,
  );
}
