/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoFeatureResponse,
  DtoFeatureResponse$inboundSchema,
} from "./dtofeatureresponse.js";
import {
  DtoUpdateFeatureRequest,
  DtoUpdateFeatureRequest$Outbound,
  DtoUpdateFeatureRequest$outboundSchema,
} from "./dtoupdatefeaturerequest.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type UpdateFeatureRequest = {
  /**
   * Feature ID
   */
  id: string;
  /**
   * Feature update data
   */
  dtoUpdateFeatureRequest: DtoUpdateFeatureRequest;
};

export type UpdateFeatureResponse = DtoFeatureResponse | ErrorsErrorResponse;

/** @internal */
export type UpdateFeatureRequest$Outbound = {
  id: string;
  "dto.UpdateFeatureRequest": DtoUpdateFeatureRequest$Outbound;
};

/** @internal */
export const UpdateFeatureRequest$outboundSchema: z.ZodType<
  UpdateFeatureRequest$Outbound,
  z.ZodTypeDef,
  UpdateFeatureRequest
> = z.object({
  id: z.string(),
  dtoUpdateFeatureRequest: DtoUpdateFeatureRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdateFeatureRequest: "dto.UpdateFeatureRequest",
  });
});

export function updateFeatureRequestToJSON(
  updateFeatureRequest: UpdateFeatureRequest,
): string {
  return JSON.stringify(
    UpdateFeatureRequest$outboundSchema.parse(updateFeatureRequest),
  );
}

/** @internal */
export const UpdateFeatureResponse$inboundSchema: z.ZodType<
  UpdateFeatureResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoFeatureResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function updateFeatureResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFeatureResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateFeatureResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFeatureResponse' from JSON`,
  );
}
