/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoCreditNoteResponse,
  DtoCreditNoteResponse$inboundSchema,
} from "./dtocreditnoteresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type VoidCreditNoteRequest = {
  /**
   * Credit note ID
   */
  id: string;
};

export type VoidCreditNoteResponse =
  | DtoCreditNoteResponse
  | ErrorsErrorResponse;

/** @internal */
export type VoidCreditNoteRequest$Outbound = {
  id: string;
};

/** @internal */
export const VoidCreditNoteRequest$outboundSchema: z.ZodType<
  VoidCreditNoteRequest$Outbound,
  z.ZodTypeDef,
  VoidCreditNoteRequest
> = z.object({
  id: z.string(),
});

export function voidCreditNoteRequestToJSON(
  voidCreditNoteRequest: VoidCreditNoteRequest,
): string {
  return JSON.stringify(
    VoidCreditNoteRequest$outboundSchema.parse(voidCreditNoteRequest),
  );
}

/** @internal */
export const VoidCreditNoteResponse$inboundSchema: z.ZodType<
  VoidCreditNoteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoCreditNoteResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function voidCreditNoteResponseFromJSON(
  jsonString: string,
): SafeParseResult<VoidCreditNoteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VoidCreditNoteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VoidCreditNoteResponse' from JSON`,
  );
}
