/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  DtoSuccessResponse,
  DtoSuccessResponse$inboundSchema,
} from "./dtosuccessresponse.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type VoidInvoiceRequest = {
  /**
   * Invoice ID
   */
  id: string;
};

export type VoidInvoiceResponse = DtoSuccessResponse | ErrorsErrorResponse;

/** @internal */
export type VoidInvoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const VoidInvoiceRequest$outboundSchema: z.ZodType<
  VoidInvoiceRequest$Outbound,
  z.ZodTypeDef,
  VoidInvoiceRequest
> = z.object({
  id: z.string(),
});

export function voidInvoiceRequestToJSON(
  voidInvoiceRequest: VoidInvoiceRequest,
): string {
  return JSON.stringify(
    VoidInvoiceRequest$outboundSchema.parse(voidInvoiceRequest),
  );
}

/** @internal */
export const VoidInvoiceResponse$inboundSchema: z.ZodType<
  VoidInvoiceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  DtoSuccessResponse$inboundSchema,
  ErrorsErrorResponse$inboundSchema,
]);

export function voidInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<VoidInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VoidInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VoidInvoiceResponse' from JSON`,
  );
}
