/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const WalletTxReferenceType = {
  Payment: "PAYMENT",
  External: "EXTERNAL",
  Request: "REQUEST",
  Invoice: "INVOICE",
} as const;
export type WalletTxReferenceType = ClosedEnum<typeof WalletTxReferenceType>;

/** @internal */
export const WalletTxReferenceType$inboundSchema: z.ZodNativeEnum<
  typeof WalletTxReferenceType
> = z.nativeEnum(WalletTxReferenceType);
