/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";
import { FlexPriceError } from "./flexpriceerror.js";

export type ErrorsErrorResponseData = {
  error?: components.ErrorsErrorDetail | undefined;
  success?: boolean | undefined;
};

export class ErrorsErrorResponse extends FlexPriceError {
  error?: components.ErrorsErrorDetail | undefined;
  success?: boolean | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorsErrorResponseData;

  constructor(
    err: ErrorsErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.success != null) this.success = err.success;

    this.name = "ErrorsErrorResponse";
  }
}

/** @internal */
export const ErrorsErrorResponse$inboundSchema: z.ZodType<
  ErrorsErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: components.ErrorsErrorDetail$inboundSchema.optional(),
  success: z.boolean().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorsErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
