"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetFeaturesRequest$outboundSchema = exports.GetFeaturesStatus$outboundSchema = exports.GetFeaturesOrder$outboundSchema = exports.GetFeaturesStatus = exports.GetFeaturesOrder = void 0;
exports.getFeaturesRequestToJSON = getFeaturesRequestToJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
exports.GetFeaturesOrder = {
    Asc: "asc",
    Desc: "desc",
};
exports.GetFeaturesStatus = {
    Published: "published",
    Deleted: "deleted",
    Archived: "archived",
};
/** @internal */
exports.GetFeaturesOrder$outboundSchema = z.nativeEnum(exports.GetFeaturesOrder);
/** @internal */
exports.GetFeaturesStatus$outboundSchema = z.nativeEnum(exports.GetFeaturesStatus);
/** @internal */
exports.GetFeaturesRequest$outboundSchema = z.object({
    endTime: z.string().optional(),
    expand: z.string().optional(),
    featureIds: z.array(z.string()).optional(),
    limit: z.number().int().optional(),
    lookupKey: z.string().optional(),
    lookupKeys: z.array(z.string()).optional(),
    meterIds: z.array(z.string()).optional(),
    nameContains: z.string().optional(),
    offset: z.number().int().optional(),
    order: exports.GetFeaturesOrder$outboundSchema.optional(),
    startTime: z.string().optional(),
    status: exports.GetFeaturesStatus$outboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        endTime: "end_time",
        featureIds: "feature_ids",
        lookupKey: "lookup_key",
        lookupKeys: "lookup_keys",
        meterIds: "meter_ids",
        nameContains: "name_contains",
        startTime: "start_time",
    });
});
function getFeaturesRequestToJSON(getFeaturesRequest) {
    return JSON.stringify(exports.GetFeaturesRequest$outboundSchema.parse(getFeaturesRequest));
}
//# sourceMappingURL=getfeatures.js.map