/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const CreditGrantPeriod = {
  Daily: "DAILY",
  Weekly: "WEEKLY",
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
} as const;
export type CreditGrantPeriod = ClosedEnum<typeof CreditGrantPeriod>;

/** @internal */
export const CreditGrantPeriod$inboundSchema: z.ZodNativeEnum<
  typeof CreditGrantPeriod
> = z.nativeEnum(CreditGrantPeriod);
/** @internal */
export const CreditGrantPeriod$outboundSchema: z.ZodNativeEnum<
  typeof CreditGrantPeriod
> = CreditGrantPeriod$inboundSchema;
