/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoAddonResponse,
  DtoAddonResponse$inboundSchema,
} from "./dtoaddonresponse.js";
import {
  DtoSubscriptionResponse,
  DtoSubscriptionResponse$inboundSchema,
} from "./dtosubscriptionresponse.js";
import {
  TypesAddonAssociationEntityType,
  TypesAddonAssociationEntityType$inboundSchema,
} from "./typesaddonassociationentitytype.js";
import {
  TypesAddonStatus,
  TypesAddonStatus$inboundSchema,
} from "./typesaddonstatus.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";

export type DtoAddonAssociationResponse = {
  addon?: DtoAddonResponse | undefined;
  addonId?: string | undefined;
  addonStatus?: TypesAddonStatus | undefined;
  cancellationReason?: string | undefined;
  cancelledAt?: string | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  endDate?: string | undefined;
  entityId?: string | undefined;
  entityType?: TypesAddonAssociationEntityType | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  startDate?: string | undefined;
  status?: TypesStatus | undefined;
  subscription?: DtoSubscriptionResponse | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoAddonAssociationResponse$inboundSchema: z.ZodType<
  DtoAddonAssociationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  addon: DtoAddonResponse$inboundSchema.optional(),
  addon_id: z.string().optional(),
  addon_status: TypesAddonStatus$inboundSchema.optional(),
  cancellation_reason: z.string().optional(),
  cancelled_at: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  end_date: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TypesAddonAssociationEntityType$inboundSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  start_date: z.string().optional(),
  status: TypesStatus$inboundSchema.optional(),
  subscription: DtoSubscriptionResponse$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "addon_id": "addonId",
    "addon_status": "addonStatus",
    "cancellation_reason": "cancellationReason",
    "cancelled_at": "cancelledAt",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "end_date": "endDate",
    "entity_id": "entityId",
    "entity_type": "entityType",
    "environment_id": "environmentId",
    "start_date": "startDate",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoAddonAssociationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoAddonAssociationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoAddonAssociationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoAddonAssociationResponse' from JSON`,
  );
}
