/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DtoBillingPeriodInfo = {
  endTime?: string | undefined;
  /**
   * e.g., "monthly", "yearly"
   */
  period?: string | undefined;
  startTime?: string | undefined;
};

/** @internal */
export const DtoBillingPeriodInfo$inboundSchema: z.ZodType<
  DtoBillingPeriodInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  end_time: z.string().optional(),
  period: z.string().optional(),
  start_time: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "end_time": "endTime",
    "start_time": "startTime",
  });
});

export function dtoBillingPeriodInfoFromJSON(
  jsonString: string,
): SafeParseResult<DtoBillingPeriodInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoBillingPeriodInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoBillingPeriodInfo' from JSON`,
  );
}
