/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  TypesAddonType,
  TypesAddonType$outboundSchema,
} from "./typesaddontype.js";

export type DtoCreateAddonRequest = {
  description?: string | undefined;
  lookupKey: string;
  metadata?: { [k: string]: any } | undefined;
  name: string;
  type: TypesAddonType;
};

/** @internal */
export type DtoCreateAddonRequest$Outbound = {
  description?: string | undefined;
  lookup_key: string;
  metadata?: { [k: string]: any } | undefined;
  name: string;
  type: string;
};

/** @internal */
export const DtoCreateAddonRequest$outboundSchema: z.ZodType<
  DtoCreateAddonRequest$Outbound,
  z.ZodTypeDef,
  DtoCreateAddonRequest
> = z.object({
  description: z.string().optional(),
  lookupKey: z.string(),
  metadata: z.record(z.any()).optional(),
  name: z.string(),
  type: TypesAddonType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    lookupKey: "lookup_key",
  });
});

export function dtoCreateAddonRequestToJSON(
  dtoCreateAddonRequest: DtoCreateAddonRequest,
): string {
  return JSON.stringify(
    DtoCreateAddonRequest$outboundSchema.parse(dtoCreateAddonRequest),
  );
}
