/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  TypesCouponCadence,
  TypesCouponCadence$outboundSchema,
} from "./typescouponcadence.js";
import {
  TypesCouponType,
  TypesCouponType$outboundSchema,
} from "./typescoupontype.js";

export type DtoCreateCouponRequest = {
  amountOff?: string | undefined;
  cadence: TypesCouponCadence;
  currency?: string | undefined;
  durationInPeriods?: number | undefined;
  maxRedemptions?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
  percentageOff?: string | undefined;
  redeemAfter?: string | undefined;
  redeemBefore?: string | undefined;
  rules?: { [k: string]: any } | undefined;
  type: TypesCouponType;
};

/** @internal */
export type DtoCreateCouponRequest$Outbound = {
  amount_off?: string | undefined;
  cadence: string;
  currency?: string | undefined;
  duration_in_periods?: number | undefined;
  max_redemptions?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
  percentage_off?: string | undefined;
  redeem_after?: string | undefined;
  redeem_before?: string | undefined;
  rules?: { [k: string]: any } | undefined;
  type: string;
};

/** @internal */
export const DtoCreateCouponRequest$outboundSchema: z.ZodType<
  DtoCreateCouponRequest$Outbound,
  z.ZodTypeDef,
  DtoCreateCouponRequest
> = z.object({
  amountOff: z.string().optional(),
  cadence: TypesCouponCadence$outboundSchema,
  currency: z.string().optional(),
  durationInPeriods: z.number().int().optional(),
  maxRedemptions: z.number().int().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string(),
  percentageOff: z.string().optional(),
  redeemAfter: z.string().optional(),
  redeemBefore: z.string().optional(),
  rules: z.record(z.any()).optional(),
  type: TypesCouponType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    amountOff: "amount_off",
    durationInPeriods: "duration_in_periods",
    maxRedemptions: "max_redemptions",
    percentageOff: "percentage_off",
    redeemAfter: "redeem_after",
    redeemBefore: "redeem_before",
  });
});

export function dtoCreateCouponRequestToJSON(
  dtoCreateCouponRequest: DtoCreateCouponRequest,
): string {
  return JSON.stringify(
    DtoCreateCouponRequest$outboundSchema.parse(dtoCreateCouponRequest),
  );
}
