/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type DtoCreatePlanRequest = {
  description?: string | undefined;
  displayOrder?: number | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
};

/** @internal */
export type DtoCreatePlanRequest$Outbound = {
  description?: string | undefined;
  display_order?: number | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
};

/** @internal */
export const DtoCreatePlanRequest$outboundSchema: z.ZodType<
  DtoCreatePlanRequest$Outbound,
  z.ZodTypeDef,
  DtoCreatePlanRequest
> = z.object({
  description: z.string().optional(),
  displayOrder: z.number().int().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string(),
}).transform((v) => {
  return remap$(v, {
    displayOrder: "display_order",
    lookupKey: "lookup_key",
  });
});

export function dtoCreatePlanRequestToJSON(
  dtoCreatePlanRequest: DtoCreatePlanRequest,
): string {
  return JSON.stringify(
    DtoCreatePlanRequest$outboundSchema.parse(dtoCreatePlanRequest),
  );
}
