/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$inboundSchema,
} from "./dtopriceresponse.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";

export type DtoCostsheetResponse = {
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  description?: string | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  /**
   * Associated prices
   */
  prices?: Array<DtoPriceResponse> | undefined;
  status?: TypesStatus | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoCostsheetResponse$inboundSchema: z.ZodType<
  DtoCostsheetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
  prices: z.array(DtoPriceResponse$inboundSchema).optional(),
  status: TypesStatus$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "created_by": "createdBy",
    "environment_id": "environmentId",
    "lookup_key": "lookupKey",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoCostsheetResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCostsheetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCostsheetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCostsheetResponse' from JSON`,
  );
}
