/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  TypesIntegrationEntityType,
  TypesIntegrationEntityType$outboundSchema,
} from "./typesintegrationentitytype.js";

export type DtoCreateEntityIntegrationMappingRequest = {
  entityId: string;
  entityType: TypesIntegrationEntityType;
  metadata?: { [k: string]: any } | undefined;
  providerEntityId: string;
  providerType: string;
};

/** @internal */
export type DtoCreateEntityIntegrationMappingRequest$Outbound = {
  entity_id: string;
  entity_type: string;
  metadata?: { [k: string]: any } | undefined;
  provider_entity_id: string;
  provider_type: string;
};

/** @internal */
export const DtoCreateEntityIntegrationMappingRequest$outboundSchema: z.ZodType<
  DtoCreateEntityIntegrationMappingRequest$Outbound,
  z.ZodTypeDef,
  DtoCreateEntityIntegrationMappingRequest
> = z.object({
  entityId: z.string(),
  entityType: TypesIntegrationEntityType$outboundSchema,
  metadata: z.record(z.any()).optional(),
  providerEntityId: z.string(),
  providerType: z.string(),
}).transform((v) => {
  return remap$(v, {
    entityId: "entity_id",
    entityType: "entity_type",
    providerEntityId: "provider_entity_id",
    providerType: "provider_type",
  });
});

export function dtoCreateEntityIntegrationMappingRequestToJSON(
  dtoCreateEntityIntegrationMappingRequest:
    DtoCreateEntityIntegrationMappingRequest,
): string {
  return JSON.stringify(
    DtoCreateEntityIntegrationMappingRequest$outboundSchema.parse(
      dtoCreateEntityIntegrationMappingRequest,
    ),
  );
}
