/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoPriceResponse,
  DtoPriceResponse$inboundSchema,
} from "./dtopriceresponse.js";

export type DtoCreateBulkPriceResponse = {
  items?: Array<DtoPriceResponse> | undefined;
};

/** @internal */
export const DtoCreateBulkPriceResponse$inboundSchema: z.ZodType<
  DtoCreateBulkPriceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoPriceResponse$inboundSchema).optional(),
});

export function dtoCreateBulkPriceResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCreateBulkPriceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCreateBulkPriceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCreateBulkPriceResponse' from JSON`,
  );
}
