/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  DtoAddAddonToSubscriptionRequest,
  DtoAddAddonToSubscriptionRequest$Outbound,
  DtoAddAddonToSubscriptionRequest$outboundSchema,
} from "./dtoaddaddontosubscriptionrequest.js";
import {
  DtoCreateCreditGrantRequest,
  DtoCreateCreditGrantRequest$Outbound,
  DtoCreateCreditGrantRequest$outboundSchema,
} from "./dtocreatecreditgrantrequest.js";
import {
  DtoCreateSubscriptionLineItemRequest,
  DtoCreateSubscriptionLineItemRequest$Outbound,
  DtoCreateSubscriptionLineItemRequest$outboundSchema,
} from "./dtocreatesubscriptionlineitemrequest.js";
import {
  DtoLineItemCommitmentConfig,
  DtoLineItemCommitmentConfig$Outbound,
  DtoLineItemCommitmentConfig$outboundSchema,
} from "./dtolineitemcommitmentconfig.js";
import {
  DtoOverrideEntitlementRequest,
  DtoOverrideEntitlementRequest$Outbound,
  DtoOverrideEntitlementRequest$outboundSchema,
} from "./dtooverrideentitlementrequest.js";
import {
  DtoOverrideLineItemRequest,
  DtoOverrideLineItemRequest$Outbound,
  DtoOverrideLineItemRequest$outboundSchema,
} from "./dtooverridelineitemrequest.js";
import {
  DtoSubscriptionPhaseCreateRequest,
  DtoSubscriptionPhaseCreateRequest$Outbound,
  DtoSubscriptionPhaseCreateRequest$outboundSchema,
} from "./dtosubscriptionphasecreaterequest.js";
import {
  DtoTaxRateOverride,
  DtoTaxRateOverride$Outbound,
  DtoTaxRateOverride$outboundSchema,
} from "./dtotaxrateoverride.js";
import {
  TypesBillingCadence,
  TypesBillingCadence$outboundSchema,
} from "./typesbillingcadence.js";
import {
  TypesBillingCycle,
  TypesBillingCycle$outboundSchema,
} from "./typesbillingcycle.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$outboundSchema,
} from "./typesbillingperiod.js";
import {
  TypesCollectionMethod,
  TypesCollectionMethod$outboundSchema,
} from "./typescollectionmethod.js";
import {
  TypesInvoiceBilling,
  TypesInvoiceBilling$outboundSchema,
} from "./typesinvoicebilling.js";
import {
  TypesPaymentBehavior,
  TypesPaymentBehavior$outboundSchema,
} from "./typespaymentbehavior.js";
import {
  TypesPaymentTerms,
  TypesPaymentTerms$outboundSchema,
} from "./typespaymentterms.js";
import {
  TypesProrationBehavior,
  TypesProrationBehavior$outboundSchema,
} from "./typesprorationbehavior.js";
import {
  TypesSubscriptionStatus,
  TypesSubscriptionStatus$outboundSchema,
} from "./typessubscriptionstatus.js";

export type DtoCreateSubscriptionRequest = {
  /**
   * Addons represents addons to be added to the subscription during creation
   */
  addons?: Array<DtoAddAddonToSubscriptionRequest> | undefined;
  billingCadence: TypesBillingCadence;
  billingCycle?: TypesBillingCycle | undefined;
  billingPeriod: TypesBillingPeriod;
  billingPeriodCount?: number | undefined;
  collectionMethod?: TypesCollectionMethod | undefined;
  /**
   * CommitmentAmount is the minimum amount a customer commits to paying for a billing period
   */
  commitmentAmount?: string | undefined;
  commitmentDuration?: TypesBillingPeriod | undefined;
  coupons?: Array<string> | undefined;
  /**
   * Credit grants to be applied when subscription is created
   */
  creditGrants?: Array<DtoCreateCreditGrantRequest> | undefined;
  currency: string;
  /**
   * customer_id is the flexprice customer id
   *
   * @remarks
   * and it is prioritized over external_customer_id in case both are provided.
   */
  customerId?: string | undefined;
  /**
   * Timezone of the customer.
   *
   * @remarks
   * If not set, the default value is UTC.
   */
  customerTimezone?: string | undefined;
  /**
   * Enable Commitment True Up Fee
   */
  enableTrueUp?: boolean | undefined;
  endDate?: string | undefined;
  /**
   * external_customer_id is the customer id in your DB
   *
   * @remarks
   * and must be same as what you provided as external_id while creating the customer in flexprice.
   */
  externalCustomerId?: string | undefined;
  gatewayPaymentMethodId?: string | undefined;
  invoiceBilling?: TypesInvoiceBilling | undefined;
  /**
   * LineItemCommitments allows setting commitment configuration per line item (keyed by price_id)
   */
  lineItemCommitments?:
    | { [k: string]: DtoLineItemCommitmentConfig }
    | undefined;
  lineItemCoupons?: { [k: string]: Array<string> } | undefined;
  /**
   * LineItems are extra line items to add at creation (each with price_id or price), in addition to plan prices
   */
  lineItems?: Array<DtoCreateSubscriptionLineItemRequest> | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  /**
   * OverageFactor is a multiplier applied to usage beyond the commitment amount
   */
  overageFactor?: string | undefined;
  /**
   * OverrideEntitlements allows customizing specific entitlements for this subscription
   */
  overrideEntitlements?: Array<DtoOverrideEntitlementRequest> | undefined;
  /**
   * OverrideLineItems allows customizing specific prices for this subscription
   */
  overrideLineItems?: Array<DtoOverrideLineItemRequest> | undefined;
  /**
   * ParentSubscriptionID is the parent subscription ID for hierarchy (e.g. child subscription under a parent)
   */
  parentSubscriptionId?: string | undefined;
  paymentBehavior?: TypesPaymentBehavior | undefined;
  paymentTerms?: TypesPaymentTerms | undefined;
  /**
   * Phases represents subscription phases to be created with the subscription
   */
  phases?: Array<DtoSubscriptionPhaseCreateRequest> | undefined;
  planId: string;
  prorationBehavior?: TypesProrationBehavior | undefined;
  startDate?: string | undefined;
  subscriptionStatus?: TypesSubscriptionStatus | undefined;
  /**
   * tax_rate_overrides is the tax rate overrides	to be applied to the subscription
   */
  taxRateOverrides?: Array<DtoTaxRateOverride> | undefined;
  trialEnd?: string | undefined;
  trialStart?: string | undefined;
};

/** @internal */
export type DtoCreateSubscriptionRequest$Outbound = {
  addons?: Array<DtoAddAddonToSubscriptionRequest$Outbound> | undefined;
  billing_cadence: string;
  billing_cycle?: string | undefined;
  billing_period: string;
  billing_period_count?: number | undefined;
  collection_method?: string | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: string | undefined;
  coupons?: Array<string> | undefined;
  credit_grants?: Array<DtoCreateCreditGrantRequest$Outbound> | undefined;
  currency: string;
  customer_id?: string | undefined;
  customer_timezone?: string | undefined;
  enable_true_up?: boolean | undefined;
  end_date?: string | undefined;
  external_customer_id?: string | undefined;
  gateway_payment_method_id?: string | undefined;
  invoice_billing?: string | undefined;
  line_item_commitments?:
    | { [k: string]: DtoLineItemCommitmentConfig$Outbound }
    | undefined;
  line_item_coupons?: { [k: string]: Array<string> } | undefined;
  line_items?: Array<DtoCreateSubscriptionLineItemRequest$Outbound> | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  overage_factor?: string | undefined;
  override_entitlements?:
    | Array<DtoOverrideEntitlementRequest$Outbound>
    | undefined;
  override_line_items?: Array<DtoOverrideLineItemRequest$Outbound> | undefined;
  parent_subscription_id?: string | undefined;
  payment_behavior?: string | undefined;
  payment_terms?: string | undefined;
  phases?: Array<DtoSubscriptionPhaseCreateRequest$Outbound> | undefined;
  plan_id: string;
  proration_behavior?: string | undefined;
  start_date?: string | undefined;
  subscription_status?: string | undefined;
  tax_rate_overrides?: Array<DtoTaxRateOverride$Outbound> | undefined;
  trial_end?: string | undefined;
  trial_start?: string | undefined;
};

/** @internal */
export const DtoCreateSubscriptionRequest$outboundSchema: z.ZodType<
  DtoCreateSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  DtoCreateSubscriptionRequest
> = z.object({
  addons: z.array(DtoAddAddonToSubscriptionRequest$outboundSchema).optional(),
  billingCadence: TypesBillingCadence$outboundSchema,
  billingCycle: TypesBillingCycle$outboundSchema.optional(),
  billingPeriod: TypesBillingPeriod$outboundSchema,
  billingPeriodCount: z.number().int().optional(),
  collectionMethod: TypesCollectionMethod$outboundSchema.optional(),
  commitmentAmount: z.string().optional(),
  commitmentDuration: TypesBillingPeriod$outboundSchema.optional(),
  coupons: z.array(z.string()).optional(),
  creditGrants: z.array(DtoCreateCreditGrantRequest$outboundSchema).optional(),
  currency: z.string(),
  customerId: z.string().optional(),
  customerTimezone: z.string().optional(),
  enableTrueUp: z.boolean().optional(),
  endDate: z.string().optional(),
  externalCustomerId: z.string().optional(),
  gatewayPaymentMethodId: z.string().optional(),
  invoiceBilling: TypesInvoiceBilling$outboundSchema.optional(),
  lineItemCommitments: z.record(DtoLineItemCommitmentConfig$outboundSchema)
    .optional(),
  lineItemCoupons: z.record(z.array(z.string())).optional(),
  lineItems: z.array(DtoCreateSubscriptionLineItemRequest$outboundSchema)
    .optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  overageFactor: z.string().optional(),
  overrideEntitlements: z.array(DtoOverrideEntitlementRequest$outboundSchema)
    .optional(),
  overrideLineItems: z.array(DtoOverrideLineItemRequest$outboundSchema)
    .optional(),
  parentSubscriptionId: z.string().optional(),
  paymentBehavior: TypesPaymentBehavior$outboundSchema.optional(),
  paymentTerms: TypesPaymentTerms$outboundSchema.optional(),
  phases: z.array(DtoSubscriptionPhaseCreateRequest$outboundSchema).optional(),
  planId: z.string(),
  prorationBehavior: TypesProrationBehavior$outboundSchema.optional(),
  startDate: z.string().optional(),
  subscriptionStatus: TypesSubscriptionStatus$outboundSchema.optional(),
  taxRateOverrides: z.array(DtoTaxRateOverride$outboundSchema).optional(),
  trialEnd: z.string().optional(),
  trialStart: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    billingCadence: "billing_cadence",
    billingCycle: "billing_cycle",
    billingPeriod: "billing_period",
    billingPeriodCount: "billing_period_count",
    collectionMethod: "collection_method",
    commitmentAmount: "commitment_amount",
    commitmentDuration: "commitment_duration",
    creditGrants: "credit_grants",
    customerId: "customer_id",
    customerTimezone: "customer_timezone",
    enableTrueUp: "enable_true_up",
    endDate: "end_date",
    externalCustomerId: "external_customer_id",
    gatewayPaymentMethodId: "gateway_payment_method_id",
    invoiceBilling: "invoice_billing",
    lineItemCommitments: "line_item_commitments",
    lineItemCoupons: "line_item_coupons",
    lineItems: "line_items",
    lookupKey: "lookup_key",
    overageFactor: "overage_factor",
    overrideEntitlements: "override_entitlements",
    overrideLineItems: "override_line_items",
    parentSubscriptionId: "parent_subscription_id",
    paymentBehavior: "payment_behavior",
    paymentTerms: "payment_terms",
    planId: "plan_id",
    prorationBehavior: "proration_behavior",
    startDate: "start_date",
    subscriptionStatus: "subscription_status",
    taxRateOverrides: "tax_rate_overrides",
    trialEnd: "trial_end",
    trialStart: "trial_start",
  });
});

export function dtoCreateSubscriptionRequestToJSON(
  dtoCreateSubscriptionRequest: DtoCreateSubscriptionRequest,
): string {
  return JSON.stringify(
    DtoCreateSubscriptionRequest$outboundSchema.parse(
      dtoCreateSubscriptionRequest,
    ),
  );
}
