/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type DtoCreateCostsheetRequest = {
  description?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
};

/** @internal */
export type DtoCreateCostsheetRequest$Outbound = {
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
};

/** @internal */
export const DtoCreateCostsheetRequest$outboundSchema: z.ZodType<
  DtoCreateCostsheetRequest$Outbound,
  z.ZodTypeDef,
  DtoCreateCostsheetRequest
> = z.object({
  description: z.string().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string(),
}).transform((v) => {
  return remap$(v, {
    lookupKey: "lookup_key",
  });
});

export function dtoCreateCostsheetRequestToJSON(
  dtoCreateCostsheetRequest: DtoCreateCostsheetRequest,
): string {
  return JSON.stringify(
    DtoCreateCostsheetRequest$outboundSchema.parse(dtoCreateCostsheetRequest),
  );
}
