/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$inboundSchema,
} from "./dtoentitlementresponse.js";

export type DtoCreateBulkEntitlementResponse = {
  items?: Array<DtoEntitlementResponse> | undefined;
};

/** @internal */
export const DtoCreateBulkEntitlementResponse$inboundSchema: z.ZodType<
  DtoCreateBulkEntitlementResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoEntitlementResponse$inboundSchema).optional(),
});

export function dtoCreateBulkEntitlementResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCreateBulkEntitlementResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCreateBulkEntitlementResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCreateBulkEntitlementResponse' from JSON`,
  );
}
