/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";

/**
 * Customer response object containing all customer information
 */
export type DtoCustomerResponse = {
  /**
   * AddressCity is the city of the customer's address
   */
  addressCity?: string | undefined;
  /**
   * AddressCountry is the country of the customer's address (ISO 3166-1 alpha-2)
   */
  addressCountry?: string | undefined;
  /**
   * AddressLine1 is the first line of the customer's address
   */
  addressLine1?: string | undefined;
  /**
   * AddressLine2 is the second line of the customer's address
   */
  addressLine2?: string | undefined;
  /**
   * AddressPostalCode is the postal code of the customer's address
   */
  addressPostalCode?: string | undefined;
  /**
   * AddressState is the state of the customer's address
   */
  addressState?: string | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  /**
   * Email is the email of the customer
   */
  email?: string | undefined;
  /**
   * EnvironmentID is the environment identifier for the customer
   */
  environmentId?: string | undefined;
  /**
   * ExternalID is the external identifier for the customer
   */
  externalId?: string | undefined;
  /**
   * ID is the unique identifier for the customer
   */
  id?: string | undefined;
  /**
   * Metadata
   */
  metadata?: { [k: string]: string } | undefined;
  /**
   * Name is the name of the customer
   */
  name?: string | undefined;
  /**
   * Customer response object containing all customer information
   */
  parentCustomer?: DtoCustomerResponse | undefined;
  /**
   * ParentCustomerID is the parent customer identifier for the customer
   */
  parentCustomerId?: string | undefined;
  status?: TypesStatus | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoCustomerResponse$inboundSchema: z.ZodType<
  DtoCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  address_city: z.string().optional(),
  address_country: z.string().optional(),
  address_line1: z.string().optional(),
  address_line2: z.string().optional(),
  address_postal_code: z.string().optional(),
  address_state: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  email: z.string().optional(),
  environment_id: z.string().optional(),
  external_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
  parent_customer: z.lazy(() => DtoCustomerResponse$inboundSchema).optional(),
  parent_customer_id: z.string().optional(),
  status: TypesStatus$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "address_city": "addressCity",
    "address_country": "addressCountry",
    "address_line1": "addressLine1",
    "address_line2": "addressLine2",
    "address_postal_code": "addressPostalCode",
    "address_state": "addressState",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "environment_id": "environmentId",
    "external_id": "externalId",
    "parent_customer": "parentCustomer",
    "parent_customer_id": "parentCustomerId",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoCustomerResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCustomerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCustomerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCustomerResponse' from JSON`,
  );
}
