/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { DtoCostPoint, DtoCostPoint$inboundSchema } from "./dtocostpoint.js";
import { MeterMeter, MeterMeter$inboundSchema } from "./metermeter.js";
import { PricePrice, PricePrice$inboundSchema } from "./priceprice.js";

export type DtoCostAnalyticItem = {
  /**
   * Breakdown
   */
  costByPeriod?: Array<DtoCostPoint> | undefined;
  costsheetId?: string | undefined;
  /**
   * Metadata
   */
  currency?: string | undefined;
  customerId?: string | undefined;
  externalCustomerId?: string | undefined;
  meter?: MeterMeter | undefined;
  meterId?: string | undefined;
  meterName?: string | undefined;
  price?: PricePrice | undefined;
  priceId?: string | undefined;
  properties?: { [k: string]: string } | undefined;
  source?: string | undefined;
  /**
   * Aggregated metrics
   */
  totalCost?: string | undefined;
  totalEvents?: number | undefined;
  totalQuantity?: string | undefined;
};

/** @internal */
export const DtoCostAnalyticItem$inboundSchema: z.ZodType<
  DtoCostAnalyticItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  cost_by_period: z.array(DtoCostPoint$inboundSchema).optional(),
  costsheet_id: z.string().optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  external_customer_id: z.string().optional(),
  meter: MeterMeter$inboundSchema.optional(),
  meter_id: z.string().optional(),
  meter_name: z.string().optional(),
  price: PricePrice$inboundSchema.optional(),
  price_id: z.string().optional(),
  properties: z.record(z.string()).optional(),
  source: z.string().optional(),
  total_cost: z.string().optional(),
  total_events: z.number().int().optional(),
  total_quantity: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cost_by_period": "costByPeriod",
    "costsheet_id": "costsheetId",
    "customer_id": "customerId",
    "external_customer_id": "externalCustomerId",
    "meter_id": "meterId",
    "meter_name": "meterName",
    "price_id": "priceId",
    "total_cost": "totalCost",
    "total_events": "totalEvents",
    "total_quantity": "totalQuantity",
  });
});

export function dtoCostAnalyticItemFromJSON(
  jsonString: string,
): SafeParseResult<DtoCostAnalyticItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCostAnalyticItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCostAnalyticItem' from JSON`,
  );
}
