/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const DtoEntitlementSourceEntityType = {
  Plan: "plan",
  Addon: "addon",
  Subscription: "subscription",
} as const;
export type DtoEntitlementSourceEntityType = ClosedEnum<
  typeof DtoEntitlementSourceEntityType
>;

/** @internal */
export const DtoEntitlementSourceEntityType$inboundSchema: z.ZodNativeEnum<
  typeof DtoEntitlementSourceEntityType
> = z.nativeEnum(DtoEntitlementSourceEntityType);
