/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DtoEventCostInfo = {
  costNanoUsd?: string | undefined;
  requestId?: string | undefined;
};

/** @internal */
export const DtoEventCostInfo$inboundSchema: z.ZodType<
  DtoEventCostInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  costNanoUsd: z.string().optional(),
  requestId: z.string().optional(),
});

export function dtoEventCostInfoFromJSON(
  jsonString: string,
): SafeParseResult<DtoEventCostInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoEventCostInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoEventCostInfo' from JSON`,
  );
}
