/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DtoEvent = {
  customerId?: string | undefined;
  environmentId?: string | undefined;
  eventName?: string | undefined;
  externalCustomerId?: string | undefined;
  id?: string | undefined;
  properties?: { [k: string]: any } | undefined;
  source?: string | undefined;
  timestamp?: string | undefined;
};

/** @internal */
export const DtoEvent$inboundSchema: z.ZodType<
  DtoEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string().optional(),
  environment_id: z.string().optional(),
  event_name: z.string().optional(),
  external_customer_id: z.string().optional(),
  id: z.string().optional(),
  properties: z.record(z.any()).optional(),
  source: z.string().optional(),
  timestamp: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "environment_id": "environmentId",
    "event_name": "eventName",
    "external_customer_id": "externalCustomerId",
  });
});

export function dtoEventFromJSON(
  jsonString: string,
): SafeParseResult<DtoEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoEvent' from JSON`,
  );
}
