/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DtoFeatureUsageInfo = {
  customerId?: string | undefined;
  featureId?: string | undefined;
  meterId?: string | undefined;
  priceId?: string | undefined;
  processedAt?: string | undefined;
  qtyTotal?: string | undefined;
  subLineItemId?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const DtoFeatureUsageInfo$inboundSchema: z.ZodType<
  DtoFeatureUsageInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string().optional(),
  feature_id: z.string().optional(),
  meter_id: z.string().optional(),
  price_id: z.string().optional(),
  processed_at: z.string().optional(),
  qty_total: z.string().optional(),
  sub_line_item_id: z.string().optional(),
  subscription_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "feature_id": "featureId",
    "meter_id": "meterId",
    "price_id": "priceId",
    "processed_at": "processedAt",
    "qty_total": "qtyTotal",
    "sub_line_item_id": "subLineItemId",
    "subscription_id": "subscriptionId",
  });
});

export function dtoFeatureUsageInfoFromJSON(
  jsonString: string,
): SafeParseResult<DtoFeatureUsageInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoFeatureUsageInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoFeatureUsageInfo' from JSON`,
  );
}
