/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  TypesWindowSize,
  TypesWindowSize$outboundSchema,
} from "./typeswindowsize.js";

export type DtoGetUsageAnalyticsRequest = {
  endTime?: string | undefined;
  /**
   * allowed values: "price", "meter", "feature", "subscription_line_item","plan","addon"
   */
  expand?: Array<string> | undefined;
  externalCustomerId: string;
  featureIds?: Array<string> | undefined;
  /**
   * allowed values: "source", "feature_id", "properties.<field_name>"
   */
  groupBy?: Array<string> | undefined;
  /**
   * Property filters to filter the events by the keys in `properties` field of the event
   */
  propertyFilters?: { [k: string]: Array<string> } | undefined;
  sources?: Array<string> | undefined;
  startTime?: string | undefined;
  windowSize?: TypesWindowSize | undefined;
};

/** @internal */
export type DtoGetUsageAnalyticsRequest$Outbound = {
  end_time?: string | undefined;
  expand?: Array<string> | undefined;
  external_customer_id: string;
  feature_ids?: Array<string> | undefined;
  group_by?: Array<string> | undefined;
  property_filters?: { [k: string]: Array<string> } | undefined;
  sources?: Array<string> | undefined;
  start_time?: string | undefined;
  window_size?: string | undefined;
};

/** @internal */
export const DtoGetUsageAnalyticsRequest$outboundSchema: z.ZodType<
  DtoGetUsageAnalyticsRequest$Outbound,
  z.ZodTypeDef,
  DtoGetUsageAnalyticsRequest
> = z.object({
  endTime: z.string().optional(),
  expand: z.array(z.string()).optional(),
  externalCustomerId: z.string(),
  featureIds: z.array(z.string()).optional(),
  groupBy: z.array(z.string()).optional(),
  propertyFilters: z.record(z.array(z.string())).optional(),
  sources: z.array(z.string()).optional(),
  startTime: z.string().optional(),
  windowSize: TypesWindowSize$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    externalCustomerId: "external_customer_id",
    featureIds: "feature_ids",
    groupBy: "group_by",
    propertyFilters: "property_filters",
    startTime: "start_time",
    windowSize: "window_size",
  });
});

export function dtoGetUsageAnalyticsRequestToJSON(
  dtoGetUsageAnalyticsRequest: DtoGetUsageAnalyticsRequest,
): string {
  return JSON.stringify(
    DtoGetUsageAnalyticsRequest$outboundSchema.parse(
      dtoGetUsageAnalyticsRequest,
    ),
  );
}
