/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoWalletTransactionResponse,
  DtoWalletTransactionResponse$inboundSchema,
} from "./dtowallettransactionresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./typespaginationresponse.js";

export type DtoListWalletTransactionsResponse = {
  items?: Array<DtoWalletTransactionResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListWalletTransactionsResponse$inboundSchema: z.ZodType<
  DtoListWalletTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoWalletTransactionResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function dtoListWalletTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListWalletTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListWalletTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListWalletTransactionsResponse' from JSON`,
  );
}
