/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoScheduledTaskResponse,
  DtoScheduledTaskResponse$inboundSchema,
} from "./dtoscheduledtaskresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./typespaginationresponse.js";

export type DtoListScheduledTasksResponse = {
  items?: Array<DtoScheduledTaskResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListScheduledTasksResponse$inboundSchema: z.ZodType<
  DtoListScheduledTasksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoScheduledTaskResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function dtoListScheduledTasksResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListScheduledTasksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListScheduledTasksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListScheduledTasksResponse' from JSON`,
  );
}
