/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoUserResponse,
  DtoUserResponse$inboundSchema,
} from "./dtouserresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./typespaginationresponse.js";

export type DtoListUsersResponse = {
  items?: Array<DtoUserResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListUsersResponse$inboundSchema: z.ZodType<
  DtoListUsersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoUserResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function dtoListUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListUsersResponse' from JSON`,
  );
}
