/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoMatchedPrice,
  DtoMatchedPrice$inboundSchema,
} from "./dtomatchedprice.js";
import {
  ErrorsErrorResponse,
  ErrorsErrorResponse$inboundSchema,
} from "./errorserrorresponse.js";
import {
  TypesDebugTrackerStatus,
  TypesDebugTrackerStatus$inboundSchema,
} from "./typesdebugtrackerstatus.js";

export type DtoPriceLookupResult = {
  error?: ErrorsErrorResponse | undefined;
  matchedPrices?: Array<DtoMatchedPrice> | undefined;
  status?: TypesDebugTrackerStatus | undefined;
};

/** @internal */
export const DtoPriceLookupResult$inboundSchema: z.ZodType<
  DtoPriceLookupResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: ErrorsErrorResponse$inboundSchema.optional(),
  matched_prices: z.array(DtoMatchedPrice$inboundSchema).optional(),
  status: TypesDebugTrackerStatus$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "matched_prices": "matchedPrices",
  });
});

export function dtoPriceLookupResultFromJSON(
  jsonString: string,
): SafeParseResult<DtoPriceLookupResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoPriceLookupResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoPriceLookupResult' from JSON`,
  );
}
