/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  TypesResumeMode,
  TypesResumeMode$outboundSchema,
} from "./typesresumemode.js";

/**
 * Request object for resuming a paused subscription
 */
export type DtoResumeSubscriptionRequest = {
  /**
   * Whether to perform a dry run
   *
   * @remarks
   * @Description If true, validates the request and shows impact without actually resuming the subscription
   * @Example false
   */
  dryRun?: boolean | undefined;
  /**
   * Additional metadata as key-value pairs
   *
   * @remarks
   * @Description Optional metadata for storing additional information about the resume operation
   * @Example {"resumed_by": "admin", "reason": "issue_resolved"}
   */
  metadata?: { [k: string]: string } | undefined;
  resumeMode: TypesResumeMode;
};

/** @internal */
export type DtoResumeSubscriptionRequest$Outbound = {
  dry_run?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  resume_mode: string;
};

/** @internal */
export const DtoResumeSubscriptionRequest$outboundSchema: z.ZodType<
  DtoResumeSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  DtoResumeSubscriptionRequest
> = z.object({
  dryRun: z.boolean().optional(),
  metadata: z.record(z.string()).optional(),
  resumeMode: TypesResumeMode$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dryRun: "dry_run",
    resumeMode: "resume_mode",
  });
});

export function dtoResumeSubscriptionRequestToJSON(
  dtoResumeSubscriptionRequest: DtoResumeSubscriptionRequest,
): string {
  return JSON.stringify(
    DtoResumeSubscriptionRequest$outboundSchema.parse(
      dtoResumeSubscriptionRequest,
    ),
  );
}
