/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoCreditGrantResponse,
  DtoCreditGrantResponse$inboundSchema,
} from "./dtocreditgrantresponse.js";
import {
  DtoInvoiceResponse,
  DtoInvoiceResponse$inboundSchema,
} from "./dtoinvoiceresponse.js";
import {
  DtoProrationDetails,
  DtoProrationDetails$inboundSchema,
} from "./dtoprorationdetails.js";
import {
  DtoSubscriptionSummary,
  DtoSubscriptionSummary$inboundSchema,
} from "./dtosubscriptionsummary.js";
import {
  TypesSubscriptionChangeType,
  TypesSubscriptionChangeType$inboundSchema,
} from "./typessubscriptionchangetype.js";

/**
 * Response after successfully executing a subscription plan change
 */
export type DtoSubscriptionChangeExecuteResponse = {
  changeType?: TypesSubscriptionChangeType | undefined;
  /**
   * credit_grants contains any credit grants created for proration credits
   */
  creditGrants?: Array<DtoCreditGrantResponse> | undefined;
  /**
   * effective_date is when the change took effect
   */
  effectiveDate?: string | undefined;
  invoice?: DtoInvoiceResponse | undefined;
  /**
   * is_scheduled indicates if the change was scheduled or executed immediately
   */
  isScheduled?: boolean | undefined;
  /**
   * metadata from the request
   */
  metadata?: { [k: string]: string } | undefined;
  newSubscription?: DtoSubscriptionSummary | undefined;
  oldSubscription?: DtoSubscriptionSummary | undefined;
  prorationApplied?: DtoProrationDetails | undefined;
  /**
   * schedule_id is the ID of the created schedule (only if is_scheduled=true)
   */
  scheduleId?: string | undefined;
  /**
   * scheduled_at is when the change will execute (only if is_scheduled=true)
   */
  scheduledAt?: string | undefined;
};

/** @internal */
export const DtoSubscriptionChangeExecuteResponse$inboundSchema: z.ZodType<
  DtoSubscriptionChangeExecuteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  change_type: TypesSubscriptionChangeType$inboundSchema.optional(),
  credit_grants: z.array(DtoCreditGrantResponse$inboundSchema).optional(),
  effective_date: z.string().optional(),
  invoice: DtoInvoiceResponse$inboundSchema.optional(),
  is_scheduled: z.boolean().optional(),
  metadata: z.record(z.string()).optional(),
  new_subscription: DtoSubscriptionSummary$inboundSchema.optional(),
  old_subscription: DtoSubscriptionSummary$inboundSchema.optional(),
  proration_applied: DtoProrationDetails$inboundSchema.optional(),
  schedule_id: z.string().optional(),
  scheduled_at: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "change_type": "changeType",
    "credit_grants": "creditGrants",
    "effective_date": "effectiveDate",
    "is_scheduled": "isScheduled",
    "new_subscription": "newSubscription",
    "old_subscription": "oldSubscription",
    "proration_applied": "prorationApplied",
    "schedule_id": "scheduleId",
    "scheduled_at": "scheduledAt",
  });
});

export function dtoSubscriptionChangeExecuteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoSubscriptionChangeExecuteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DtoSubscriptionChangeExecuteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoSubscriptionChangeExecuteResponse' from JSON`,
  );
}
