/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dtowalletresponse.js";
import {
  DtoWalletTransactionResponse,
  DtoWalletTransactionResponse$inboundSchema,
} from "./dtowallettransactionresponse.js";

export type DtoTopUpWalletResponse = {
  /**
   * Invoice ID if an invoice was created (only for PURCHASED_CREDIT_INVOICED)
   */
  invoiceId?: string | undefined;
  wallet?: DtoWalletResponse | undefined;
  walletTransaction?: DtoWalletTransactionResponse | undefined;
};

/** @internal */
export const DtoTopUpWalletResponse$inboundSchema: z.ZodType<
  DtoTopUpWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  invoice_id: z.string().optional(),
  wallet: DtoWalletResponse$inboundSchema.optional(),
  wallet_transaction: DtoWalletTransactionResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "invoice_id": "invoiceId",
    "wallet_transaction": "walletTransaction",
  });
});

export function dtoTopUpWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoTopUpWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoTopUpWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoTopUpWalletResponse' from JSON`,
  );
}
