/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$inboundSchema,
} from "./dtotaxrateresponse.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";
import {
  TypesTaxRateEntityType,
  TypesTaxRateEntityType$inboundSchema,
} from "./typestaxrateentitytype.js";

export type DtoTaxAppliedResponse = {
  appliedAt?: string | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  currency?: string | undefined;
  entityId?: string | undefined;
  entityType?: TypesTaxRateEntityType | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  idempotencyKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  status?: TypesStatus | undefined;
  taxAmount?: string | undefined;
  taxAssociationId?: string | undefined;
  taxRate?: DtoTaxRateResponse | undefined;
  taxRateId?: string | undefined;
  taxableAmount?: string | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoTaxAppliedResponse$inboundSchema: z.ZodType<
  DtoTaxAppliedResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  applied_at: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TypesTaxRateEntityType$inboundSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  status: TypesStatus$inboundSchema.optional(),
  tax_amount: z.string().optional(),
  tax_association_id: z.string().optional(),
  tax_rate: DtoTaxRateResponse$inboundSchema.optional(),
  tax_rate_id: z.string().optional(),
  taxable_amount: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "applied_at": "appliedAt",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "entity_id": "entityId",
    "entity_type": "entityType",
    "environment_id": "environmentId",
    "idempotency_key": "idempotencyKey",
    "tax_amount": "taxAmount",
    "tax_association_id": "taxAssociationId",
    "tax_rate": "taxRate",
    "tax_rate_id": "taxRateId",
    "taxable_amount": "taxableAmount",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoTaxAppliedResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoTaxAppliedResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoTaxAppliedResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoTaxAppliedResponse' from JSON`,
  );
}
