/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoAddress,
  DtoAddress$inboundSchema,
  DtoAddress$Outbound,
  DtoAddress$outboundSchema,
} from "./dtoaddress.js";

export type DtoTenantBillingDetails = {
  address?: DtoAddress | undefined;
  email?: string | undefined;
  helpEmail?: string | undefined;
  phone?: string | undefined;
};

/** @internal */
export const DtoTenantBillingDetails$inboundSchema: z.ZodType<
  DtoTenantBillingDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: DtoAddress$inboundSchema.optional(),
  email: z.string().optional(),
  help_email: z.string().optional(),
  phone: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "help_email": "helpEmail",
  });
});
/** @internal */
export type DtoTenantBillingDetails$Outbound = {
  address?: DtoAddress$Outbound | undefined;
  email?: string | undefined;
  help_email?: string | undefined;
  phone?: string | undefined;
};

/** @internal */
export const DtoTenantBillingDetails$outboundSchema: z.ZodType<
  DtoTenantBillingDetails$Outbound,
  z.ZodTypeDef,
  DtoTenantBillingDetails
> = z.object({
  address: DtoAddress$outboundSchema.optional(),
  email: z.string().optional(),
  helpEmail: z.string().optional(),
  phone: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    helpEmail: "help_email",
  });
});

export function dtoTenantBillingDetailsToJSON(
  dtoTenantBillingDetails: DtoTenantBillingDetails,
): string {
  return JSON.stringify(
    DtoTenantBillingDetails$outboundSchema.parse(dtoTenantBillingDetails),
  );
}
export function dtoTenantBillingDetailsFromJSON(
  jsonString: string,
): SafeParseResult<DtoTenantBillingDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoTenantBillingDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoTenantBillingDetails' from JSON`,
  );
}
