/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  MeterFilter,
  MeterFilter$Outbound,
  MeterFilter$outboundSchema,
} from "./meterfilter.js";
import {
  TypesAlertSettings,
  TypesAlertSettings$Outbound,
  TypesAlertSettings$outboundSchema,
} from "./typesalertsettings.js";

export type DtoUpdateFeatureRequest = {
  alertSettings?: TypesAlertSettings | undefined;
  description?: string | undefined;
  filters?: Array<MeterFilter> | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  unitPlural?: string | undefined;
  unitSingular?: string | undefined;
};

/** @internal */
export type DtoUpdateFeatureRequest$Outbound = {
  alert_settings?: TypesAlertSettings$Outbound | undefined;
  description?: string | undefined;
  filters?: Array<MeterFilter$Outbound> | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

/** @internal */
export const DtoUpdateFeatureRequest$outboundSchema: z.ZodType<
  DtoUpdateFeatureRequest$Outbound,
  z.ZodTypeDef,
  DtoUpdateFeatureRequest
> = z.object({
  alertSettings: TypesAlertSettings$outboundSchema.optional(),
  description: z.string().optional(),
  filters: z.array(MeterFilter$outboundSchema).optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
  unitPlural: z.string().optional(),
  unitSingular: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    alertSettings: "alert_settings",
    unitPlural: "unit_plural",
    unitSingular: "unit_singular",
  });
});

export function dtoUpdateFeatureRequestToJSON(
  dtoUpdateFeatureRequest: DtoUpdateFeatureRequest,
): string {
  return JSON.stringify(
    DtoUpdateFeatureRequest$outboundSchema.parse(dtoUpdateFeatureRequest),
  );
}
