/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoCostsheetResponse,
  DtoCostsheetResponse$inboundSchema,
} from "./dtocostsheetresponse.js";

export type DtoUpdateCostsheetResponse = {
  costsheet?: DtoCostsheetResponse | undefined;
};

/** @internal */
export const DtoUpdateCostsheetResponse$inboundSchema: z.ZodType<
  DtoUpdateCostsheetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  costsheet: DtoCostsheetResponse$inboundSchema.optional(),
});

export function dtoUpdateCostsheetResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoUpdateCostsheetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoUpdateCostsheetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoUpdateCostsheetResponse' from JSON`,
  );
}
