/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoTenantResponse,
  DtoTenantResponse$inboundSchema,
} from "./dtotenantresponse.js";
import { TypesUserType, TypesUserType$inboundSchema } from "./typesusertype.js";

export type DtoUserResponse = {
  /**
   * Empty for service accounts
   */
  email?: string | undefined;
  id?: string | undefined;
  roles?: Array<string> | undefined;
  tenant?: DtoTenantResponse | undefined;
  type?: TypesUserType | undefined;
};

/** @internal */
export const DtoUserResponse$inboundSchema: z.ZodType<
  DtoUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().optional(),
  id: z.string().optional(),
  roles: z.array(z.string()).optional(),
  tenant: DtoTenantResponse$inboundSchema.optional(),
  type: TypesUserType$inboundSchema.optional(),
});

export function dtoUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoUserResponse' from JSON`,
  );
}
