/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TypesAlertSettings,
  TypesAlertSettings$inboundSchema,
} from "./typesalertsettings.js";
import {
  TypesAlertState,
  TypesAlertState$inboundSchema,
} from "./typesalertstate.js";
import {
  TypesAutoTopup,
  TypesAutoTopup$inboundSchema,
} from "./typesautotopup.js";
import {
  TypesCreditBreakdown,
  TypesCreditBreakdown$inboundSchema,
} from "./typescreditbreakdown.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";
import {
  TypesWalletConfig,
  TypesWalletConfig$inboundSchema,
} from "./typeswalletconfig.js";
import {
  TypesWalletStatus,
  TypesWalletStatus$inboundSchema,
} from "./typeswalletstatus.js";
import {
  TypesWalletType,
  TypesWalletType$inboundSchema,
} from "./typeswallettype.js";

export type DtoWalletResponse = {
  alertSettings?: TypesAlertSettings | undefined;
  alertState?: TypesAlertState | undefined;
  autoTopup?: TypesAutoTopup | undefined;
  balance?: string | undefined;
  config?: TypesWalletConfig | undefined;
  /**
   * amount in the currency =  number of credits * conversion_rate
   *
   * @remarks
   * ex if conversion_rate is 1, then 1 USD = 1 credit
   * ex if conversion_rate is 2, then 1 USD = 0.5 credits
   * ex if conversion_rate is 0.5, then 1 USD = 2 credits
   */
  conversionRate?: string | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  creditBalance?: string | undefined;
  creditsAvailableBreakdown?: TypesCreditBreakdown | undefined;
  currency?: string | undefined;
  customerId?: string | undefined;
  description?: string | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: TypesStatus | undefined;
  tenantId?: string | undefined;
  /**
   * topup_conversion_rate is the conversion rate for the topup to the currency
   *
   * @remarks
   * ex if topup_conversion_rate is 1, then 1 USD = 1 credit
   * ex if topup_conversion_rate is 2, then 1 USD = 0.5 credits
   * ex if topup_conversion_rate is 0.5, then 1 USD = 2 credits
   */
  topupConversionRate?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
  walletStatus?: TypesWalletStatus | undefined;
  walletType?: TypesWalletType | undefined;
};

/** @internal */
export const DtoWalletResponse$inboundSchema: z.ZodType<
  DtoWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  alert_settings: TypesAlertSettings$inboundSchema.optional(),
  alert_state: TypesAlertState$inboundSchema.optional(),
  auto_topup: TypesAutoTopup$inboundSchema.optional(),
  balance: z.string().optional(),
  config: TypesWalletConfig$inboundSchema.optional(),
  conversion_rate: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  credit_balance: z.string().optional(),
  credits_available_breakdown: TypesCreditBreakdown$inboundSchema.optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
  status: TypesStatus$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  topup_conversion_rate: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  wallet_status: TypesWalletStatus$inboundSchema.optional(),
  wallet_type: TypesWalletType$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "alert_settings": "alertSettings",
    "alert_state": "alertState",
    "auto_topup": "autoTopup",
    "conversion_rate": "conversionRate",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "credit_balance": "creditBalance",
    "credits_available_breakdown": "creditsAvailableBreakdown",
    "customer_id": "customerId",
    "environment_id": "environmentId",
    "tenant_id": "tenantId",
    "topup_conversion_rate": "topupConversionRate",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
    "wallet_status": "walletStatus",
    "wallet_type": "walletType",
  });
});

export function dtoWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoWalletResponse' from JSON`,
  );
}
