/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ModelsTemporalWorkflowResult = {
  message?: string | undefined;
  runId?: string | undefined;
  workflowId?: string | undefined;
};

/** @internal */
export const ModelsTemporalWorkflowResult$inboundSchema: z.ZodType<
  ModelsTemporalWorkflowResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  run_id: z.string().optional(),
  workflow_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "run_id": "runId",
    "workflow_id": "workflowId",
  });
});

export function modelsTemporalWorkflowResultFromJSON(
  jsonString: string,
): SafeParseResult<ModelsTemporalWorkflowResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsTemporalWorkflowResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsTemporalWorkflowResult' from JSON`,
  );
}
