/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ResetUsage = {
  BillingPeriod: "BILLING_PERIOD",
  Never: "NEVER",
} as const;
export type ResetUsage = ClosedEnum<typeof ResetUsage>;

/** @internal */
export const ResetUsage$inboundSchema: z.ZodNativeEnum<typeof ResetUsage> = z
  .nativeEnum(ResetUsage);
/** @internal */
export const ResetUsage$outboundSchema: z.ZodNativeEnum<typeof ResetUsage> =
  ResetUsage$inboundSchema;
