/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SecretProvider = {
  Flexprice: "flexprice",
  Stripe: "stripe",
  S3: "s3",
  Hubspot: "hubspot",
  Razorpay: "razorpay",
  Chargebee: "chargebee",
  Quickbooks: "quickbooks",
  Nomod: "nomod",
  Moyasar: "moyasar",
} as const;
export type SecretProvider = ClosedEnum<typeof SecretProvider>;

/** @internal */
export const SecretProvider$inboundSchema: z.ZodNativeEnum<
  typeof SecretProvider
> = z.nativeEnum(SecretProvider);
/** @internal */
export const SecretProvider$outboundSchema: z.ZodNativeEnum<
  typeof SecretProvider
> = SecretProvider$inboundSchema;
