/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PricePrice, PricePrice$inboundSchema } from "./priceprice.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$inboundSchema,
} from "./typesbillingperiod.js";
import {
  TypesCommitmentType,
  TypesCommitmentType$inboundSchema,
} from "./typescommitmenttype.js";
import {
  TypesInvoiceCadence,
  TypesInvoiceCadence$inboundSchema,
} from "./typesinvoicecadence.js";
import {
  TypesPriceType,
  TypesPriceType$inboundSchema,
} from "./typespricetype.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";
import {
  TypesSubscriptionLineItemEntityType,
  TypesSubscriptionLineItemEntityType$inboundSchema,
} from "./typessubscriptionlineitementitytype.js";

export type SubscriptionSubscriptionLineItem = {
  billingPeriod?: TypesBillingPeriod | undefined;
  /**
   * from price at create; default 1
   */
  billingPeriodCount?: number | undefined;
  /**
   * Commitment fields
   */
  commitmentAmount?: string | undefined;
  commitmentDuration?: TypesBillingPeriod | undefined;
  commitmentOverageFactor?: string | undefined;
  commitmentQuantity?: string | undefined;
  commitmentTrueUpEnabled?: boolean | undefined;
  commitmentType?: TypesCommitmentType | undefined;
  commitmentWindowed?: boolean | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  currency?: string | undefined;
  customerId?: string | undefined;
  displayName?: string | undefined;
  endDate?: string | undefined;
  entityId?: string | undefined;
  entityType?: TypesSubscriptionLineItemEntityType | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  invoiceCadence?: TypesInvoiceCadence | undefined;
  metadata?: { [k: string]: string } | undefined;
  meterDisplayName?: string | undefined;
  meterId?: string | undefined;
  planDisplayName?: string | undefined;
  price?: PricePrice | undefined;
  priceId?: string | undefined;
  priceType?: TypesPriceType | undefined;
  priceUnit?: string | undefined;
  priceUnitId?: string | undefined;
  quantity?: string | undefined;
  startDate?: string | undefined;
  status?: TypesStatus | undefined;
  subscriptionId?: string | undefined;
  subscriptionPhaseId?: string | undefined;
  tenantId?: string | undefined;
  trialPeriod?: number | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const SubscriptionSubscriptionLineItem$inboundSchema: z.ZodType<
  SubscriptionSubscriptionLineItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_period: TypesBillingPeriod$inboundSchema.optional(),
  billing_period_count: z.number().int().optional(),
  commitment_amount: z.string().optional(),
  commitment_duration: TypesBillingPeriod$inboundSchema.optional(),
  commitment_overage_factor: z.string().optional(),
  commitment_quantity: z.string().optional(),
  commitment_true_up_enabled: z.boolean().optional(),
  commitment_type: TypesCommitmentType$inboundSchema.optional(),
  commitment_windowed: z.boolean().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  display_name: z.string().optional(),
  end_date: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TypesSubscriptionLineItemEntityType$inboundSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  invoice_cadence: TypesInvoiceCadence$inboundSchema.optional(),
  metadata: z.record(z.string()).optional(),
  meter_display_name: z.string().optional(),
  meter_id: z.string().optional(),
  plan_display_name: z.string().optional(),
  price: PricePrice$inboundSchema.optional(),
  price_id: z.string().optional(),
  price_type: TypesPriceType$inboundSchema.optional(),
  price_unit: z.string().optional(),
  price_unit_id: z.string().optional(),
  quantity: z.string().optional(),
  start_date: z.string().optional(),
  status: TypesStatus$inboundSchema.optional(),
  subscription_id: z.string().optional(),
  subscription_phase_id: z.string().optional(),
  tenant_id: z.string().optional(),
  trial_period: z.number().int().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "billing_period": "billingPeriod",
    "billing_period_count": "billingPeriodCount",
    "commitment_amount": "commitmentAmount",
    "commitment_duration": "commitmentDuration",
    "commitment_overage_factor": "commitmentOverageFactor",
    "commitment_quantity": "commitmentQuantity",
    "commitment_true_up_enabled": "commitmentTrueUpEnabled",
    "commitment_type": "commitmentType",
    "commitment_windowed": "commitmentWindowed",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "customer_id": "customerId",
    "display_name": "displayName",
    "end_date": "endDate",
    "entity_id": "entityId",
    "entity_type": "entityType",
    "environment_id": "environmentId",
    "invoice_cadence": "invoiceCadence",
    "meter_display_name": "meterDisplayName",
    "meter_id": "meterId",
    "plan_display_name": "planDisplayName",
    "price_id": "priceId",
    "price_type": "priceType",
    "price_unit": "priceUnit",
    "price_unit_id": "priceUnitId",
    "start_date": "startDate",
    "subscription_id": "subscriptionId",
    "subscription_phase_id": "subscriptionPhaseId",
    "tenant_id": "tenantId",
    "trial_period": "trialPeriod",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function subscriptionSubscriptionLineItemFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionSubscriptionLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionSubscriptionLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionSubscriptionLineItem' from JSON`,
  );
}
