/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TaxRateType = {
  Percentage: "percentage",
  Fixed: "fixed",
} as const;
export type TaxRateType = ClosedEnum<typeof TaxRateType>;

/** @internal */
export const TaxRateType$inboundSchema: z.ZodNativeEnum<typeof TaxRateType> = z
  .nativeEnum(TaxRateType);
/** @internal */
export const TaxRateType$outboundSchema: z.ZodNativeEnum<typeof TaxRateType> =
  TaxRateType$inboundSchema;
