/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TypesAlertCondition,
  TypesAlertCondition$inboundSchema,
  TypesAlertCondition$outboundSchema,
} from "./typesalertcondition.js";

export type TypesAlertThreshold = {
  condition?: TypesAlertCondition | undefined;
  threshold?: number | undefined;
};

/** @internal */
export const TypesAlertThreshold$inboundSchema: z.ZodType<
  TypesAlertThreshold,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: TypesAlertCondition$inboundSchema.optional(),
  threshold: z.number().optional(),
});
/** @internal */
export type TypesAlertThreshold$Outbound = {
  condition?: string | undefined;
  threshold?: number | undefined;
};

/** @internal */
export const TypesAlertThreshold$outboundSchema: z.ZodType<
  TypesAlertThreshold$Outbound,
  z.ZodTypeDef,
  TypesAlertThreshold
> = z.object({
  condition: TypesAlertCondition$outboundSchema.optional(),
  threshold: z.number().optional(),
});

export function typesAlertThresholdToJSON(
  typesAlertThreshold: TypesAlertThreshold,
): string {
  return JSON.stringify(
    TypesAlertThreshold$outboundSchema.parse(typesAlertThreshold),
  );
}
export function typesAlertThresholdFromJSON(
  jsonString: string,
): SafeParseResult<TypesAlertThreshold, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypesAlertThreshold$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesAlertThreshold' from JSON`,
  );
}
