/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesScheduleStatus = {
  Pending: "pending",
  Executing: "executing",
  Executed: "executed",
  Cancelled: "cancelled",
  Failed: "failed",
} as const;
export type TypesScheduleStatus = ClosedEnum<typeof TypesScheduleStatus>;

/** @internal */
export const TypesScheduleStatus$inboundSchema: z.ZodNativeEnum<
  typeof TypesScheduleStatus
> = z.nativeEnum(TypesScheduleStatus);
