/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesFeatureType = {
  Metered: "metered",
  Boolean: "boolean",
  Static: "static",
} as const;
export type TypesFeatureType = ClosedEnum<typeof TypesFeatureType>;

/** @internal */
export const TypesFeatureType$inboundSchema: z.ZodNativeEnum<
  typeof TypesFeatureType
> = z.nativeEnum(TypesFeatureType);
/** @internal */
export const TypesFeatureType$outboundSchema: z.ZodNativeEnum<
  typeof TypesFeatureType
> = TypesFeatureType$inboundSchema;
