/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type TypesTimeRangeFilter = {
  endTime?: string | undefined;
  startTime?: string | undefined;
};

/** @internal */
export type TypesTimeRangeFilter$Outbound = {
  end_time?: string | undefined;
  start_time?: string | undefined;
};

/** @internal */
export const TypesTimeRangeFilter$outboundSchema: z.ZodType<
  TypesTimeRangeFilter$Outbound,
  z.ZodTypeDef,
  TypesTimeRangeFilter
> = z.object({
  endTime: z.string().optional(),
  startTime: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    startTime: "start_time",
  });
});

export function typesTimeRangeFilterToJSON(
  typesTimeRangeFilter: TypesTimeRangeFilter,
): string {
  return JSON.stringify(
    TypesTimeRangeFilter$outboundSchema.parse(typesTimeRangeFilter),
  );
}
