/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesBillingPeriod = {
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Weekly: "WEEKLY",
  Daily: "DAILY",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
} as const;
export type TypesBillingPeriod = ClosedEnum<typeof TypesBillingPeriod>;

/** @internal */
export const TypesBillingPeriod$inboundSchema: z.ZodNativeEnum<
  typeof TypesBillingPeriod
> = z.nativeEnum(TypesBillingPeriod);
/** @internal */
export const TypesBillingPeriod$outboundSchema: z.ZodNativeEnum<
  typeof TypesBillingPeriod
> = TypesBillingPeriod$inboundSchema;
