/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./typesstatus.js";

export const TypesQueryFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesQueryFilterOrder = ClosedEnum<typeof TypesQueryFilterOrder>;

export type TypesQueryFilter = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesQueryFilterOrder | undefined;
  sort?: string | undefined;
  status?: TypesStatus | undefined;
};

/** @internal */
export const TypesQueryFilterOrder$outboundSchema: z.ZodNativeEnum<
  typeof TypesQueryFilterOrder
> = z.nativeEnum(TypesQueryFilterOrder);

/** @internal */
export type TypesQueryFilter$Outbound = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const TypesQueryFilter$outboundSchema: z.ZodType<
  TypesQueryFilter$Outbound,
  z.ZodTypeDef,
  TypesQueryFilter
> = z.object({
  expand: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: TypesQueryFilterOrder$outboundSchema.optional(),
  sort: z.string().optional(),
  status: TypesStatus$outboundSchema.optional(),
});

export function typesQueryFilterToJSON(
  typesQueryFilter: TypesQueryFilter,
): string {
  return JSON.stringify(
    TypesQueryFilter$outboundSchema.parse(typesQueryFilter),
  );
}
