/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesCreditGrantCadence = {
  Onetime: "ONETIME",
  Recurring: "RECURRING",
} as const;
export type TypesCreditGrantCadence = ClosedEnum<
  typeof TypesCreditGrantCadence
>;

/** @internal */
export const TypesCreditGrantCadence$inboundSchema: z.ZodNativeEnum<
  typeof TypesCreditGrantCadence
> = z.nativeEnum(TypesCreditGrantCadence);
/** @internal */
export const TypesCreditGrantCadence$outboundSchema: z.ZodNativeEnum<
  typeof TypesCreditGrantCadence
> = TypesCreditGrantCadence$inboundSchema;
