/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TypesCreditBreakdown = {
  free?: string | undefined;
  purchased?: string | undefined;
};

/** @internal */
export const TypesCreditBreakdown$inboundSchema: z.ZodType<
  TypesCreditBreakdown,
  z.ZodTypeDef,
  unknown
> = z.object({
  free: z.string().optional(),
  purchased: z.string().optional(),
});

export function typesCreditBreakdownFromJSON(
  jsonString: string,
): SafeParseResult<TypesCreditBreakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypesCreditBreakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesCreditBreakdown' from JSON`,
  );
}
