/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesS3CompressionType = {
  None: "none",
  Gzip: "gzip",
} as const;
export type TypesS3CompressionType = ClosedEnum<typeof TypesS3CompressionType>;

/** @internal */
export const TypesS3CompressionType$inboundSchema: z.ZodNativeEnum<
  typeof TypesS3CompressionType
> = z.nativeEnum(TypesS3CompressionType);
/** @internal */
export const TypesS3CompressionType$outboundSchema: z.ZodNativeEnum<
  typeof TypesS3CompressionType
> = TypesS3CompressionType$inboundSchema;
