/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TypesPaginationResponse = {
  limit?: number | undefined;
  offset?: number | undefined;
  total?: number | undefined;
};

/** @internal */
export const TypesPaginationResponse$inboundSchema: z.ZodType<
  TypesPaginationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  total: z.number().int().optional(),
});

export function typesPaginationResponseFromJSON(
  jsonString: string,
): SafeParseResult<TypesPaginationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypesPaginationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesPaginationResponse' from JSON`,
  );
}
