/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesPauseMode = {
  Immediate: "immediate",
  Scheduled: "scheduled",
  PeriodEnd: "period_end",
} as const;
export type TypesPauseMode = ClosedEnum<typeof TypesPauseMode>;

/** @internal */
export const TypesPauseMode$inboundSchema: z.ZodNativeEnum<
  typeof TypesPauseMode
> = z.nativeEnum(TypesPauseMode);
/** @internal */
export const TypesPauseMode$outboundSchema: z.ZodNativeEnum<
  typeof TypesPauseMode
> = TypesPauseMode$inboundSchema;
