/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$Outbound,
  TypesSortCondition$outboundSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./typesstatus.js";

export const TypesFeatureFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesFeatureFilterOrder = ClosedEnum<
  typeof TypesFeatureFilterOrder
>;

export type TypesFeatureFilter = {
  endTime?: string | undefined;
  expand?: string | undefined;
  /**
   * Feature specific filters
   */
  featureIds?: Array<string> | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  lookupKey?: string | undefined;
  lookupKeys?: Array<string> | undefined;
  meterIds?: Array<string> | undefined;
  nameContains?: string | undefined;
  offset?: number | undefined;
  order?: TypesFeatureFilterOrder | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  startTime?: string | undefined;
  status?: TypesStatus | undefined;
};

/** @internal */
export const TypesFeatureFilterOrder$outboundSchema: z.ZodNativeEnum<
  typeof TypesFeatureFilterOrder
> = z.nativeEnum(TypesFeatureFilterOrder);

/** @internal */
export type TypesFeatureFilter$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  lookup_key?: string | undefined;
  lookup_keys?: Array<string> | undefined;
  meter_ids?: Array<string> | undefined;
  name_contains?: string | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: Array<TypesSortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const TypesFeatureFilter$outboundSchema: z.ZodType<
  TypesFeatureFilter$Outbound,
  z.ZodTypeDef,
  TypesFeatureFilter
> = z.object({
  endTime: z.string().optional(),
  expand: z.string().optional(),
  featureIds: z.array(z.string()).optional(),
  filters: z.array(TypesFilterCondition$outboundSchema).optional(),
  limit: z.number().int().optional(),
  lookupKey: z.string().optional(),
  lookupKeys: z.array(z.string()).optional(),
  meterIds: z.array(z.string()).optional(),
  nameContains: z.string().optional(),
  offset: z.number().int().optional(),
  order: TypesFeatureFilterOrder$outboundSchema.optional(),
  sort: z.array(TypesSortCondition$outboundSchema).optional(),
  startTime: z.string().optional(),
  status: TypesStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    featureIds: "feature_ids",
    lookupKey: "lookup_key",
    lookupKeys: "lookup_keys",
    meterIds: "meter_ids",
    nameContains: "name_contains",
    startTime: "start_time",
  });
});

export function typesFeatureFilterToJSON(
  typesFeatureFilter: TypesFeatureFilter,
): string {
  return JSON.stringify(
    TypesFeatureFilter$outboundSchema.parse(typesFeatureFilter),
  );
}
