/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  TypesFilterCondition,
  TypesFilterCondition$Outbound,
  TypesFilterCondition$outboundSchema,
} from "./typesfiltercondition.js";
import {
  TypesSortCondition,
  TypesSortCondition$Outbound,
  TypesSortCondition$outboundSchema,
} from "./typessortcondition.js";
import { TypesStatus, TypesStatus$outboundSchema } from "./typesstatus.js";

export const TypesPriceUnitFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type TypesPriceUnitFilterOrder = ClosedEnum<
  typeof TypesPriceUnitFilterOrder
>;

export type TypesPriceUnitFilter = {
  endTime?: string | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<TypesFilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: TypesPriceUnitFilterOrder | undefined;
  priceUnitIds?: Array<string> | undefined;
  sort?: Array<TypesSortCondition> | undefined;
  startTime?: string | undefined;
  status?: TypesStatus | undefined;
};

/** @internal */
export const TypesPriceUnitFilterOrder$outboundSchema: z.ZodNativeEnum<
  typeof TypesPriceUnitFilterOrder
> = z.nativeEnum(TypesPriceUnitFilterOrder);

/** @internal */
export type TypesPriceUnitFilter$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<TypesFilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  price_unit_ids?: Array<string> | undefined;
  sort?: Array<TypesSortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const TypesPriceUnitFilter$outboundSchema: z.ZodType<
  TypesPriceUnitFilter$Outbound,
  z.ZodTypeDef,
  TypesPriceUnitFilter
> = z.object({
  endTime: z.string().optional(),
  expand: z.string().optional(),
  filters: z.array(TypesFilterCondition$outboundSchema).optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: TypesPriceUnitFilterOrder$outboundSchema.optional(),
  priceUnitIds: z.array(z.string()).optional(),
  sort: z.array(TypesSortCondition$outboundSchema).optional(),
  startTime: z.string().optional(),
  status: TypesStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    priceUnitIds: "price_unit_ids",
    startTime: "start_time",
  });
});

export function typesPriceUnitFilterToJSON(
  typesPriceUnitFilter: TypesPriceUnitFilter,
): string {
  return JSON.stringify(
    TypesPriceUnitFilter$outboundSchema.parse(typesPriceUnitFilter),
  );
}
