/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesScheduledTaskInterval = {
  FifteenMIN: "15MIN",
  Custom: "custom",
  Hourly: "hourly",
  Daily: "daily",
} as const;
export type TypesScheduledTaskInterval = ClosedEnum<
  typeof TypesScheduledTaskInterval
>;

/** @internal */
export const TypesScheduledTaskInterval$inboundSchema: z.ZodNativeEnum<
  typeof TypesScheduledTaskInterval
> = z.nativeEnum(TypesScheduledTaskInterval);
/** @internal */
export const TypesScheduledTaskInterval$outboundSchema: z.ZodNativeEnum<
  typeof TypesScheduledTaskInterval
> = TypesScheduledTaskInterval$inboundSchema;
