/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesAddonType = {
  Onetime: "onetime",
  MultipleInstance: "multiple_instance",
} as const;
export type TypesAddonType = ClosedEnum<typeof TypesAddonType>;

/** @internal */
export const TypesAddonType$inboundSchema: z.ZodNativeEnum<
  typeof TypesAddonType
> = z.nativeEnum(TypesAddonType);
/** @internal */
export const TypesAddonType$outboundSchema: z.ZodNativeEnum<
  typeof TypesAddonType
> = TypesAddonType$inboundSchema;
