"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DtoAlertLogResponse$inboundSchema = void 0;
exports.dtoAlertLogResponseFromJSON = dtoAlertLogResponseFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const dtocustomerresponse_js_1 = require("./dtocustomerresponse.js");
const dtofeatureresponse_js_1 = require("./dtofeatureresponse.js");
const dtowalletresponse_js_1 = require("./dtowalletresponse.js");
const typesalertentitytype_js_1 = require("./typesalertentitytype.js");
const typesalertinfo_js_1 = require("./typesalertinfo.js");
const typesalertstate_js_1 = require("./typesalertstate.js");
const typesalerttype_js_1 = require("./typesalerttype.js");
/** @internal */
exports.DtoAlertLogResponse$inboundSchema = z.object({
    alert_info: typesalertinfo_js_1.TypesAlertInfo$inboundSchema.optional(),
    alert_status: typesalertstate_js_1.TypesAlertState$inboundSchema.optional(),
    alert_type: typesalerttype_js_1.TypesAlertType$inboundSchema.optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    customer: dtocustomerresponse_js_1.DtoCustomerResponse$inboundSchema.optional(),
    customer_id: z.string().optional(),
    entity_id: z.string().optional(),
    entity_type: typesalertentitytype_js_1.TypesAlertEntityType$inboundSchema.optional(),
    environment_id: z.string().optional(),
    feature: dtofeatureresponse_js_1.DtoFeatureResponse$inboundSchema.optional(),
    id: z.string().optional(),
    parent_entity_id: z.string().optional(),
    parent_entity_type: z.string().optional(),
    status: z.string().optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
    wallet: dtowalletresponse_js_1.DtoWalletResponse$inboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "alert_info": "alertInfo",
        "alert_status": "alertStatus",
        "alert_type": "alertType",
        "created_at": "createdAt",
        "created_by": "createdBy",
        "customer_id": "customerId",
        "entity_id": "entityId",
        "entity_type": "entityType",
        "environment_id": "environmentId",
        "parent_entity_id": "parentEntityId",
        "parent_entity_type": "parentEntityType",
        "tenant_id": "tenantId",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
    });
});
function dtoAlertLogResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DtoAlertLogResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DtoAlertLogResponse' from JSON`);
}
//# sourceMappingURL=dtoalertlogresponse.js.map