"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DtoCustomerResponse$inboundSchema = void 0;
exports.dtoCustomerResponseFromJSON = dtoCustomerResponseFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const typesstatus_js_1 = require("./typesstatus.js");
/** @internal */
exports.DtoCustomerResponse$inboundSchema = z.object({
    address_city: z.string().optional(),
    address_country: z.string().optional(),
    address_line1: z.string().optional(),
    address_line2: z.string().optional(),
    address_postal_code: z.string().optional(),
    address_state: z.string().optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    email: z.string().optional(),
    environment_id: z.string().optional(),
    external_id: z.string().optional(),
    id: z.string().optional(),
    metadata: z.record(z.string()).optional(),
    name: z.string().optional(),
    parent_customer: z.lazy(() => exports.DtoCustomerResponse$inboundSchema).optional(),
    parent_customer_id: z.string().optional(),
    status: typesstatus_js_1.TypesStatus$inboundSchema.optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "address_city": "addressCity",
        "address_country": "addressCountry",
        "address_line1": "addressLine1",
        "address_line2": "addressLine2",
        "address_postal_code": "addressPostalCode",
        "address_state": "addressState",
        "created_at": "createdAt",
        "created_by": "createdBy",
        "environment_id": "environmentId",
        "external_id": "externalId",
        "parent_customer": "parentCustomer",
        "parent_customer_id": "parentCustomerId",
        "tenant_id": "tenantId",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
    });
});
function dtoCustomerResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DtoCustomerResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DtoCustomerResponse' from JSON`);
}
//# sourceMappingURL=dtocustomerresponse.js.map