"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DtoCreditNoteResponse$inboundSchema = void 0;
exports.dtoCreditNoteResponseFromJSON = dtoCreditNoteResponseFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const creditnotecreditnotelineitem_js_1 = require("./creditnotecreditnotelineitem.js");
const dtoinvoiceresponse_js_1 = require("./dtoinvoiceresponse.js");
const dtosubscriptionresponse_js_1 = require("./dtosubscriptionresponse.js");
const githubcomflexpriceflexpriceinternaldomaincustomercustomer_js_1 = require("./githubcomflexpriceflexpriceinternaldomaincustomercustomer.js");
const typescreditnotereason_js_1 = require("./typescreditnotereason.js");
const typescreditnotestatus_js_1 = require("./typescreditnotestatus.js");
const typescreditnotetype_js_1 = require("./typescreditnotetype.js");
const typespaymentstatus_js_1 = require("./typespaymentstatus.js");
const typesstatus_js_1 = require("./typesstatus.js");
/** @internal */
exports.DtoCreditNoteResponse$inboundSchema = z.object({
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    credit_note_number: z.string().optional(),
    credit_note_status: typescreditnotestatus_js_1.TypesCreditNoteStatus$inboundSchema.optional(),
    credit_note_type: typescreditnotetype_js_1.TypesCreditNoteType$inboundSchema.optional(),
    currency: z.string().optional(),
    customer: githubcomflexpriceflexpriceinternaldomaincustomercustomer_js_1.GithubComFlexpriceFlexpriceInternalDomainCustomerCustomer$inboundSchema
        .optional(),
    customer_id: z.string().optional(),
    environment_id: z.string().optional(),
    finalized_at: z.string().optional(),
    id: z.string().optional(),
    idempotency_key: z.string().optional(),
    invoice: dtoinvoiceresponse_js_1.DtoInvoiceResponse$inboundSchema.optional(),
    invoice_id: z.string().optional(),
    line_items: z.array(creditnotecreditnotelineitem_js_1.CreditnoteCreditNoteLineItem$inboundSchema).optional(),
    memo: z.string().optional(),
    metadata: z.record(z.string()).optional(),
    reason: typescreditnotereason_js_1.TypesCreditNoteReason$inboundSchema.optional(),
    refund_status: typespaymentstatus_js_1.TypesPaymentStatus$inboundSchema.optional(),
    status: typesstatus_js_1.TypesStatus$inboundSchema.optional(),
    subscription: dtosubscriptionresponse_js_1.DtoSubscriptionResponse$inboundSchema.optional(),
    subscription_id: z.string().optional(),
    tenant_id: z.string().optional(),
    total_amount: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
    voided_at: z.string().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "created_at": "createdAt",
        "created_by": "createdBy",
        "credit_note_number": "creditNoteNumber",
        "credit_note_status": "creditNoteStatus",
        "credit_note_type": "creditNoteType",
        "customer_id": "customerId",
        "environment_id": "environmentId",
        "finalized_at": "finalizedAt",
        "idempotency_key": "idempotencyKey",
        "invoice_id": "invoiceId",
        "line_items": "lineItems",
        "refund_status": "refundStatus",
        "subscription_id": "subscriptionId",
        "tenant_id": "tenantId",
        "total_amount": "totalAmount",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
        "voided_at": "voidedAt",
    });
});
function dtoCreditNoteResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DtoCreditNoteResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DtoCreditNoteResponse' from JSON`);
}
//# sourceMappingURL=dtocreditnoteresponse.js.map