"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DtoCreateEntitlementRequest$outboundSchema = void 0;
exports.dtoCreateEntitlementRequestToJSON = dtoCreateEntitlementRequestToJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const typesentitlemententitytype_js_1 = require("./typesentitlemententitytype.js");
const typesentitlementusageresetperiod_js_1 = require("./typesentitlementusageresetperiod.js");
const typesfeaturetype_js_1 = require("./typesfeaturetype.js");
/** @internal */
exports.DtoCreateEntitlementRequest$outboundSchema = z.object({
    endDate: z.string().optional(),
    entityId: z.string().optional(),
    entityType: typesentitlemententitytype_js_1.TypesEntitlementEntityType$outboundSchema.optional(),
    featureId: z.string(),
    featureType: typesfeaturetype_js_1.TypesFeatureType$outboundSchema,
    isEnabled: z.boolean().optional(),
    isSoftLimit: z.boolean().optional(),
    parentEntitlementId: z.string().optional(),
    planId: z.string().optional(),
    startDate: z.string().optional(),
    staticValue: z.string().optional(),
    usageLimit: z.number().int().optional(),
    usageResetPeriod: typesentitlementusageresetperiod_js_1.TypesEntitlementUsageResetPeriod$outboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        endDate: "end_date",
        entityId: "entity_id",
        entityType: "entity_type",
        featureId: "feature_id",
        featureType: "feature_type",
        isEnabled: "is_enabled",
        isSoftLimit: "is_soft_limit",
        parentEntitlementId: "parent_entitlement_id",
        planId: "plan_id",
        startDate: "start_date",
        staticValue: "static_value",
        usageLimit: "usage_limit",
        usageResetPeriod: "usage_reset_period",
    });
});
function dtoCreateEntitlementRequestToJSON(dtoCreateEntitlementRequest) {
    return JSON.stringify(exports.DtoCreateEntitlementRequest$outboundSchema.parse(dtoCreateEntitlementRequest));
}
//# sourceMappingURL=dtocreateentitlementrequest.js.map