"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DtoPaymentResponse$inboundSchema = void 0;
exports.dtoPaymentResponseFromJSON = dtoPaymentResponseFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const dtopaymentattemptresponse_js_1 = require("./dtopaymentattemptresponse.js");
const typespaymentdestinationtype_js_1 = require("./typespaymentdestinationtype.js");
const typespaymentmethodtype_js_1 = require("./typespaymentmethodtype.js");
const typespaymentstatus_js_1 = require("./typespaymentstatus.js");
/** @internal */
exports.DtoPaymentResponse$inboundSchema = z.object({
    amount: z.string().optional(),
    attempts: z.array(dtopaymentattemptresponse_js_1.DtoPaymentAttemptResponse$inboundSchema).optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    currency: z.string().optional(),
    destination_id: z.string().optional(),
    destination_type: typespaymentdestinationtype_js_1.TypesPaymentDestinationType$inboundSchema.optional(),
    error_message: z.string().optional(),
    failed_at: z.string().optional(),
    gateway_metadata: z.record(z.string()).optional(),
    gateway_payment_id: z.string().optional(),
    gateway_tracking_id: z.string().optional(),
    id: z.string().optional(),
    idempotency_key: z.string().optional(),
    invoice_number: z.string().optional(),
    metadata: z.record(z.string()).optional(),
    payment_gateway: z.string().optional(),
    payment_method_id: z.string().optional(),
    payment_method_type: typespaymentmethodtype_js_1.TypesPaymentMethodType$inboundSchema.optional(),
    payment_status: typespaymentstatus_js_1.TypesPaymentStatus$inboundSchema.optional(),
    payment_url: z.string().optional(),
    refunded_at: z.string().optional(),
    save_card_and_make_default: z.boolean().optional(),
    succeeded_at: z.string().optional(),
    tenant_id: z.string().optional(),
    track_attempts: z.boolean().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "created_at": "createdAt",
        "created_by": "createdBy",
        "destination_id": "destinationId",
        "destination_type": "destinationType",
        "error_message": "errorMessage",
        "failed_at": "failedAt",
        "gateway_metadata": "gatewayMetadata",
        "gateway_payment_id": "gatewayPaymentId",
        "gateway_tracking_id": "gatewayTrackingId",
        "idempotency_key": "idempotencyKey",
        "invoice_number": "invoiceNumber",
        "payment_gateway": "paymentGateway",
        "payment_method_id": "paymentMethodId",
        "payment_method_type": "paymentMethodType",
        "payment_status": "paymentStatus",
        "payment_url": "paymentUrl",
        "refunded_at": "refundedAt",
        "save_card_and_make_default": "saveCardAndMakeDefault",
        "succeeded_at": "succeededAt",
        "tenant_id": "tenantId",
        "track_attempts": "trackAttempts",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
    });
});
function dtoPaymentResponseFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DtoPaymentResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DtoPaymentResponse' from JSON`);
}
//# sourceMappingURL=dtopaymentresponse.js.map