"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DtoUsageAnalyticItem$inboundSchema = void 0;
exports.dtoUsageAnalyticItemFromJSON = dtoUsageAnalyticItemFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const dtopriceresponse_js_1 = require("./dtopriceresponse.js");
const dtousageanalyticpoint_js_1 = require("./dtousageanalyticpoint.js");
const githubcomflexpriceflexpriceinternaldomainaddonaddon_js_1 = require("./githubcomflexpriceflexpriceinternaldomainaddonaddon.js");
const githubcomflexpriceflexpriceinternaldomainfeaturefeature_js_1 = require("./githubcomflexpriceflexpriceinternaldomainfeaturefeature.js");
const githubcomflexpriceflexpriceinternaldomainplanplan_js_1 = require("./githubcomflexpriceflexpriceinternaldomainplanplan.js");
const metermeter_js_1 = require("./metermeter.js");
const subscriptionsubscriptionlineitem_js_1 = require("./subscriptionsubscriptionlineitem.js");
const typesaggregationtype_js_1 = require("./typesaggregationtype.js");
const typescommitmentinfo_js_1 = require("./typescommitmentinfo.js");
const typeswindowsize_js_1 = require("./typeswindowsize.js");
/** @internal */
exports.DtoUsageAnalyticItem$inboundSchema = z.object({
    add_on_id: z.string().optional(),
    addon: githubcomflexpriceflexpriceinternaldomainaddonaddon_js_1.GithubComFlexpriceFlexpriceInternalDomainAddonAddon$inboundSchema
        .optional(),
    aggregation_type: typesaggregationtype_js_1.TypesAggregationType$inboundSchema.optional(),
    commitment_info: typescommitmentinfo_js_1.TypesCommitmentInfo$inboundSchema.optional(),
    currency: z.string().optional(),
    event_count: z.number().int().optional(),
    event_name: z.string().optional(),
    feature: githubcomflexpriceflexpriceinternaldomainfeaturefeature_js_1.GithubComFlexpriceFlexpriceInternalDomainFeatureFeature$inboundSchema
        .optional(),
    feature_id: z.string().optional(),
    meter: metermeter_js_1.MeterMeter$inboundSchema.optional(),
    meter_id: z.string().optional(),
    name: z.string().optional(),
    plan: githubcomflexpriceflexpriceinternaldomainplanplan_js_1.GithubComFlexpriceFlexpriceInternalDomainPlanPlan$inboundSchema
        .optional(),
    plan_id: z.string().optional(),
    points: z.array(dtousageanalyticpoint_js_1.DtoUsageAnalyticPoint$inboundSchema).optional(),
    price: dtopriceresponse_js_1.DtoPriceResponse$inboundSchema.optional(),
    price_id: z.string().optional(),
    properties: z.record(z.string()).optional(),
    source: z.string().optional(),
    sources: z.array(z.string()).optional(),
    sub_line_item_id: z.string().optional(),
    subscription_id: z.string().optional(),
    subscription_line_item: subscriptionsubscriptionlineitem_js_1.SubscriptionSubscriptionLineItem$inboundSchema
        .optional(),
    total_cost: z.string().optional(),
    total_usage: z.string().optional(),
    unit: z.string().optional(),
    unit_plural: z.string().optional(),
    window_size: typeswindowsize_js_1.TypesWindowSize$inboundSchema.optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "add_on_id": "addOnId",
        "aggregation_type": "aggregationType",
        "commitment_info": "commitmentInfo",
        "event_count": "eventCount",
        "event_name": "eventName",
        "feature_id": "featureId",
        "meter_id": "meterId",
        "plan_id": "planId",
        "price_id": "priceId",
        "sub_line_item_id": "subLineItemId",
        "subscription_id": "subscriptionId",
        "subscription_line_item": "subscriptionLineItem",
        "total_cost": "totalCost",
        "total_usage": "totalUsage",
        "unit_plural": "unitPlural",
        "window_size": "windowSize",
    });
});
function dtoUsageAnalyticItemFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.DtoUsageAnalyticItem$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'DtoUsageAnalyticItem' from JSON`);
}
//# sourceMappingURL=dtousageanalyticitem.js.map