"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeterMeter$inboundSchema = void 0;
exports.meterMeterFromJSON = meterMeterFromJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const schemas_js_1 = require("../../lib/schemas.js");
const meter_aggregation_js_1 = require("./meter-aggregation.js");
const meter_filter_js_1 = require("./meter-filter.js");
const types_reset_usage_js_1 = require("./types-reset-usage.js");
const types_status_js_1 = require("./types-status.js");
/** @internal */
exports.MeterMeter$inboundSchema = z.object({
    aggregation: meter_aggregation_js_1.MeterAggregation$inboundSchema.optional(),
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    environment_id: z.string().optional(),
    event_name: z.string().optional(),
    filters: z.array(meter_filter_js_1.MeterFilter$inboundSchema).optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    reset_usage: types_reset_usage_js_1.TypesResetUsage$inboundSchema.optional(),
    status: types_status_js_1.TypesStatus$inboundSchema.optional(),
    tenant_id: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        "created_at": "createdAt",
        "created_by": "createdBy",
        "environment_id": "environmentId",
        "event_name": "eventName",
        "reset_usage": "resetUsage",
        "tenant_id": "tenantId",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
    });
});
function meterMeterFromJSON(jsonString) {
    return (0, schemas_js_1.safeParse)(jsonString, (x) => exports.MeterMeter$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'MeterMeter' from JSON`);
}
//# sourceMappingURL=meter-meter.js.map