"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TypesConnectionMetadata$outboundSchema = void 0;
exports.typesConnectionMetadataToJSON = typesConnectionMetadataToJSON;
const z = __importStar(require("zod/v3"));
const typeschargebeeconnectionmetadata_js_1 = require("./typeschargebeeconnectionmetadata.js");
const typesconnectionsettings_js_1 = require("./typesconnectionsettings.js");
const typesgenericconnectionmetadata_js_1 = require("./typesgenericconnectionmetadata.js");
const typeshubspotconnectionmetadata_js_1 = require("./typeshubspotconnectionmetadata.js");
const typesnomodconnectionmetadata_js_1 = require("./typesnomodconnectionmetadata.js");
const typesquickbooksconnectionmetadata_js_1 = require("./typesquickbooksconnectionmetadata.js");
const typesrazorpayconnectionmetadata_js_1 = require("./typesrazorpayconnectionmetadata.js");
const typess3connectionmetadata_js_1 = require("./typess3connectionmetadata.js");
const typesstripeconnectionmetadata_js_1 = require("./typesstripeconnectionmetadata.js");
/** @internal */
exports.TypesConnectionMetadata$outboundSchema = z.object({
    chargebee: typeschargebeeconnectionmetadata_js_1.TypesChargebeeConnectionMetadata$outboundSchema.optional(),
    generic: typesgenericconnectionmetadata_js_1.TypesGenericConnectionMetadata$outboundSchema.optional(),
    hubspot: typeshubspotconnectionmetadata_js_1.TypesHubSpotConnectionMetadata$outboundSchema.optional(),
    nomod: typesnomodconnectionmetadata_js_1.TypesNomodConnectionMetadata$outboundSchema.optional(),
    quickbooks: typesquickbooksconnectionmetadata_js_1.TypesQuickBooksConnectionMetadata$outboundSchema.optional(),
    razorpay: typesrazorpayconnectionmetadata_js_1.TypesRazorpayConnectionMetadata$outboundSchema.optional(),
    s3: typess3connectionmetadata_js_1.TypesS3ConnectionMetadata$outboundSchema.optional(),
    settings: typesconnectionsettings_js_1.TypesConnectionSettings$outboundSchema.optional(),
    stripe: typesstripeconnectionmetadata_js_1.TypesStripeConnectionMetadata$outboundSchema.optional(),
});
function typesConnectionMetadataToJSON(typesConnectionMetadata) {
    return JSON.stringify(exports.TypesConnectionMetadata$outboundSchema.parse(typesConnectionMetadata));
}
//# sourceMappingURL=typesconnectionmetadata.js.map