"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TypesUserFilter$outboundSchema = exports.TypesUserFilterOrder$outboundSchema = exports.TypesUserFilterOrder = void 0;
exports.typesUserFilterToJSON = typesUserFilterToJSON;
const z = __importStar(require("zod/v3"));
const primitives_js_1 = require("../../lib/primitives.js");
const typesfiltercondition_js_1 = require("./typesfiltercondition.js");
const typessortcondition_js_1 = require("./typessortcondition.js");
const typesstatus_js_1 = require("./typesstatus.js");
const typesusertype_js_1 = require("./typesusertype.js");
exports.TypesUserFilterOrder = {
    Asc: "asc",
    Desc: "desc",
};
/** @internal */
exports.TypesUserFilterOrder$outboundSchema = z.nativeEnum(exports.TypesUserFilterOrder);
/** @internal */
exports.TypesUserFilter$outboundSchema = z.object({
    endTime: z.string().optional(),
    expand: z.string().optional(),
    filters: z.array(typesfiltercondition_js_1.TypesFilterCondition$outboundSchema).optional(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional(),
    order: exports.TypesUserFilterOrder$outboundSchema.optional(),
    roles: z.array(z.string()).optional(),
    sort: z.array(typessortcondition_js_1.TypesSortCondition$outboundSchema).optional(),
    startTime: z.string().optional(),
    status: typesstatus_js_1.TypesStatus$outboundSchema.optional(),
    type: typesusertype_js_1.TypesUserType$outboundSchema.optional(),
    userIds: z.array(z.string()).optional(),
}).transform((v) => {
    return (0, primitives_js_1.remap)(v, {
        endTime: "end_time",
        startTime: "start_time",
        userIds: "user_ids",
    });
});
function typesUserFilterToJSON(typesUserFilter) {
    return JSON.stringify(exports.TypesUserFilter$outboundSchema.parse(typesUserFilter));
}
//# sourceMappingURL=typesuserfilter.js.map