/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ActivateSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Activate Draft Subscription Request
   */
  dtoActivateDraftSubscriptionRequest:
    shared.DtoActivateDraftSubscriptionRequest;
};

export type ActivateSubscriptionResponse =
  | shared.DtoSubscriptionResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type ActivateSubscriptionRequest$Outbound = {
  id: string;
  "dto.ActivateDraftSubscriptionRequest":
    shared.DtoActivateDraftSubscriptionRequest$Outbound;
};

/** @internal */
export const ActivateSubscriptionRequest$outboundSchema: z.ZodType<
  ActivateSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  ActivateSubscriptionRequest
> = z.object({
  id: z.string(),
  dtoActivateDraftSubscriptionRequest:
    shared.DtoActivateDraftSubscriptionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoActivateDraftSubscriptionRequest: "dto.ActivateDraftSubscriptionRequest",
  });
});

export function activateSubscriptionRequestToJSON(
  activateSubscriptionRequest: ActivateSubscriptionRequest,
): string {
  return JSON.stringify(
    ActivateSubscriptionRequest$outboundSchema.parse(
      activateSubscriptionRequest,
    ),
  );
}

/** @internal */
export const ActivateSubscriptionResponse$inboundSchema: z.ZodType<
  ActivateSubscriptionResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoSubscriptionResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function activateSubscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActivateSubscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivateSubscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivateSubscriptionResponse' from JSON`,
  );
}
