/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreateApiKeyResponse =
  | shared.DtoCreateAPIKeyResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const CreateApiKeyResponse$inboundSchema: z.ZodType<
  CreateApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoCreateAPIKeyResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function createApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyResponse' from JSON`,
  );
}
