/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreateSubscriptionLineItemRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Create Line Item Request
   */
  dtoCreateSubscriptionLineItemRequest:
    shared.DtoCreateSubscriptionLineItemRequest;
};

export type CreateSubscriptionLineItemResponse =
  | shared.DtoSubscriptionLineItemResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type CreateSubscriptionLineItemRequest$Outbound = {
  id: string;
  "dto.CreateSubscriptionLineItemRequest":
    shared.DtoCreateSubscriptionLineItemRequest$Outbound;
};

/** @internal */
export const CreateSubscriptionLineItemRequest$outboundSchema: z.ZodType<
  CreateSubscriptionLineItemRequest$Outbound,
  z.ZodTypeDef,
  CreateSubscriptionLineItemRequest
> = z.object({
  id: z.string(),
  dtoCreateSubscriptionLineItemRequest:
    shared.DtoCreateSubscriptionLineItemRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoCreateSubscriptionLineItemRequest:
      "dto.CreateSubscriptionLineItemRequest",
  });
});

export function createSubscriptionLineItemRequestToJSON(
  createSubscriptionLineItemRequest: CreateSubscriptionLineItemRequest,
): string {
  return JSON.stringify(
    CreateSubscriptionLineItemRequest$outboundSchema.parse(
      createSubscriptionLineItemRequest,
    ),
  );
}

/** @internal */
export const CreateSubscriptionLineItemResponse$inboundSchema: z.ZodType<
  CreateSubscriptionLineItemResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoSubscriptionLineItemResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function createSubscriptionLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSubscriptionLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSubscriptionLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSubscriptionLineItemResponse' from JSON`,
  );
}
