/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreateTaxRateResponse =
  | shared.DtoTaxRateResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const CreateTaxRateResponse$inboundSchema: z.ZodType<
  CreateTaxRateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoTaxRateResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function createTaxRateResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTaxRateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTaxRateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTaxRateResponse' from JSON`,
  );
}
