/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreatePaymentResponse =
  | shared.DtoPaymentResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const CreatePaymentResponse$inboundSchema: z.ZodType<
  CreatePaymentResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoPaymentResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function createPaymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentResponse' from JSON`,
  );
}
