/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreatePlanResponse =
  | shared.DtoPlanResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const CreatePlanResponse$inboundSchema: z.ZodType<
  CreatePlanResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoPlanResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function createPlanResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePlanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlanResponse' from JSON`,
  );
}
