/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteEntityIntegrationMappingRequest = {
  /**
   * Entity integration mapping ID
   */
  id: string;
};

/** @internal */
export type DeleteEntityIntegrationMappingRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteEntityIntegrationMappingRequest$outboundSchema: z.ZodType<
  DeleteEntityIntegrationMappingRequest$Outbound,
  z.ZodTypeDef,
  DeleteEntityIntegrationMappingRequest
> = z.object({
  id: z.string(),
});

export function deleteEntityIntegrationMappingRequestToJSON(
  deleteEntityIntegrationMappingRequest: DeleteEntityIntegrationMappingRequest,
): string {
  return JSON.stringify(
    DeleteEntityIntegrationMappingRequest$outboundSchema.parse(
      deleteEntityIntegrationMappingRequest,
    ),
  );
}
