/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type DeleteCouponRequest = {
  /**
   * Coupon ID
   */
  id: string;
};

export type DeleteCouponResponse = shared.ErrorsErrorResponse | {
  [k: string]: string;
};

/** @internal */
export type DeleteCouponRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCouponRequest$outboundSchema: z.ZodType<
  DeleteCouponRequest$Outbound,
  z.ZodTypeDef,
  DeleteCouponRequest
> = z.object({
  id: z.string(),
});

export function deleteCouponRequestToJSON(
  deleteCouponRequest: DeleteCouponRequest,
): string {
  return JSON.stringify(
    DeleteCouponRequest$outboundSchema.parse(deleteCouponRequest),
  );
}

/** @internal */
export const DeleteCouponResponse$inboundSchema: z.ZodType<
  DeleteCouponResponse,
  z.ZodTypeDef,
  unknown
> = z.union([shared.ErrorsErrorResponse$inboundSchema, z.record(z.string())]);

export function deleteCouponResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCouponResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCouponResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCouponResponse' from JSON`,
  );
}
