/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ExecuteSubscriptionChangeRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Subscription change request
   */
  dtoSubscriptionChangeRequest: shared.DtoSubscriptionChangeRequest;
};

export type ExecuteSubscriptionChangeResponse =
  | shared.DtoSubscriptionChangeExecuteResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type ExecuteSubscriptionChangeRequest$Outbound = {
  id: string;
  "dto.SubscriptionChangeRequest": shared.DtoSubscriptionChangeRequest$Outbound;
};

/** @internal */
export const ExecuteSubscriptionChangeRequest$outboundSchema: z.ZodType<
  ExecuteSubscriptionChangeRequest$Outbound,
  z.ZodTypeDef,
  ExecuteSubscriptionChangeRequest
> = z.object({
  id: z.string(),
  dtoSubscriptionChangeRequest:
    shared.DtoSubscriptionChangeRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoSubscriptionChangeRequest: "dto.SubscriptionChangeRequest",
  });
});

export function executeSubscriptionChangeRequestToJSON(
  executeSubscriptionChangeRequest: ExecuteSubscriptionChangeRequest,
): string {
  return JSON.stringify(
    ExecuteSubscriptionChangeRequest$outboundSchema.parse(
      executeSubscriptionChangeRequest,
    ),
  );
}

/** @internal */
export const ExecuteSubscriptionChangeResponse$inboundSchema: z.ZodType<
  ExecuteSubscriptionChangeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoSubscriptionChangeExecuteResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function executeSubscriptionChangeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteSubscriptionChangeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExecuteSubscriptionChangeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteSubscriptionChangeResponse' from JSON`,
  );
}
