/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetActiveCostsheetResponse =
  | shared.DtoCostsheetResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const GetActiveCostsheetResponse$inboundSchema: z.ZodType<
  GetActiveCostsheetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoCostsheetResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getActiveCostsheetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetActiveCostsheetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetActiveCostsheetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetActiveCostsheetResponse' from JSON`,
  );
}
