/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetCustomerUpcomingGrantsRequest = {
  /**
   * Customer ID
   */
  id: string;
};

export type GetCustomerUpcomingGrantsResponse =
  | shared.DtoListCreditGrantApplicationsResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type GetCustomerUpcomingGrantsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomerUpcomingGrantsRequest$outboundSchema: z.ZodType<
  GetCustomerUpcomingGrantsRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerUpcomingGrantsRequest
> = z.object({
  id: z.string(),
});

export function getCustomerUpcomingGrantsRequestToJSON(
  getCustomerUpcomingGrantsRequest: GetCustomerUpcomingGrantsRequest,
): string {
  return JSON.stringify(
    GetCustomerUpcomingGrantsRequest$outboundSchema.parse(
      getCustomerUpcomingGrantsRequest,
    ),
  );
}

/** @internal */
export const GetCustomerUpcomingGrantsResponse$inboundSchema: z.ZodType<
  GetCustomerUpcomingGrantsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListCreditGrantApplicationsResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getCustomerUpcomingGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerUpcomingGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerUpcomingGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerUpcomingGrantsResponse' from JSON`,
  );
}
