/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetEventRequest = {
  /**
   * Event ID
   */
  id: string;
};

export type GetEventResponse =
  | shared.DtoGetEventByIDResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type GetEventRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEventRequest$outboundSchema: z.ZodType<
  GetEventRequest$Outbound,
  z.ZodTypeDef,
  GetEventRequest
> = z.object({
  id: z.string(),
});

export function getEventRequestToJSON(
  getEventRequest: GetEventRequest,
): string {
  return JSON.stringify(GetEventRequest$outboundSchema.parse(getEventRequest));
}

/** @internal */
export const GetEventResponse$inboundSchema: z.ZodType<
  GetEventResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoGetEventByIDResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetEventResponse' from JSON`,
  );
}
