/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetSubscriptionUpcomingGrantsRequest = {
  /**
   * Subscription ID
   */
  id: string;
};

export type GetSubscriptionUpcomingGrantsResponse =
  | shared.DtoListCreditGrantApplicationsResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type GetSubscriptionUpcomingGrantsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSubscriptionUpcomingGrantsRequest$outboundSchema: z.ZodType<
  GetSubscriptionUpcomingGrantsRequest$Outbound,
  z.ZodTypeDef,
  GetSubscriptionUpcomingGrantsRequest
> = z.object({
  id: z.string(),
});

export function getSubscriptionUpcomingGrantsRequestToJSON(
  getSubscriptionUpcomingGrantsRequest: GetSubscriptionUpcomingGrantsRequest,
): string {
  return JSON.stringify(
    GetSubscriptionUpcomingGrantsRequest$outboundSchema.parse(
      getSubscriptionUpcomingGrantsRequest,
    ),
  );
}

/** @internal */
export const GetSubscriptionUpcomingGrantsResponse$inboundSchema: z.ZodType<
  GetSubscriptionUpcomingGrantsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListCreditGrantApplicationsResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getSubscriptionUpcomingGrantsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriptionUpcomingGrantsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetSubscriptionUpcomingGrantsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriptionUpcomingGrantsResponse' from JSON`,
  );
}
