/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export const GetTaxRatesOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetTaxRatesOrder = ClosedEnum<typeof GetTaxRatesOrder>;

export const Scope = {
  Internal: "INTERNAL",
  External: "EXTERNAL",
  Onetime: "ONETIME",
} as const;
export type Scope = ClosedEnum<typeof Scope>;

export const GetTaxRatesStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetTaxRatesStatus = ClosedEnum<typeof GetTaxRatesStatus>;

export type GetTaxRatesRequest = {
  endTime?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetTaxRatesOrder | undefined;
  scope?: Scope | undefined;
  startTime?: string | undefined;
  status?: GetTaxRatesStatus | undefined;
  taxrateCodes?: Array<string> | undefined;
  taxrateIds?: Array<string> | undefined;
};

export type GetTaxRatesResponse =
  | Array<shared.DtoTaxRateResponse>
  | shared.ErrorsErrorResponse;

/** @internal */
export const GetTaxRatesOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetTaxRatesOrder
> = z.nativeEnum(GetTaxRatesOrder);

/** @internal */
export const Scope$outboundSchema: z.ZodNativeEnum<typeof Scope> = z.nativeEnum(
  Scope,
);

/** @internal */
export const GetTaxRatesStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetTaxRatesStatus
> = z.nativeEnum(GetTaxRatesStatus);

/** @internal */
export type GetTaxRatesRequest$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  scope?: string | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  taxrate_codes?: Array<string> | undefined;
  taxrate_ids?: Array<string> | undefined;
};

/** @internal */
export const GetTaxRatesRequest$outboundSchema: z.ZodType<
  GetTaxRatesRequest$Outbound,
  z.ZodTypeDef,
  GetTaxRatesRequest
> = z.object({
  endTime: z.string().optional(),
  expand: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: GetTaxRatesOrder$outboundSchema.optional(),
  scope: Scope$outboundSchema.optional(),
  startTime: z.string().optional(),
  status: GetTaxRatesStatus$outboundSchema.optional(),
  taxrateCodes: z.array(z.string()).optional(),
  taxrateIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    startTime: "start_time",
    taxrateCodes: "taxrate_codes",
    taxrateIds: "taxrate_ids",
  });
});

export function getTaxRatesRequestToJSON(
  getTaxRatesRequest: GetTaxRatesRequest,
): string {
  return JSON.stringify(
    GetTaxRatesRequest$outboundSchema.parse(getTaxRatesRequest),
  );
}

/** @internal */
export const GetTaxRatesResponse$inboundSchema: z.ZodType<
  GetTaxRatesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.array(shared.DtoTaxRateResponse$inboundSchema),
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getTaxRatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatesResponse' from JSON`,
  );
}
