/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetUsageStatisticsResponse =
  | shared.DtoGetUsageResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const GetUsageStatisticsResponse$inboundSchema: z.ZodType<
  GetUsageStatisticsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoGetUsageResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getUsageStatisticsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUsageStatisticsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsageStatisticsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsageStatisticsResponse' from JSON`,
  );
}
