/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export const GetWalletTransactionsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetWalletTransactionsOrder = ClosedEnum<
  typeof GetWalletTransactionsOrder
>;

export const GetWalletTransactionsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetWalletTransactionsStatus = ClosedEnum<
  typeof GetWalletTransactionsStatus
>;

export const TransactionReason = {
  InvoicePayment: "INVOICE_PAYMENT",
  FreeCreditGrant: "FREE_CREDIT_GRANT",
  SubscriptionCreditGrant: "SUBSCRIPTION_CREDIT_GRANT",
  PurchasedCreditInvoiced: "PURCHASED_CREDIT_INVOICED",
  PurchasedCreditDirect: "PURCHASED_CREDIT_DIRECT",
  CreditNote: "CREDIT_NOTE",
  CreditExpired: "CREDIT_EXPIRED",
  WalletTermination: "WALLET_TERMINATION",
  ManualBalanceDebit: "MANUAL_BALANCE_DEBIT",
  CreditAdjustment: "CREDIT_ADJUSTMENT",
} as const;
export type TransactionReason = ClosedEnum<typeof TransactionReason>;

export const TransactionStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
} as const;
export type TransactionStatus = ClosedEnum<typeof TransactionStatus>;

export const Type = {
  Credit: "credit",
  Debit: "debit",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type GetWalletTransactionsRequest = {
  /**
   * Wallet ID
   */
  idPathParameter: string;
  createdBy?: string | undefined;
  creditsAvailableGt?: number | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  expiryDateAfter?: string | undefined;
  expiryDateBefore?: string | undefined;
  idQueryParameter?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetWalletTransactionsOrder | undefined;
  priority?: number | undefined;
  referenceId?: string | undefined;
  referenceType?: string | undefined;
  startTime?: string | undefined;
  status?: GetWalletTransactionsStatus | undefined;
  transactionReason?: TransactionReason | undefined;
  transactionStatus?: TransactionStatus | undefined;
  type?: Type | undefined;
};

export type GetWalletTransactionsResponse =
  | shared.DtoListWalletTransactionsResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const GetWalletTransactionsOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetWalletTransactionsOrder
> = z.nativeEnum(GetWalletTransactionsOrder);

/** @internal */
export const GetWalletTransactionsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetWalletTransactionsStatus
> = z.nativeEnum(GetWalletTransactionsStatus);

/** @internal */
export const TransactionReason$outboundSchema: z.ZodNativeEnum<
  typeof TransactionReason
> = z.nativeEnum(TransactionReason);

/** @internal */
export const TransactionStatus$outboundSchema: z.ZodNativeEnum<
  typeof TransactionStatus
> = z.nativeEnum(TransactionStatus);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export type GetWalletTransactionsRequest$Outbound = {
  idPathParameter: string;
  created_by?: string | undefined;
  credits_available_gt?: number | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  expiry_date_after?: string | undefined;
  expiry_date_before?: string | undefined;
  idQueryParameter?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  priority?: number | undefined;
  reference_id?: string | undefined;
  reference_type?: string | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  transaction_reason?: string | undefined;
  transaction_status?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const GetWalletTransactionsRequest$outboundSchema: z.ZodType<
  GetWalletTransactionsRequest$Outbound,
  z.ZodTypeDef,
  GetWalletTransactionsRequest
> = z.object({
  idPathParameter: z.string(),
  createdBy: z.string().optional(),
  creditsAvailableGt: z.number().optional(),
  endTime: z.string().optional(),
  expand: z.string().optional(),
  expiryDateAfter: z.string().optional(),
  expiryDateBefore: z.string().optional(),
  idQueryParameter: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: GetWalletTransactionsOrder$outboundSchema.optional(),
  priority: z.number().int().optional(),
  referenceId: z.string().optional(),
  referenceType: z.string().optional(),
  startTime: z.string().optional(),
  status: GetWalletTransactionsStatus$outboundSchema.optional(),
  transactionReason: TransactionReason$outboundSchema.optional(),
  transactionStatus: TransactionStatus$outboundSchema.optional(),
  type: Type$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    createdBy: "created_by",
    creditsAvailableGt: "credits_available_gt",
    endTime: "end_time",
    expiryDateAfter: "expiry_date_after",
    expiryDateBefore: "expiry_date_before",
    referenceId: "reference_id",
    referenceType: "reference_type",
    startTime: "start_time",
    transactionReason: "transaction_reason",
    transactionStatus: "transaction_status",
  });
});

export function getWalletTransactionsRequestToJSON(
  getWalletTransactionsRequest: GetWalletTransactionsRequest,
): string {
  return JSON.stringify(
    GetWalletTransactionsRequest$outboundSchema.parse(
      getWalletTransactionsRequest,
    ),
  );
}

/** @internal */
export const GetWalletTransactionsResponse$inboundSchema: z.ZodType<
  GetWalletTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListWalletTransactionsResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function getWalletTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWalletTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWalletTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWalletTransactionsResponse' from JSON`,
  );
}
