/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type IngestEventsBulkResponse =
  | { [k: string]: string }
  | shared.ErrorsErrorResponse;

/** @internal */
export const IngestEventsBulkResponse$inboundSchema: z.ZodType<
  IngestEventsBulkResponse,
  z.ZodTypeDef,
  unknown
> = z.union([z.record(z.string()), shared.ErrorsErrorResponse$inboundSchema]);

export function ingestEventsBulkResponseFromJSON(
  jsonString: string,
): SafeParseResult<IngestEventsBulkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestEventsBulkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestEventsBulkResponse' from JSON`,
  );
}
