/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListTaxAssociationsRequest = {
  /**
   * Entity Type
   */
  entityType?: string | undefined;
  /**
   * Entity ID
   */
  entityId?: string | undefined;
  /**
   * Tax Rate ID
   */
  taxRateId?: string | undefined;
};

export type ListTaxAssociationsResponse =
  | shared.DtoListTaxAssociationsResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type ListTaxAssociationsRequest$Outbound = {
  entity_type?: string | undefined;
  entity_id?: string | undefined;
  tax_rate_id?: string | undefined;
};

/** @internal */
export const ListTaxAssociationsRequest$outboundSchema: z.ZodType<
  ListTaxAssociationsRequest$Outbound,
  z.ZodTypeDef,
  ListTaxAssociationsRequest
> = z.object({
  entityType: z.string().optional(),
  entityId: z.string().optional(),
  taxRateId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    entityType: "entity_type",
    entityId: "entity_id",
    taxRateId: "tax_rate_id",
  });
});

export function listTaxAssociationsRequestToJSON(
  listTaxAssociationsRequest: ListTaxAssociationsRequest,
): string {
  return JSON.stringify(
    ListTaxAssociationsRequest$outboundSchema.parse(listTaxAssociationsRequest),
  );
}

/** @internal */
export const ListTaxAssociationsResponse$inboundSchema: z.ZodType<
  ListTaxAssociationsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListTaxAssociationsResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function listTaxAssociationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTaxAssociationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTaxAssociationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTaxAssociationsResponse' from JSON`,
  );
}
