/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type PostPlansIdCloneRequest = {
  /**
   * Source Plan ID
   */
  id: string;
  /**
   * Clone configuration
   */
  dtoClonePlanRequest: shared.DtoClonePlanRequest;
};

export type PostPlansIdCloneResponse =
  | shared.DtoPlanResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type PostPlansIdCloneRequest$Outbound = {
  id: string;
  "dto.ClonePlanRequest": shared.DtoClonePlanRequest$Outbound;
};

/** @internal */
export const PostPlansIdCloneRequest$outboundSchema: z.ZodType<
  PostPlansIdCloneRequest$Outbound,
  z.ZodTypeDef,
  PostPlansIdCloneRequest
> = z.object({
  id: z.string(),
  dtoClonePlanRequest: shared.DtoClonePlanRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoClonePlanRequest: "dto.ClonePlanRequest",
  });
});

export function postPlansIdCloneRequestToJSON(
  postPlansIdCloneRequest: PostPlansIdCloneRequest,
): string {
  return JSON.stringify(
    PostPlansIdCloneRequest$outboundSchema.parse(postPlansIdCloneRequest),
  );
}

/** @internal */
export const PostPlansIdCloneResponse$inboundSchema: z.ZodType<
  PostPlansIdCloneResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoPlanResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function postPlansIdCloneResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostPlansIdCloneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostPlansIdCloneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostPlansIdCloneResponse' from JSON`,
  );
}
