/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type QueryPlanResponse =
  | shared.DtoListPlansResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const QueryPlanResponse$inboundSchema: z.ZodType<
  QueryPlanResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListPlansResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function queryPlanResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryPlanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryPlanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryPlanResponse' from JSON`,
  );
}
