/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type QueryPriceUnitResponse =
  | shared.DtoListPriceUnitsResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const QueryPriceUnitResponse$inboundSchema: z.ZodType<
  QueryPriceUnitResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListPriceUnitsResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function queryPriceUnitResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryPriceUnitResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryPriceUnitResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryPriceUnitResponse' from JSON`,
  );
}
