/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type QueryCustomerResponse =
  | shared.DtoListCustomersResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const QueryCustomerResponse$inboundSchema: z.ZodType<
  QueryCustomerResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoListCustomersResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function queryCustomerResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryCustomerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryCustomerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryCustomerResponse' from JSON`,
  );
}
