/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type RecalculateInvoiceRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Whether to finalize the invoice after recalculation (default: true)
   */
  finalize?: boolean | undefined;
};

export type RecalculateInvoiceResponse =
  | shared.DtoInvoiceResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type RecalculateInvoiceRequest$Outbound = {
  id: string;
  finalize?: boolean | undefined;
};

/** @internal */
export const RecalculateInvoiceRequest$outboundSchema: z.ZodType<
  RecalculateInvoiceRequest$Outbound,
  z.ZodTypeDef,
  RecalculateInvoiceRequest
> = z.object({
  id: z.string(),
  finalize: z.boolean().optional(),
});

export function recalculateInvoiceRequestToJSON(
  recalculateInvoiceRequest: RecalculateInvoiceRequest,
): string {
  return JSON.stringify(
    RecalculateInvoiceRequest$outboundSchema.parse(recalculateInvoiceRequest),
  );
}

/** @internal */
export const RecalculateInvoiceResponse$inboundSchema: z.ZodType<
  RecalculateInvoiceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoInvoiceResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function recalculateInvoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<RecalculateInvoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RecalculateInvoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RecalculateInvoiceResponse' from JSON`,
  );
}
