/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type TopUpWalletRequest = {
  /**
   * Wallet ID
   */
  id: string;
  /**
   * Top up request
   */
  dtoTopUpWalletRequest: shared.DtoTopUpWalletRequest;
};

export type TopUpWalletResponse =
  | shared.DtoTopUpWalletResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type TopUpWalletRequest$Outbound = {
  id: string;
  "dto.TopUpWalletRequest": shared.DtoTopUpWalletRequest$Outbound;
};

/** @internal */
export const TopUpWalletRequest$outboundSchema: z.ZodType<
  TopUpWalletRequest$Outbound,
  z.ZodTypeDef,
  TopUpWalletRequest
> = z.object({
  id: z.string(),
  dtoTopUpWalletRequest: shared.DtoTopUpWalletRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoTopUpWalletRequest: "dto.TopUpWalletRequest",
  });
});

export function topUpWalletRequestToJSON(
  topUpWalletRequest: TopUpWalletRequest,
): string {
  return JSON.stringify(
    TopUpWalletRequest$outboundSchema.parse(topUpWalletRequest),
  );
}

/** @internal */
export const TopUpWalletResponse$inboundSchema: z.ZodType<
  TopUpWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoTopUpWalletResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function topUpWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<TopUpWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopUpWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopUpWalletResponse' from JSON`,
  );
}
