/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateSubscriptionRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Update Subscription Request
   */
  dtoUpdateSubscriptionRequest: shared.DtoUpdateSubscriptionRequest;
};

export type UpdateSubscriptionResponse =
  | shared.DtoSubscriptionResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type UpdateSubscriptionRequest$Outbound = {
  id: string;
  "dto.UpdateSubscriptionRequest": shared.DtoUpdateSubscriptionRequest$Outbound;
};

/** @internal */
export const UpdateSubscriptionRequest$outboundSchema: z.ZodType<
  UpdateSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  UpdateSubscriptionRequest
> = z.object({
  id: z.string(),
  dtoUpdateSubscriptionRequest:
    shared.DtoUpdateSubscriptionRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdateSubscriptionRequest: "dto.UpdateSubscriptionRequest",
  });
});

export function updateSubscriptionRequestToJSON(
  updateSubscriptionRequest: UpdateSubscriptionRequest,
): string {
  return JSON.stringify(
    UpdateSubscriptionRequest$outboundSchema.parse(updateSubscriptionRequest),
  );
}

/** @internal */
export const UpdateSubscriptionResponse$inboundSchema: z.ZodType<
  UpdateSubscriptionResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoSubscriptionResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateSubscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSubscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSubscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSubscriptionResponse' from JSON`,
  );
}
