/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateInvoicePaymentStatusRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Payment Status Update Request
   */
  dtoUpdatePaymentStatusRequest: shared.DtoUpdatePaymentStatusRequest;
};

export type UpdateInvoicePaymentStatusResponse =
  | shared.DtoInvoiceResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type UpdateInvoicePaymentStatusRequest$Outbound = {
  id: string;
  "dto.UpdatePaymentStatusRequest":
    shared.DtoUpdatePaymentStatusRequest$Outbound;
};

/** @internal */
export const UpdateInvoicePaymentStatusRequest$outboundSchema: z.ZodType<
  UpdateInvoicePaymentStatusRequest$Outbound,
  z.ZodTypeDef,
  UpdateInvoicePaymentStatusRequest
> = z.object({
  id: z.string(),
  dtoUpdatePaymentStatusRequest:
    shared.DtoUpdatePaymentStatusRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdatePaymentStatusRequest: "dto.UpdatePaymentStatusRequest",
  });
});

export function updateInvoicePaymentStatusRequestToJSON(
  updateInvoicePaymentStatusRequest: UpdateInvoicePaymentStatusRequest,
): string {
  return JSON.stringify(
    UpdateInvoicePaymentStatusRequest$outboundSchema.parse(
      updateInvoicePaymentStatusRequest,
    ),
  );
}

/** @internal */
export const UpdateInvoicePaymentStatusResponse$inboundSchema: z.ZodType<
  UpdateInvoicePaymentStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoInvoiceResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateInvoicePaymentStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateInvoicePaymentStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateInvoicePaymentStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateInvoicePaymentStatusResponse' from JSON`,
  );
}
