/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateTaskStatusRequest = {
  /**
   * Task ID
   */
  id: string;
  /**
   * Status update
   */
  dtoUpdateTaskStatusRequest: shared.DtoUpdateTaskStatusRequest;
};

export type UpdateTaskStatusResponse =
  | shared.DtoSuccessResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type UpdateTaskStatusRequest$Outbound = {
  id: string;
  "dto.UpdateTaskStatusRequest": shared.DtoUpdateTaskStatusRequest$Outbound;
};

/** @internal */
export const UpdateTaskStatusRequest$outboundSchema: z.ZodType<
  UpdateTaskStatusRequest$Outbound,
  z.ZodTypeDef,
  UpdateTaskStatusRequest
> = z.object({
  id: z.string(),
  dtoUpdateTaskStatusRequest: shared.DtoUpdateTaskStatusRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdateTaskStatusRequest: "dto.UpdateTaskStatusRequest",
  });
});

export function updateTaskStatusRequestToJSON(
  updateTaskStatusRequest: UpdateTaskStatusRequest,
): string {
  return JSON.stringify(
    UpdateTaskStatusRequest$outboundSchema.parse(updateTaskStatusRequest),
  );
}

/** @internal */
export const UpdateTaskStatusResponse$inboundSchema: z.ZodType<
  UpdateTaskStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoSuccessResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateTaskStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTaskStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTaskStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTaskStatusResponse' from JSON`,
  );
}
