/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateTenantResponse =
  | shared.DtoTenantResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export const UpdateTenantResponse$inboundSchema: z.ZodType<
  UpdateTenantResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoTenantResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateTenantResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTenantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTenantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTenantResponse' from JSON`,
  );
}
