/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateTaxAssociationRequest = {
  /**
   * Tax Config ID
   */
  id: string;
  /**
   * Tax Config Request
   */
  dtoTaxAssociationUpdateRequest: shared.DtoTaxAssociationUpdateRequest;
};

export type UpdateTaxAssociationResponse =
  | shared.DtoTaxAssociationResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type UpdateTaxAssociationRequest$Outbound = {
  id: string;
  "dto.TaxAssociationUpdateRequest":
    shared.DtoTaxAssociationUpdateRequest$Outbound;
};

/** @internal */
export const UpdateTaxAssociationRequest$outboundSchema: z.ZodType<
  UpdateTaxAssociationRequest$Outbound,
  z.ZodTypeDef,
  UpdateTaxAssociationRequest
> = z.object({
  id: z.string(),
  dtoTaxAssociationUpdateRequest:
    shared.DtoTaxAssociationUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoTaxAssociationUpdateRequest: "dto.TaxAssociationUpdateRequest",
  });
});

export function updateTaxAssociationRequestToJSON(
  updateTaxAssociationRequest: UpdateTaxAssociationRequest,
): string {
  return JSON.stringify(
    UpdateTaxAssociationRequest$outboundSchema.parse(
      updateTaxAssociationRequest,
    ),
  );
}

/** @internal */
export const UpdateTaxAssociationResponse$inboundSchema: z.ZodType<
  UpdateTaxAssociationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoTaxAssociationResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateTaxAssociationResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTaxAssociationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTaxAssociationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTaxAssociationResponse' from JSON`,
  );
}
