/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateEntitlementRequest = {
  /**
   * Entitlement ID
   */
  id: string;
  /**
   * Entitlement configuration
   */
  dtoUpdateEntitlementRequest: shared.DtoUpdateEntitlementRequest;
};

export type UpdateEntitlementResponse =
  | shared.DtoEntitlementResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type UpdateEntitlementRequest$Outbound = {
  id: string;
  "dto.UpdateEntitlementRequest": shared.DtoUpdateEntitlementRequest$Outbound;
};

/** @internal */
export const UpdateEntitlementRequest$outboundSchema: z.ZodType<
  UpdateEntitlementRequest$Outbound,
  z.ZodTypeDef,
  UpdateEntitlementRequest
> = z.object({
  id: z.string(),
  dtoUpdateEntitlementRequest:
    shared.DtoUpdateEntitlementRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdateEntitlementRequest: "dto.UpdateEntitlementRequest",
  });
});

export function updateEntitlementRequestToJSON(
  updateEntitlementRequest: UpdateEntitlementRequest,
): string {
  return JSON.stringify(
    UpdateEntitlementRequest$outboundSchema.parse(updateEntitlementRequest),
  );
}

/** @internal */
export const UpdateEntitlementResponse$inboundSchema: z.ZodType<
  UpdateEntitlementResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoEntitlementResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateEntitlementResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateEntitlementResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateEntitlementResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateEntitlementResponse' from JSON`,
  );
}
