/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateAddonRequest = {
  /**
   * Addon ID
   */
  id: string;
  /**
   * Update Addon Request
   */
  dtoUpdateAddonRequest: shared.DtoUpdateAddonRequest;
};

export type UpdateAddonResponse =
  | shared.DtoAddonResponse
  | shared.ErrorsErrorResponse;

/** @internal */
export type UpdateAddonRequest$Outbound = {
  id: string;
  "dto.UpdateAddonRequest": shared.DtoUpdateAddonRequest$Outbound;
};

/** @internal */
export const UpdateAddonRequest$outboundSchema: z.ZodType<
  UpdateAddonRequest$Outbound,
  z.ZodTypeDef,
  UpdateAddonRequest
> = z.object({
  id: z.string(),
  dtoUpdateAddonRequest: shared.DtoUpdateAddonRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dtoUpdateAddonRequest: "dto.UpdateAddonRequest",
  });
});

export function updateAddonRequestToJSON(
  updateAddonRequest: UpdateAddonRequest,
): string {
  return JSON.stringify(
    UpdateAddonRequest$outboundSchema.parse(updateAddonRequest),
  );
}

/** @internal */
export const UpdateAddonResponse$inboundSchema: z.ZodType<
  UpdateAddonResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.DtoAddonResponse$inboundSchema,
  shared.ErrorsErrorResponse$inboundSchema,
]);

export function updateAddonResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAddonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAddonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAddonResponse' from JSON`,
  );
}
