/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { creditGrantsCreateCreditGrant } from "../funcs/creditGrantsCreateCreditGrant.js";
import { creditGrantsDeleteCreditGrant } from "../funcs/creditGrantsDeleteCreditGrant.js";
import { creditGrantsGetCreditGrant } from "../funcs/creditGrantsGetCreditGrant.js";
import { creditGrantsGetPlanCreditGrants } from "../funcs/creditGrantsGetPlanCreditGrants.js";
import { creditGrantsUpdateCreditGrant } from "../funcs/creditGrantsUpdateCreditGrant.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class CreditGrants extends ClientSDK {
  /**
   * Create credit grant
   *
   * @remarks
   * Use when giving a customer or plan credits (e.g. prepaid balance or promotional credits). Scope can be plan or subscription; supports start/end dates.
   */
  async createCreditGrant(
    request: shared.DtoCreateCreditGrantRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCreditGrantResponse> {
    return unwrapAsync(creditGrantsCreateCreditGrant(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete credit grant
   *
   * @remarks
   * Use when removing or ending a credit grant (e.g. revoke promo or close prepaid). Plan-scoped grants are archived; subscription-scoped supports optional effective_date in body.
   */
  async deleteCreditGrant(
    request: operations.DeleteCreditGrantRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteCreditGrantResponse> {
    return unwrapAsync(creditGrantsDeleteCreditGrant(
      this,
      request,
      options,
    ));
  }

  /**
   * Get credit grant
   *
   * @remarks
   * Use when you need to load a single credit grant (e.g. for display or to check balance).
   */
  async getCreditGrant(
    request: operations.GetCreditGrantRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCreditGrantResponse> {
    return unwrapAsync(creditGrantsGetCreditGrant(
      this,
      request,
      options,
    ));
  }

  /**
   * Get plan credit grants
   *
   * @remarks
   * Use when listing credits attached to a plan (e.g. included prepaid or promo credits).
   */
  async getPlanCreditGrants(
    request: operations.GetPlanCreditGrantsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPlanCreditGrantsResponse> {
    return unwrapAsync(creditGrantsGetPlanCreditGrants(
      this,
      request,
      options,
    ));
  }

  /**
   * Update credit grant
   *
   * @remarks
   * Use when changing a credit grant (e.g. amount or end date). Request body contains the fields to update.
   */
  async updateCreditGrant(
    request: operations.UpdateCreditGrantRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateCreditGrantResponse> {
    return unwrapAsync(creditGrantsUpdateCreditGrant(
      this,
      request,
      options,
    ));
  }
}
