/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreateCustomer } from "../funcs/customersCreateCustomer.js";
import { customersDeleteCustomer } from "../funcs/customersDeleteCustomer.js";
import { customersGetCustomer } from "../funcs/customersGetCustomer.js";
import { customersGetCustomerByExternalId } from "../funcs/customersGetCustomerByExternalId.js";
import { customersGetCustomerEntitlements } from "../funcs/customersGetCustomerEntitlements.js";
import { customersGetCustomerUpcomingGrants } from "../funcs/customersGetCustomerUpcomingGrants.js";
import { customersGetCustomerUsageSummary } from "../funcs/customersGetCustomerUsageSummary.js";
import { customersQueryCustomer } from "../funcs/customersQueryCustomer.js";
import { customersUpdateCustomer } from "../funcs/customersUpdateCustomer.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Customers extends ClientSDK {
  /**
   * Create customer
   *
   * @remarks
   * Use when onboarding a new billing customer (e.g. sign-up or CRM sync). Ideal for linking via external_customer_id to your app's user id.
   */
  async createCustomer(
    request: shared.DtoCreateCustomerRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCustomerResponse> {
    return unwrapAsync(customersCreateCustomer(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete customer
   *
   * @remarks
   * Use when removing a customer (e.g. GDPR or churn). Returns 204 No Content on success.
   */
  async deleteCustomer(
    request: operations.DeleteCustomerRequest,
    options?: RequestOptions,
  ): Promise<shared.ErrorsErrorResponse | undefined> {
    return unwrapAsync(customersDeleteCustomer(
      this,
      request,
      options,
    ));
  }

  /**
   * Get customer
   *
   * @remarks
   * Use when you need to load a single customer (e.g. for a billing portal or to attach a subscription).
   */
  async getCustomer(
    request: operations.GetCustomerRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCustomerResponse> {
    return unwrapAsync(customersGetCustomer(
      this,
      request,
      options,
    ));
  }

  /**
   * Get customer by external ID
   *
   * @remarks
   * Use when resolving a customer by your app's id (e.g. from your user table). Ideal for integrations that key by external id.
   */
  async getCustomerByExternalId(
    request: operations.GetCustomerByExternalIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCustomerByExternalIdResponse> {
    return unwrapAsync(customersGetCustomerByExternalId(
      this,
      request,
      options,
    ));
  }

  /**
   * Get customer entitlements
   *
   * @remarks
   * Use when checking what a customer can access (e.g. feature gating or usage limits). Supports optional filters (feature_ids, subscription_ids).
   */
  async getCustomerEntitlements(
    request: operations.GetCustomerEntitlementsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCustomerEntitlementsResponse> {
    return unwrapAsync(customersGetCustomerEntitlements(
      this,
      request,
      options,
    ));
  }

  /**
   * Get upcoming credit grant applications
   *
   * @remarks
   * Use when showing upcoming or pending credits for a customer (e.g. in a portal or for forecasting).
   */
  async getCustomerUpcomingGrants(
    request: operations.GetCustomerUpcomingGrantsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetCustomerUpcomingGrantsResponse> {
    return unwrapAsync(customersGetCustomerUpcomingGrants(
      this,
      request,
      options,
    ));
  }

  /**
   * Get customer usage summary
   *
   * @remarks
   * Use when showing a customer's usage (e.g. portal or overage alerts). Identify by customer_id or customer_lookup_key; supports filters.
   */
  async getCustomerUsageSummary(
    request?: operations.GetCustomerUsageSummaryRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetCustomerUsageSummaryResponse> {
    return unwrapAsync(customersGetCustomerUsageSummary(
      this,
      request,
      options,
    ));
  }

  /**
   * Query customers
   *
   * @remarks
   * Use when listing or searching customers (e.g. admin CRM or reporting). Returns a paginated list; supports filtering and sorting.
   */
  async queryCustomer(
    request: shared.TypesCustomerFilter,
    options?: RequestOptions,
  ): Promise<operations.QueryCustomerResponse> {
    return unwrapAsync(customersQueryCustomer(
      this,
      request,
      options,
    ));
  }

  /**
   * Update customer
   *
   * @remarks
   * Use when updating customer details (e.g. name, email, or metadata). Identify by id or external_customer_id.
   */
  async updateCustomer(
    request: operations.UpdateCustomerRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateCustomerResponse> {
    return unwrapAsync(customersUpdateCustomer(
      this,
      request,
      options,
    ));
  }
}
