/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersDeleteCustomersId } from "../funcs/customers-delete-customers-id.js";
import { customersGetCustomersExternalExternalId } from "../funcs/customers-get-customers-external-external-id.js";
import { customersGetCustomersIdEntitlements } from "../funcs/customers-get-customers-id-entitlements.js";
import { customersGetCustomersIdGrantsUpcoming } from "../funcs/customers-get-customers-id-grants-upcoming.js";
import { customersGetCustomersId } from "../funcs/customers-get-customers-id.js";
import { customersGetCustomersUsage } from "../funcs/customers-get-customers-usage.js";
import { customersGetCustomers } from "../funcs/customers-get-customers.js";
import { customersPostCustomersSearch } from "../funcs/customers-post-customers-search.js";
import { customersPostCustomers } from "../funcs/customers-post-customers.js";
import { customersPutCustomers } from "../funcs/customers-put-customers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Customers extends ClientSDK {
  /**
   * Get customers
   *
   * @remarks
   * Get customers
   */
  async getCustomers(
    request: operations.GetCustomersRequest,
    options?: RequestOptions,
  ): Promise<components.DtoListCustomersResponse> {
    return unwrapAsync(customersGetCustomers(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer
   *
   * @remarks
   * Update a customer by id or external_customer_id
   */
  async putCustomers(
    body: components.DtoUpdateCustomerRequest,
    id?: string | undefined,
    externalCustomerId?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.DtoCustomerResponse> {
    return unwrapAsync(customersPutCustomers(
      this,
      body,
      id,
      externalCustomerId,
      options,
    ));
  }

  /**
   * Create a customer
   *
   * @remarks
   * Create a customer
   */
  async postCustomers(
    request: components.DtoCreateCustomerRequest,
    options?: RequestOptions,
  ): Promise<components.DtoCustomerResponse> {
    return unwrapAsync(customersPostCustomers(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a customer by external id
   *
   * @remarks
   * Get a customer by external id
   */
  async getCustomersExternalExternalId(
    externalId: string,
    options?: RequestOptions,
  ): Promise<components.DtoCustomerResponse> {
    return unwrapAsync(customersGetCustomersExternalExternalId(
      this,
      externalId,
      options,
    ));
  }

  /**
   * List customers by filter
   *
   * @remarks
   * List customers by filter
   */
  async postCustomersSearch(
    request: components.TypesCustomerFilter,
    options?: RequestOptions,
  ): Promise<components.DtoListCustomersResponse> {
    return unwrapAsync(customersPostCustomersSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get customer usage summary
   *
   * @remarks
   * Get customer usage summary by customer_id or customer_lookup_key (external_customer_id)
   */
  async getCustomersUsage(
    request: operations.GetCustomersUsageRequest,
    options?: RequestOptions,
  ): Promise<components.DtoCustomerUsageSummaryResponse> {
    return unwrapAsync(customersGetCustomersUsage(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a customer
   *
   * @remarks
   * Get a customer
   */
  async getCustomersId(
    id: string,
    options?: RequestOptions,
  ): Promise<components.DtoCustomerResponse> {
    return unwrapAsync(customersGetCustomersId(
      this,
      id,
      options,
    ));
  }

  /**
   * Delete a customer
   *
   * @remarks
   * Delete a customer
   */
  async deleteCustomersId(
    id: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(customersDeleteCustomersId(
      this,
      id,
      options,
    ));
  }

  /**
   * Get customer entitlements
   *
   * @remarks
   * Get customer entitlements
   */
  async getCustomersIdEntitlements(
    id: string,
    featureIds?: Array<string> | undefined,
    subscriptionIds?: Array<string> | undefined,
    options?: RequestOptions,
  ): Promise<components.DtoCustomerEntitlementsResponse> {
    return unwrapAsync(customersGetCustomersIdEntitlements(
      this,
      id,
      featureIds,
      subscriptionIds,
      options,
    ));
  }

  /**
   * Get upcoming credit grant applications
   *
   * @remarks
   * Get upcoming credit grant applications for a customer
   */
  async getCustomersIdGrantsUpcoming(
    id: string,
    options?: RequestOptions,
  ): Promise<components.DtoListCreditGrantApplicationsResponse> {
    return unwrapAsync(customersGetCustomersIdGrantsUpcoming(
      this,
      id,
      options,
    ));
  }
}
