/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsCreateOrUpdateIntegration } from "../funcs/integrationsCreateOrUpdateIntegration.js";
import { integrationsDeleteIntegration } from "../funcs/integrationsDeleteIntegration.js";
import { integrationsGetIntegration } from "../funcs/integrationsGetIntegration.js";
import { integrationsListLinkedIntegrations } from "../funcs/integrationsListLinkedIntegrations.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Integrations extends ClientSDK {
  /**
   * Create or update an integration
   *
   * @remarks
   * Use when storing or updating credentials for an external integration (e.g. Stripe, HubSpot). Secrets are encrypted at rest.
   */
  async createOrUpdateIntegration(
    request: operations.CreateOrUpdateIntegrationRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateOrUpdateIntegrationResponse> {
    return unwrapAsync(integrationsCreateOrUpdateIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an integration
   *
   * @remarks
   * Use when disconnecting an integration (e.g. switching provider or removing OAuth). Deletes stored credentials.
   */
  async deleteIntegration(
    request: operations.DeleteIntegrationRequest,
    options?: RequestOptions,
  ): Promise<shared.ErrorsErrorResponse | undefined> {
    return unwrapAsync(integrationsDeleteIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * Get integration details
   *
   * @remarks
   * Use when you need to check or display integration config (e.g. which provider is linked). Sensitive values may be redacted.
   */
  async getIntegration(
    request: operations.GetIntegrationRequest,
    options?: RequestOptions,
  ): Promise<operations.GetIntegrationResponse> {
    return unwrapAsync(integrationsGetIntegration(
      this,
      request,
      options,
    ));
  }

  /**
   * List linked integrations
   *
   * @remarks
   * Use when showing which integrations are connected (e.g. settings page). Returns providers that have valid linked credentials.
   */
  async listLinkedIntegrations(
    options?: RequestOptions,
  ): Promise<operations.ListLinkedIntegrationsResponse> {
    return unwrapAsync(integrationsListLinkedIntegrations(
      this,
      options,
    ));
  }
}
