/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rbacGetRBACRolesId } from "../funcs/rbac-get-rbac-roles-id.js";
import { rbacGetRBACRoles } from "../funcs/rbac-get-rbac-roles.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Rbac extends ClientSDK {
  /**
   * List all RBAC roles
   *
   * @remarks
   * Returns all available roles with their permissions, names, and descriptions
   */
  async getRbacRoles(
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(rbacGetRBACRoles(
      this,
      options,
    ));
  }

  /**
   * Get a specific RBAC role
   *
   * @remarks
   * Returns details of a specific role including permissions, name, and description
   */
  async getRbacRolesId(
    id: string,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(rbacGetRBACRolesId(
      this,
      id,
      options,
    ));
  }
}
