/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { scheduledTasksCreateScheduledTask } from "../funcs/scheduledTasksCreateScheduledTask.js";
import { scheduledTasksDeleteScheduledTask } from "../funcs/scheduledTasksDeleteScheduledTask.js";
import { scheduledTasksGetScheduledTask } from "../funcs/scheduledTasksGetScheduledTask.js";
import { scheduledTasksListScheduledTasks } from "../funcs/scheduledTasksListScheduledTasks.js";
import { scheduledTasksScheduleUpdateBillingPeriod } from "../funcs/scheduledTasksScheduleUpdateBillingPeriod.js";
import { scheduledTasksTriggerScheduledTaskRun } from "../funcs/scheduledTasksTriggerScheduledTaskRun.js";
import { scheduledTasksUpdateScheduledTask } from "../funcs/scheduledTasksUpdateScheduledTask.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class ScheduledTasks extends ClientSDK {
  /**
   * Create scheduled task
   *
   * @remarks
   * Use when setting up recurring data exports or other scheduled jobs. Ideal for report generation or syncing data on a schedule.
   */
  async createScheduledTask(
    request: shared.DtoCreateScheduledTaskRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateScheduledTaskResponse> {
    return unwrapAsync(scheduledTasksCreateScheduledTask(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a scheduled task
   *
   * @remarks
   * Use when removing a scheduled task from the active roster. Archives the task and removes it from the scheduler (soft delete).
   */
  async deleteScheduledTask(
    request: operations.DeleteScheduledTaskRequest,
    options?: RequestOptions,
  ): Promise<shared.ErrorsErrorResponse | undefined> {
    return unwrapAsync(scheduledTasksDeleteScheduledTask(
      this,
      request,
      options,
    ));
  }

  /**
   * Get scheduled task
   *
   * @remarks
   * Use when you need to load a single scheduled task (e.g. to show details in a UI or check its configuration).
   */
  async getScheduledTask(
    request: operations.GetScheduledTaskRequest,
    options?: RequestOptions,
  ): Promise<operations.GetScheduledTaskResponse> {
    return unwrapAsync(scheduledTasksGetScheduledTask(
      this,
      request,
      options,
    ));
  }

  /**
   * List scheduled tasks
   *
   * @remarks
   * Use when listing or managing scheduled tasks in an admin UI. Returns a list; supports filtering by status, type, and pagination.
   */
  async listScheduledTasks(
    request?: operations.ListScheduledTasksRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListScheduledTasksResponse> {
    return unwrapAsync(scheduledTasksListScheduledTasks(
      this,
      request,
      options,
    ));
  }

  /**
   * Schedule update billing period
   *
   * @remarks
   * Use when you need to trigger a billing-period update workflow (e.g. to recalculate or sync billing windows).
   */
  async scheduleUpdateBillingPeriod(
    request: operations.ScheduleUpdateBillingPeriodRequest,
    options?: RequestOptions,
  ): Promise<operations.ScheduleUpdateBillingPeriodResponse> {
    return unwrapAsync(scheduledTasksScheduleUpdateBillingPeriod(
      this,
      request,
      options,
    ));
  }

  /**
   * Trigger force run
   *
   * @remarks
   * Use when you need to run a scheduled export immediately (e.g. on-demand report or catch-up). Supports optional custom time range.
   */
  async triggerScheduledTaskRun(
    request: operations.TriggerScheduledTaskRunRequest,
    options?: RequestOptions,
  ): Promise<operations.TriggerScheduledTaskRunResponse> {
    return unwrapAsync(scheduledTasksTriggerScheduledTaskRun(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a scheduled task
   *
   * @remarks
   * Use when pausing or resuming a scheduled task. Only the enabled field can be changed.
   */
  async updateScheduledTask(
    request: operations.UpdateScheduledTaskRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateScheduledTaskResponse> {
    return unwrapAsync(scheduledTasksUpdateScheduledTask(
      this,
      request,
      options,
    ));
  }
}
