/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsCreateApiKey } from "../funcs/secretsCreateApiKey.js";
import { secretsDeleteApiKey } from "../funcs/secretsDeleteApiKey.js";
import { secretsListApiKeys } from "../funcs/secretsListApiKeys.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class Secrets extends ClientSDK {
  /**
   * List API keys
   *
   * @remarks
   * Use when listing API keys (e.g. admin view or rotating keys). Returns a paginated list.
   */
  async listApiKeys(
    request?: models.ListApiKeysRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListApiKeysResponse> {
    return unwrapAsync(secretsListApiKeys(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new API key
   *
   * @remarks
   * Use when issuing a new API key (e.g. for a service account or for the current user). Provide service_account_id to create for a service account.
   */
  async createApiKey(
    request: models.DtoCreateAPIKeyRequest,
    options?: RequestOptions,
  ): Promise<models.CreateApiKeyResponse> {
    return unwrapAsync(secretsCreateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an API key
   *
   * @remarks
   * Use when revoking an API key (e.g. rotation or compromise). Permanently invalidates the key.
   */
  async deleteApiKey(
    request: models.DeleteApiKeyRequest,
    options?: RequestOptions,
  ): Promise<models.ErrorsErrorResponse | undefined> {
    return unwrapAsync(secretsDeleteApiKey(
      this,
      request,
      options,
    ));
  }
}
