/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { secretsCreateApiKey } from "../funcs/secretsCreateApiKey.js";
import { secretsDeleteApiKey } from "../funcs/secretsDeleteApiKey.js";
import { secretsListApiKeys } from "../funcs/secretsListApiKeys.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Secrets extends ClientSDK {
  /**
   * Create a new API key
   *
   * @remarks
   * Use when issuing a new API key (e.g. for a service account or for the current user). Provide service_account_id to create for a service account.
   */
  async createApiKey(
    request: shared.DtoCreateAPIKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateApiKeyResponse> {
    return unwrapAsync(secretsCreateApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an API key
   *
   * @remarks
   * Use when revoking an API key (e.g. rotation or compromise). Permanently invalidates the key.
   */
  async deleteApiKey(
    request: operations.DeleteApiKeyRequest,
    options?: RequestOptions,
  ): Promise<shared.ErrorsErrorResponse | undefined> {
    return unwrapAsync(secretsDeleteApiKey(
      this,
      request,
      options,
    ));
  }

  /**
   * List API keys
   *
   * @remarks
   * Use when listing API keys (e.g. admin view or rotating keys). Returns a paginated list.
   */
  async listApiKeys(
    request?: operations.ListApiKeysRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListApiKeysResponse> {
    return unwrapAsync(secretsListApiKeys(
      this,
      request,
      options,
    ));
  }
}
