/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taxAssociationsCreateTaxAssociation } from "../funcs/taxAssociationsCreateTaxAssociation.js";
import { taxAssociationsDeleteTaxAssociation } from "../funcs/taxAssociationsDeleteTaxAssociation.js";
import { taxAssociationsGetTaxAssociation } from "../funcs/taxAssociationsGetTaxAssociation.js";
import { taxAssociationsListTaxAssociations } from "../funcs/taxAssociationsListTaxAssociations.js";
import { taxAssociationsUpdateTaxAssociation } from "../funcs/taxAssociationsUpdateTaxAssociation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class TaxAssociations extends ClientSDK {
  /**
   * List tax associations
   *
   * @remarks
   * Use when listing tax associations (e.g. tax config or audit). Returns list with optional filtering.
   */
  async listTaxAssociations(
    request?: models.ListTaxAssociationsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ListTaxAssociationsResponse> {
    return unwrapAsync(taxAssociationsListTaxAssociations(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Tax Association
   *
   * @remarks
   * Use when linking a tax rate to an entity (e.g. customer, product, or region) so that rate applies on invoices.
   */
  async createTaxAssociation(
    request: models.DtoCreateTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.CreateTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsCreateTaxAssociation(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Tax Association
   *
   * @remarks
   * Use when you need to load a single tax association (e.g. for display or editing).
   */
  async getTaxAssociation(
    request: models.GetTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.GetTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsGetTaxAssociation(
      this,
      request,
      options,
    ));
  }

  /**
   * Update tax association
   *
   * @remarks
   * Use when changing a tax association (e.g. switch rate or entity). Request body contains the fields to update.
   */
  async updateTaxAssociation(
    request: models.UpdateTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.UpdateTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsUpdateTaxAssociation(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete tax association
   *
   * @remarks
   * Use when removing a tax association (e.g. entity no longer subject to that rate).
   */
  async deleteTaxAssociation(
    request: models.DeleteTaxAssociationRequest,
    options?: RequestOptions,
  ): Promise<models.DeleteTaxAssociationResponse> {
    return unwrapAsync(taxAssociationsDeleteTaxAssociation(
      this,
      request,
      options,
    ));
  }
}
