/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersCreateUser } from "../funcs/usersCreateUser.js";
import { usersGetUserInfo } from "../funcs/usersGetUserInfo.js";
import { usersQueryUser } from "../funcs/usersQueryUser.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class Users extends ClientSDK {
  /**
   * Create service account
   *
   * @remarks
   * Use when provisioning API access for automation, CI/CD pipelines, or headless integrations that need scoped API keys.
   */
  async createUser(
    request: models.DtoCreateUserRequest,
    options?: RequestOptions,
  ): Promise<models.CreateUserResponse> {
    return unwrapAsync(usersCreateUser(
      this,
      request,
      options,
    ));
  }

  /**
   * Get current user
   *
   * @remarks
   * Use to show the logged-in user's profile in the UI or to check permissions and roles for the current session.
   */
  async getUserInfo(
    options?: RequestOptions,
  ): Promise<models.GetUserInfoResponse> {
    return unwrapAsync(usersGetUserInfo(
      this,
      options,
    ));
  }

  /**
   * Query users
   *
   * @remarks
   * Use when listing or searching service accounts in an admin UI, or when auditing who has API access and which roles they have.
   */
  async queryUser(
    request: models.UserFilter,
    options?: RequestOptions,
  ): Promise<models.QueryUserResponse> {
    return unwrapAsync(usersQueryUser(
      this,
      request,
      options,
    ));
  }
}
