/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowsQueryWorkflow } from "../funcs/workflowsQueryWorkflow.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Workflows extends ClientSDK {
  /**
   * Query workflows
   *
   * @remarks
   * Use when listing or auditing workflow runs (e.g. ops dashboard or debugging). Returns a paginated list; supports filtering by workflow type and status.
   */
  async queryWorkflow(
    request: shared.TypesWorkflowExecutionFilter,
    options?: RequestOptions,
  ): Promise<operations.QueryWorkflowResponse> {
    return unwrapAsync(workflowsQueryWorkflow(
      this,
      request,
      options,
    ));
  }
}
