/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteTaxesRatesIdRequest = {
  /**
   * Tax rate ID
   */
  id: string;
};

/** @internal */
export type DeleteTaxesRatesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTaxesRatesIdRequest$outboundSchema: z.ZodType<
  DeleteTaxesRatesIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteTaxesRatesIdRequest
> = z.object({
  id: z.string(),
});

export function deleteTaxesRatesIdRequestToJSON(
  deleteTaxesRatesIdRequest: DeleteTaxesRatesIdRequest,
): string {
  return JSON.stringify(
    DeleteTaxesRatesIdRequest$outboundSchema.parse(deleteTaxesRatesIdRequest),
  );
}
