/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteSecretsApiKeysIdRequest = {
  /**
   * API key ID
   */
  id: string;
};

/** @internal */
export type DeleteSecretsApiKeysIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSecretsApiKeysIdRequest$outboundSchema: z.ZodType<
  DeleteSecretsApiKeysIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteSecretsApiKeysIdRequest
> = z.object({
  id: z.string(),
});

export function deleteSecretsApiKeysIdRequestToJSON(
  deleteSecretsApiKeysIdRequest: DeleteSecretsApiKeysIdRequest,
): string {
  return JSON.stringify(
    DeleteSecretsApiKeysIdRequest$outboundSchema.parse(
      deleteSecretsApiKeysIdRequest,
    ),
  );
}
