/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetWalletsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetWalletsOrder = ClosedEnum<typeof GetWalletsOrder>;

export const GetWalletsStatus = {
  Active: "active",
  Frozen: "frozen",
  Closed: "closed",
} as const;
export type GetWalletsStatus = ClosedEnum<typeof GetWalletsStatus>;

export type GetWalletsRequest = {
  alertEnabled?: boolean | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetWalletsOrder | undefined;
  sort?: string | undefined;
  status?: GetWalletsStatus | undefined;
  walletIds?: Array<string> | undefined;
};

/** @internal */
export const GetWalletsOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetWalletsOrder
> = z.nativeEnum(GetWalletsOrder);

/** @internal */
export const GetWalletsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetWalletsStatus
> = z.nativeEnum(GetWalletsStatus);

/** @internal */
export type GetWalletsRequest$Outbound = {
  alert_enabled?: boolean | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: string | undefined;
  status?: string | undefined;
  wallet_ids?: Array<string> | undefined;
};

/** @internal */
export const GetWalletsRequest$outboundSchema: z.ZodType<
  GetWalletsRequest$Outbound,
  z.ZodTypeDef,
  GetWalletsRequest
> = z.object({
  alertEnabled: z.boolean().optional(),
  expand: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: GetWalletsOrder$outboundSchema.optional(),
  sort: z.string().optional(),
  status: GetWalletsStatus$outboundSchema.optional(),
  walletIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    alertEnabled: "alert_enabled",
    walletIds: "wallet_ids",
  });
});

export function getWalletsRequestToJSON(
  getWalletsRequest: GetWalletsRequest,
): string {
  return JSON.stringify(
    GetWalletsRequest$outboundSchema.parse(getWalletsRequest),
  );
}
