/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetTaxesRatesIdRequest = {
  /**
   * Tax rate ID
   */
  id: string;
};

/** @internal */
export type GetTaxesRatesIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTaxesRatesIdRequest$outboundSchema: z.ZodType<
  GetTaxesRatesIdRequest$Outbound,
  z.ZodTypeDef,
  GetTaxesRatesIdRequest
> = z.object({
  id: z.string(),
});

export function getTaxesRatesIdRequestToJSON(
  getTaxesRatesIdRequest: GetTaxesRatesIdRequest,
): string {
  return JSON.stringify(
    GetTaxesRatesIdRequest$outboundSchema.parse(getTaxesRatesIdRequest),
  );
}
