/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const CreditNoteStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type CreditNoteStatus = ClosedEnum<typeof CreditNoteStatus>;

export const CreditNoteType = {
  Adjustment: "ADJUSTMENT",
  Refund: "REFUND",
} as const;
export type CreditNoteType = ClosedEnum<typeof CreditNoteType>;

export const GetCreditnotesOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCreditnotesOrder = ClosedEnum<typeof GetCreditnotesOrder>;

export const GetCreditnotesStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetCreditnotesStatus = ClosedEnum<typeof GetCreditnotesStatus>;

export type GetCreditnotesRequest = {
  creditNoteIds?: Array<string> | undefined;
  creditNoteStatus?: Array<CreditNoteStatus> | undefined;
  creditNoteType?: CreditNoteType | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  invoiceId?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetCreditnotesOrder | undefined;
  sort?: string | undefined;
  startTime?: string | undefined;
  status?: GetCreditnotesStatus | undefined;
};

/** @internal */
export const CreditNoteStatus$outboundSchema: z.ZodNativeEnum<
  typeof CreditNoteStatus
> = z.nativeEnum(CreditNoteStatus);

/** @internal */
export const CreditNoteType$outboundSchema: z.ZodNativeEnum<
  typeof CreditNoteType
> = z.nativeEnum(CreditNoteType);

/** @internal */
export const GetCreditnotesOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetCreditnotesOrder
> = z.nativeEnum(GetCreditnotesOrder);

/** @internal */
export const GetCreditnotesStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetCreditnotesStatus
> = z.nativeEnum(GetCreditnotesStatus);

/** @internal */
export type GetCreditnotesRequest$Outbound = {
  credit_note_ids?: Array<string> | undefined;
  credit_note_status?: Array<string> | undefined;
  credit_note_type?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  invoice_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const GetCreditnotesRequest$outboundSchema: z.ZodType<
  GetCreditnotesRequest$Outbound,
  z.ZodTypeDef,
  GetCreditnotesRequest
> = z.object({
  creditNoteIds: z.array(z.string()).optional(),
  creditNoteStatus: z.array(CreditNoteStatus$outboundSchema).optional(),
  creditNoteType: CreditNoteType$outboundSchema.optional(),
  endTime: z.string().optional(),
  expand: z.string().optional(),
  invoiceId: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: GetCreditnotesOrder$outboundSchema.optional(),
  sort: z.string().optional(),
  startTime: z.string().optional(),
  status: GetCreditnotesStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    creditNoteIds: "credit_note_ids",
    creditNoteStatus: "credit_note_status",
    creditNoteType: "credit_note_type",
    endTime: "end_time",
    invoiceId: "invoice_id",
    startTime: "start_time",
  });
});

export function getCreditnotesRequestToJSON(
  getCreditnotesRequest: GetCreditnotesRequest,
): string {
  return JSON.stringify(
    GetCreditnotesRequest$outboundSchema.parse(getCreditnotesRequest),
  );
}
