/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetPricesUnitsCodeCodeRequest = {
  /**
   * Price unit code
   */
  code: string;
};

/** @internal */
export type GetPricesUnitsCodeCodeRequest$Outbound = {
  code: string;
};

/** @internal */
export const GetPricesUnitsCodeCodeRequest$outboundSchema: z.ZodType<
  GetPricesUnitsCodeCodeRequest$Outbound,
  z.ZodTypeDef,
  GetPricesUnitsCodeCodeRequest
> = z.object({
  code: z.string(),
});

export function getPricesUnitsCodeCodeRequestToJSON(
  getPricesUnitsCodeCodeRequest: GetPricesUnitsCodeCodeRequest,
): string {
  return JSON.stringify(
    GetPricesUnitsCodeCodeRequest$outboundSchema.parse(
      getPricesUnitsCodeCodeRequest,
    ),
  );
}
