/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetCreditgrantsIdRequest = {
  /**
   * Credit Grant ID
   */
  id: string;
};

/** @internal */
export type GetCreditgrantsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCreditgrantsIdRequest$outboundSchema: z.ZodType<
  GetCreditgrantsIdRequest$Outbound,
  z.ZodTypeDef,
  GetCreditgrantsIdRequest
> = z.object({
  id: z.string(),
});

export function getCreditgrantsIdRequestToJSON(
  getCreditgrantsIdRequest: GetCreditgrantsIdRequest,
): string {
  return JSON.stringify(
    GetCreditgrantsIdRequest$outboundSchema.parse(getCreditgrantsIdRequest),
  );
}
