/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetCustomerDashboardUsageSecurity = {
  bearerAuth: string;
};

export type GetCustomerDashboardUsageRequest = {
  customerId?: string | undefined;
  customerLookupKey?: string | undefined;
  featureIds?: Array<string> | undefined;
  featureLookupKeys?: Array<string> | undefined;
  subscriptionIds?: Array<string> | undefined;
};

/** @internal */
export type GetCustomerDashboardUsageSecurity$Outbound = {
  BearerAuth: string;
};

/** @internal */
export const GetCustomerDashboardUsageSecurity$outboundSchema: z.ZodType<
  GetCustomerDashboardUsageSecurity$Outbound,
  z.ZodTypeDef,
  GetCustomerDashboardUsageSecurity
> = z.object({
  bearerAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    bearerAuth: "BearerAuth",
  });
});

export function getCustomerDashboardUsageSecurityToJSON(
  getCustomerDashboardUsageSecurity: GetCustomerDashboardUsageSecurity,
): string {
  return JSON.stringify(
    GetCustomerDashboardUsageSecurity$outboundSchema.parse(
      getCustomerDashboardUsageSecurity,
    ),
  );
}

/** @internal */
export type GetCustomerDashboardUsageRequest$Outbound = {
  customer_id?: string | undefined;
  customer_lookup_key?: string | undefined;
  feature_ids?: Array<string> | undefined;
  feature_lookup_keys?: Array<string> | undefined;
  subscription_ids?: Array<string> | undefined;
};

/** @internal */
export const GetCustomerDashboardUsageRequest$outboundSchema: z.ZodType<
  GetCustomerDashboardUsageRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerDashboardUsageRequest
> = z.object({
  customerId: z.string().optional(),
  customerLookupKey: z.string().optional(),
  featureIds: z.array(z.string()).optional(),
  featureLookupKeys: z.array(z.string()).optional(),
  subscriptionIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    customerLookupKey: "customer_lookup_key",
    featureIds: "feature_ids",
    featureLookupKeys: "feature_lookup_keys",
    subscriptionIds: "subscription_ids",
  });
});

export function getCustomerDashboardUsageRequestToJSON(
  getCustomerDashboardUsageRequest: GetCustomerDashboardUsageRequest,
): string {
  return JSON.stringify(
    GetCustomerDashboardUsageRequest$outboundSchema.parse(
      getCustomerDashboardUsageRequest,
    ),
  );
}
