/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetCustomersWalletsRequest = {
  id?: string | undefined;
  includeRealTimeBalance?: boolean | undefined;
  lookupKey?: string | undefined;
};

/** @internal */
export type GetCustomersWalletsRequest$Outbound = {
  id?: string | undefined;
  include_real_time_balance: boolean;
  lookup_key?: string | undefined;
};

/** @internal */
export const GetCustomersWalletsRequest$outboundSchema: z.ZodType<
  GetCustomersWalletsRequest$Outbound,
  z.ZodTypeDef,
  GetCustomersWalletsRequest
> = z.object({
  id: z.string().optional(),
  includeRealTimeBalance: z.boolean().default(false),
  lookupKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    includeRealTimeBalance: "include_real_time_balance",
    lookupKey: "lookup_key",
  });
});

export function getCustomersWalletsRequestToJSON(
  getCustomersWalletsRequest: GetCustomersWalletsRequest,
): string {
  return JSON.stringify(
    GetCustomersWalletsRequest$outboundSchema.parse(getCustomersWalletsRequest),
  );
}
