/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetCustomersIdInvoicesSummaryRequest = {
  /**
   * Customer ID
   */
  id: string;
};

/** @internal */
export type GetCustomersIdInvoicesSummaryRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomersIdInvoicesSummaryRequest$outboundSchema: z.ZodType<
  GetCustomersIdInvoicesSummaryRequest$Outbound,
  z.ZodTypeDef,
  GetCustomersIdInvoicesSummaryRequest
> = z.object({
  id: z.string(),
});

export function getCustomersIdInvoicesSummaryRequestToJSON(
  getCustomersIdInvoicesSummaryRequest: GetCustomersIdInvoicesSummaryRequest,
): string {
  return JSON.stringify(
    GetCustomersIdInvoicesSummaryRequest$outboundSchema.parse(
      getCustomersIdInvoicesSummaryRequest,
    ),
  );
}
