/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetEntitlementsEntityType = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
  Addon: "ADDON",
} as const;
export type GetEntitlementsEntityType = ClosedEnum<
  typeof GetEntitlementsEntityType
>;

export const FeatureType = {
  Metered: "metered",
  Boolean: "boolean",
  Static: "static",
} as const;
export type FeatureType = ClosedEnum<typeof FeatureType>;

export const GetEntitlementsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetEntitlementsOrder = ClosedEnum<typeof GetEntitlementsOrder>;

export const GetEntitlementsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetEntitlementsStatus = ClosedEnum<typeof GetEntitlementsStatus>;

export type GetEntitlementsRequest = {
  endTime?: string | undefined;
  entityIds?: Array<string> | undefined;
  entityType?: GetEntitlementsEntityType | undefined;
  expand?: string | undefined;
  featureIds?: Array<string> | undefined;
  featureType?: FeatureType | undefined;
  isEnabled?: boolean | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetEntitlementsOrder | undefined;
  planIds?: Array<string> | undefined;
  startTime?: string | undefined;
  status?: GetEntitlementsStatus | undefined;
};

/** @internal */
export const GetEntitlementsEntityType$outboundSchema: z.ZodNativeEnum<
  typeof GetEntitlementsEntityType
> = z.nativeEnum(GetEntitlementsEntityType);

/** @internal */
export const FeatureType$outboundSchema: z.ZodNativeEnum<typeof FeatureType> = z
  .nativeEnum(FeatureType);

/** @internal */
export const GetEntitlementsOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetEntitlementsOrder
> = z.nativeEnum(GetEntitlementsOrder);

/** @internal */
export const GetEntitlementsStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetEntitlementsStatus
> = z.nativeEnum(GetEntitlementsStatus);

/** @internal */
export type GetEntitlementsRequest$Outbound = {
  end_time?: string | undefined;
  entity_ids?: Array<string> | undefined;
  entity_type?: string | undefined;
  expand?: string | undefined;
  feature_ids?: Array<string> | undefined;
  feature_type?: string | undefined;
  is_enabled?: boolean | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  plan_ids?: Array<string> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const GetEntitlementsRequest$outboundSchema: z.ZodType<
  GetEntitlementsRequest$Outbound,
  z.ZodTypeDef,
  GetEntitlementsRequest
> = z.object({
  endTime: z.string().optional(),
  entityIds: z.array(z.string()).optional(),
  entityType: GetEntitlementsEntityType$outboundSchema.optional(),
  expand: z.string().optional(),
  featureIds: z.array(z.string()).optional(),
  featureType: FeatureType$outboundSchema.optional(),
  isEnabled: z.boolean().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: GetEntitlementsOrder$outboundSchema.optional(),
  planIds: z.array(z.string()).optional(),
  startTime: z.string().optional(),
  status: GetEntitlementsStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    entityIds: "entity_ids",
    entityType: "entity_type",
    featureIds: "feature_ids",
    featureType: "feature_type",
    isEnabled: "is_enabled",
    planIds: "plan_ids",
    startTime: "start_time",
  });
});

export function getEntitlementsRequestToJSON(
  getEntitlementsRequest: GetEntitlementsRequest,
): string {
  return JSON.stringify(
    GetEntitlementsRequest$outboundSchema.parse(getEntitlementsRequest),
  );
}
