/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetPlansOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetPlansOrder = ClosedEnum<typeof GetPlansOrder>;

export const GetPlansStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetPlansStatus = ClosedEnum<typeof GetPlansStatus>;

export type GetPlansRequest = {
  endTime?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  lookupKey?: string | undefined;
  offset?: number | undefined;
  order?: GetPlansOrder | undefined;
  planIds?: Array<string> | undefined;
  startTime?: string | undefined;
  status?: GetPlansStatus | undefined;
};

/** @internal */
export const GetPlansOrder$outboundSchema: z.ZodNativeEnum<
  typeof GetPlansOrder
> = z.nativeEnum(GetPlansOrder);

/** @internal */
export const GetPlansStatus$outboundSchema: z.ZodNativeEnum<
  typeof GetPlansStatus
> = z.nativeEnum(GetPlansStatus);

/** @internal */
export type GetPlansRequest$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  lookup_key?: string | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  plan_ids?: Array<string> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const GetPlansRequest$outboundSchema: z.ZodType<
  GetPlansRequest$Outbound,
  z.ZodTypeDef,
  GetPlansRequest
> = z.object({
  endTime: z.string().optional(),
  expand: z.string().optional(),
  limit: z.number().int().optional(),
  lookupKey: z.string().optional(),
  offset: z.number().int().optional(),
  order: GetPlansOrder$outboundSchema.optional(),
  planIds: z.array(z.string()).optional(),
  startTime: z.string().optional(),
  status: GetPlansStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    lookupKey: "lookup_key",
    planIds: "plan_ids",
    startTime: "start_time",
  });
});

export function getPlansRequestToJSON(
  getPlansRequest: GetPlansRequest,
): string {
  return JSON.stringify(GetPlansRequest$outboundSchema.parse(getPlansRequest));
}
