/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetTaxesAssociationsRequest = {
  /**
   * Entity Type
   */
  entityType?: string | undefined;
  /**
   * Entity ID
   */
  entityId?: string | undefined;
  /**
   * Tax Rate ID
   */
  taxRateId?: string | undefined;
};

/** @internal */
export type GetTaxesAssociationsRequest$Outbound = {
  entity_type?: string | undefined;
  entity_id?: string | undefined;
  tax_rate_id?: string | undefined;
};

/** @internal */
export const GetTaxesAssociationsRequest$outboundSchema: z.ZodType<
  GetTaxesAssociationsRequest$Outbound,
  z.ZodTypeDef,
  GetTaxesAssociationsRequest
> = z.object({
  entityType: z.string().optional(),
  entityId: z.string().optional(),
  taxRateId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    entityType: "entity_type",
    entityId: "entity_id",
    taxRateId: "tax_rate_id",
  });
});

export function getTaxesAssociationsRequestToJSON(
  getTaxesAssociationsRequest: GetTaxesAssociationsRequest,
): string {
  return JSON.stringify(
    GetTaxesAssociationsRequest$outboundSchema.parse(
      getTaxesAssociationsRequest,
    ),
  );
}
