/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type PostSubscriptionsIdPauseRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Pause subscription request
   */
  body: components.DtoPauseSubscriptionRequest;
};

/** @internal */
export type PostSubscriptionsIdPauseRequest$Outbound = {
  id: string;
  body: components.DtoPauseSubscriptionRequest$Outbound;
};

/** @internal */
export const PostSubscriptionsIdPauseRequest$outboundSchema: z.ZodType<
  PostSubscriptionsIdPauseRequest$Outbound,
  z.ZodTypeDef,
  PostSubscriptionsIdPauseRequest
> = z.object({
  id: z.string(),
  body: components.DtoPauseSubscriptionRequest$outboundSchema,
});

export function postSubscriptionsIdPauseRequestToJSON(
  postSubscriptionsIdPauseRequest: PostSubscriptionsIdPauseRequest,
): string {
  return JSON.stringify(
    PostSubscriptionsIdPauseRequest$outboundSchema.parse(
      postSubscriptionsIdPauseRequest,
    ),
  );
}
