/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostCreditnotesIdVoidRequest = {
  /**
   * Credit note ID
   */
  id: string;
};

/** @internal */
export type PostCreditnotesIdVoidRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostCreditnotesIdVoidRequest$outboundSchema: z.ZodType<
  PostCreditnotesIdVoidRequest$Outbound,
  z.ZodTypeDef,
  PostCreditnotesIdVoidRequest
> = z.object({
  id: z.string(),
});

export function postCreditnotesIdVoidRequestToJSON(
  postCreditnotesIdVoidRequest: PostCreditnotesIdVoidRequest,
): string {
  return JSON.stringify(
    PostCreditnotesIdVoidRequest$outboundSchema.parse(
      postCreditnotesIdVoidRequest,
    ),
  );
}
