/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostGroupsSearchRequest = {
  /**
   * Filter by entity type (e.g., 'price')
   */
  entityType?: string | undefined;
  /**
   * Filter by group name (contains search)
   */
  name?: string | undefined;
  /**
   * Filter by lookup key (exact match)
   */
  lookupKey?: string | undefined;
  /**
   * Number of items to return (default: 20)
   */
  limit?: number | undefined;
  /**
   * Number of items to skip (default: 0)
   */
  offset?: number | undefined;
  /**
   * Field to sort by (name, created_at, updated_at)
   */
  sortBy?: string | undefined;
  /**
   * Sort order (asc, desc)
   */
  sortOrder?: string | undefined;
};

/** @internal */
export type PostGroupsSearchRequest$Outbound = {
  entity_type?: string | undefined;
  name?: string | undefined;
  lookup_key?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  sort_by?: string | undefined;
  sort_order?: string | undefined;
};

/** @internal */
export const PostGroupsSearchRequest$outboundSchema: z.ZodType<
  PostGroupsSearchRequest$Outbound,
  z.ZodTypeDef,
  PostGroupsSearchRequest
> = z.object({
  entityType: z.string().optional(),
  name: z.string().optional(),
  lookupKey: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  sortBy: z.string().optional(),
  sortOrder: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    entityType: "entity_type",
    lookupKey: "lookup_key",
    sortBy: "sort_by",
    sortOrder: "sort_order",
  });
});

export function postGroupsSearchRequestToJSON(
  postGroupsSearchRequest: PostGroupsSearchRequest,
): string {
  return JSON.stringify(
    PostGroupsSearchRequest$outboundSchema.parse(postGroupsSearchRequest),
  );
}
