/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostWebhooksChargebeeTenantIdEnvironmentIdRequest = {
  /**
   * Tenant ID
   */
  tenantId: string;
  /**
   * Environment ID
   */
  environmentId: string;
};

/** @internal */
export type PostWebhooksChargebeeTenantIdEnvironmentIdRequest$Outbound = {
  tenant_id: string;
  environment_id: string;
};

/** @internal */
export const PostWebhooksChargebeeTenantIdEnvironmentIdRequest$outboundSchema:
  z.ZodType<
    PostWebhooksChargebeeTenantIdEnvironmentIdRequest$Outbound,
    z.ZodTypeDef,
    PostWebhooksChargebeeTenantIdEnvironmentIdRequest
  > = z.object({
    tenantId: z.string(),
    environmentId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      tenantId: "tenant_id",
      environmentId: "environment_id",
    });
  });

export function postWebhooksChargebeeTenantIdEnvironmentIdRequestToJSON(
  postWebhooksChargebeeTenantIdEnvironmentIdRequest:
    PostWebhooksChargebeeTenantIdEnvironmentIdRequest,
): string {
  return JSON.stringify(
    PostWebhooksChargebeeTenantIdEnvironmentIdRequest$outboundSchema.parse(
      postWebhooksChargebeeTenantIdEnvironmentIdRequest,
    ),
  );
}
