/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostCustomerDashboardSubscriptionsSecurity = {
  bearerAuth: string;
};

/** @internal */
export type PostCustomerDashboardSubscriptionsSecurity$Outbound = {
  BearerAuth: string;
};

/** @internal */
export const PostCustomerDashboardSubscriptionsSecurity$outboundSchema:
  z.ZodType<
    PostCustomerDashboardSubscriptionsSecurity$Outbound,
    z.ZodTypeDef,
    PostCustomerDashboardSubscriptionsSecurity
  > = z.object({
    bearerAuth: z.string(),
  }).transform((v) => {
    return remap$(v, {
      bearerAuth: "BearerAuth",
    });
  });

export function postCustomerDashboardSubscriptionsSecurityToJSON(
  postCustomerDashboardSubscriptionsSecurity:
    PostCustomerDashboardSubscriptionsSecurity,
): string {
  return JSON.stringify(
    PostCustomerDashboardSubscriptionsSecurity$outboundSchema.parse(
      postCustomerDashboardSubscriptionsSecurity,
    ),
  );
}
