/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type PostSecretsIntegrationsCreateProviderRequest = {
  /**
   * Integration provider
   */
  provider: string;
  /**
   * Integration creation request
   */
  body: components.DtoCreateIntegrationRequest;
};

/** @internal */
export type PostSecretsIntegrationsCreateProviderRequest$Outbound = {
  provider: string;
  body: components.DtoCreateIntegrationRequest$Outbound;
};

/** @internal */
export const PostSecretsIntegrationsCreateProviderRequest$outboundSchema:
  z.ZodType<
    PostSecretsIntegrationsCreateProviderRequest$Outbound,
    z.ZodTypeDef,
    PostSecretsIntegrationsCreateProviderRequest
  > = z.object({
    provider: z.string(),
    body: components.DtoCreateIntegrationRequest$outboundSchema,
  });

export function postSecretsIntegrationsCreateProviderRequestToJSON(
  postSecretsIntegrationsCreateProviderRequest:
    PostSecretsIntegrationsCreateProviderRequest,
): string {
  return JSON.stringify(
    PostSecretsIntegrationsCreateProviderRequest$outboundSchema.parse(
      postSecretsIntegrationsCreateProviderRequest,
    ),
  );
}
