/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostInvoicesIdFinalizeRequest = {
  /**
   * Invoice ID
   */
  id: string;
};

/** @internal */
export type PostInvoicesIdFinalizeRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostInvoicesIdFinalizeRequest$outboundSchema: z.ZodType<
  PostInvoicesIdFinalizeRequest$Outbound,
  z.ZodTypeDef,
  PostInvoicesIdFinalizeRequest
> = z.object({
  id: z.string(),
});

export function postInvoicesIdFinalizeRequestToJSON(
  postInvoicesIdFinalizeRequest: PostInvoicesIdFinalizeRequest,
): string {
  return JSON.stringify(
    PostInvoicesIdFinalizeRequest$outboundSchema.parse(
      postInvoicesIdFinalizeRequest,
    ),
  );
}
