/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostInvoicesIdRecalculateRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Whether to finalize the invoice after recalculation (default: true)
   */
  finalize?: boolean | undefined;
};

/** @internal */
export type PostInvoicesIdRecalculateRequest$Outbound = {
  id: string;
  finalize?: boolean | undefined;
};

/** @internal */
export const PostInvoicesIdRecalculateRequest$outboundSchema: z.ZodType<
  PostInvoicesIdRecalculateRequest$Outbound,
  z.ZodTypeDef,
  PostInvoicesIdRecalculateRequest
> = z.object({
  id: z.string(),
  finalize: z.boolean().optional(),
});

export function postInvoicesIdRecalculateRequestToJSON(
  postInvoicesIdRecalculateRequest: PostInvoicesIdRecalculateRequest,
): string {
  return JSON.stringify(
    PostInvoicesIdRecalculateRequest$outboundSchema.parse(
      postInvoicesIdRecalculateRequest,
    ),
  );
}
