/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type PutAddonsIdRequest = {
  /**
   * Addon ID
   */
  id: string;
  /**
   * Update Addon Request
   */
  body: components.DtoUpdateAddonRequest;
};

/** @internal */
export type PutAddonsIdRequest$Outbound = {
  id: string;
  body: components.DtoUpdateAddonRequest$Outbound;
};

/** @internal */
export const PutAddonsIdRequest$outboundSchema: z.ZodType<
  PutAddonsIdRequest$Outbound,
  z.ZodTypeDef,
  PutAddonsIdRequest
> = z.object({
  id: z.string(),
  body: components.DtoUpdateAddonRequest$outboundSchema,
});

export function putAddonsIdRequestToJSON(
  putAddonsIdRequest: PutAddonsIdRequest,
): string {
  return JSON.stringify(
    PutAddonsIdRequest$outboundSchema.parse(putAddonsIdRequest),
  );
}
