/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type PutCustomersIdRequest = {
  /**
   * Customer ID
   */
  id: string;
  /**
   * Customer
   */
  body: components.DtoUpdateCustomerRequest;
};

/** @internal */
export type PutCustomersIdRequest$Outbound = {
  id: string;
  body: components.DtoUpdateCustomerRequest$Outbound;
};

/** @internal */
export const PutCustomersIdRequest$outboundSchema: z.ZodType<
  PutCustomersIdRequest$Outbound,
  z.ZodTypeDef,
  PutCustomersIdRequest
> = z.object({
  id: z.string(),
  body: components.DtoUpdateCustomerRequest$outboundSchema,
});

export function putCustomersIdRequestToJSON(
  putCustomersIdRequest: PutCustomersIdRequest,
): string {
  return JSON.stringify(
    PutCustomersIdRequest$outboundSchema.parse(putCustomersIdRequest),
  );
}
