/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type PutPlansIdRequest = {
  /**
   * Plan ID
   */
  id: string;
  /**
   * Plan update
   */
  body: components.DtoUpdatePlanRequest;
};

/** @internal */
export type PutPlansIdRequest$Outbound = {
  id: string;
  body: components.DtoUpdatePlanRequest$Outbound;
};

/** @internal */
export const PutPlansIdRequest$outboundSchema: z.ZodType<
  PutPlansIdRequest$Outbound,
  z.ZodTypeDef,
  PutPlansIdRequest
> = z.object({
  id: z.string(),
  body: components.DtoUpdatePlanRequest$outboundSchema,
});

export function putPlansIdRequestToJSON(
  putPlansIdRequest: PutPlansIdRequest,
): string {
  return JSON.stringify(
    PutPlansIdRequest$outboundSchema.parse(putPlansIdRequest),
  );
}
