"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Coupons = void 0;
const couponsDeleteCouponsId_js_1 = require("../funcs/couponsDeleteCouponsId.js");
const couponsGetCoupons_js_1 = require("../funcs/couponsGetCoupons.js");
const couponsGetCouponsId_js_1 = require("../funcs/couponsGetCouponsId.js");
const couponsPostCoupons_js_1 = require("../funcs/couponsPostCoupons.js");
const couponsPutCouponsId_js_1 = require("../funcs/couponsPutCouponsId.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Coupons extends sdks_js_1.ClientSDK {
    /**
     * List coupons with filtering
     *
     * @remarks
     * Lists coupons with filtering
     */
    async getCoupons(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, couponsGetCoupons_js_1.couponsGetCoupons)(this, request, options));
    }
    /**
     * Create a new coupon
     *
     * @remarks
     * Creates a new coupon
     */
    async postCoupons(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, couponsPostCoupons_js_1.couponsPostCoupons)(this, request, options));
    }
    /**
     * Get a coupon by ID
     *
     * @remarks
     * Retrieves a coupon by ID
     */
    async getCouponsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, couponsGetCouponsId_js_1.couponsGetCouponsId)(this, id, options));
    }
    /**
     * Update a coupon
     *
     * @remarks
     * Updates an existing coupon
     */
    async putCouponsId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, couponsPutCouponsId_js_1.couponsPutCouponsId)(this, id, body, options));
    }
    /**
     * Delete a coupon
     *
     * @remarks
     * Deletes a coupon
     */
    async deleteCouponsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, couponsDeleteCouponsId_js_1.couponsDeleteCouponsId)(this, id, options));
    }
}
exports.Coupons = Coupons;
//# sourceMappingURL=coupons.js.map