"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreditGrants = void 0;
const creditGrantsDeleteCreditgrantsId_js_1 = require("../funcs/creditGrantsDeleteCreditgrantsId.js");
const creditGrantsGetCreditgrants_js_1 = require("../funcs/creditGrantsGetCreditgrants.js");
const creditGrantsGetCreditgrantsId_js_1 = require("../funcs/creditGrantsGetCreditgrantsId.js");
const creditGrantsGetPlansIdCreditgrants_js_1 = require("../funcs/creditGrantsGetPlansIdCreditgrants.js");
const creditGrantsPostCreditgrants_js_1 = require("../funcs/creditGrantsPostCreditgrants.js");
const creditGrantsPutCreditgrantsId_js_1 = require("../funcs/creditGrantsPutCreditgrantsId.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class CreditGrants extends sdks_js_1.ClientSDK {
    /**
     * Get credit grants
     *
     * @remarks
     * Get credit grants with the specified filter
     */
    async getCreditgrants(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, creditGrantsGetCreditgrants_js_1.creditGrantsGetCreditgrants)(this, request, options));
    }
    /**
     * Create a new credit grant
     *
     * @remarks
     * Create a new credit grant with the specified configuration
     */
    async postCreditgrants(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, creditGrantsPostCreditgrants_js_1.creditGrantsPostCreditgrants)(this, request, options));
    }
    /**
     * Get a credit grant by ID
     *
     * @remarks
     * Get a credit grant by ID
     */
    async getCreditgrantsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, creditGrantsGetCreditgrantsId_js_1.creditGrantsGetCreditgrantsId)(this, id, options));
    }
    /**
     * Update a credit grant
     *
     * @remarks
     * Update a credit grant with the specified configuration
     */
    async putCreditgrantsId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, creditGrantsPutCreditgrantsId_js_1.creditGrantsPutCreditgrantsId)(this, id, body, options));
    }
    /**
     * Delete a credit grant
     *
     * @remarks
     * Delete a credit grant
     */
    async deleteCreditgrantsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, creditGrantsDeleteCreditgrantsId_js_1.creditGrantsDeleteCreditgrantsId)(this, id, options));
    }
    /**
     * Get plan credit grants
     *
     * @remarks
     * Get all credit grants for a plan
     */
    async getPlansIdCreditgrants(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, creditGrantsGetPlansIdCreditgrants_js_1.creditGrantsGetPlansIdCreditgrants)(this, id, options));
    }
}
exports.CreditGrants = CreditGrants;
//# sourceMappingURL=creditgrants.js.map