"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreditGrants = void 0;
const credit_grants_delete_creditgrants_id_js_1 = require("../funcs/credit-grants-delete-creditgrants-id.js");
const credit_grants_get_creditgrants_id_js_1 = require("../funcs/credit-grants-get-creditgrants-id.js");
const credit_grants_get_creditgrants_js_1 = require("../funcs/credit-grants-get-creditgrants.js");
const credit_grants_get_plans_id_creditgrants_js_1 = require("../funcs/credit-grants-get-plans-id-creditgrants.js");
const credit_grants_post_creditgrants_js_1 = require("../funcs/credit-grants-post-creditgrants.js");
const credit_grants_put_creditgrants_id_js_1 = require("../funcs/credit-grants-put-creditgrants-id.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class CreditGrants extends sdks_js_1.ClientSDK {
    /**
     * Get credit grants
     *
     * @remarks
     * Get credit grants with the specified filter
     */
    async getCreditgrants(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, credit_grants_get_creditgrants_js_1.creditGrantsGetCreditgrants)(this, request, options));
    }
    /**
     * Create a new credit grant
     *
     * @remarks
     * Create a new credit grant with the specified configuration
     */
    async postCreditgrants(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, credit_grants_post_creditgrants_js_1.creditGrantsPostCreditgrants)(this, request, options));
    }
    /**
     * Get a credit grant by ID
     *
     * @remarks
     * Get a credit grant by ID
     */
    async getCreditgrantsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, credit_grants_get_creditgrants_id_js_1.creditGrantsGetCreditgrantsId)(this, id, options));
    }
    /**
     * Update a credit grant
     *
     * @remarks
     * Update a credit grant with the specified configuration
     */
    async putCreditgrantsId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, credit_grants_put_creditgrants_id_js_1.creditGrantsPutCreditgrantsId)(this, id, body, options));
    }
    /**
     * Delete a credit grant
     *
     * @remarks
     * Delete a credit grant
     */
    async deleteCreditgrantsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, credit_grants_delete_creditgrants_id_js_1.creditGrantsDeleteCreditgrantsId)(this, id, options));
    }
    /**
     * Get plan credit grants
     *
     * @remarks
     * Get all credit grants for a plan
     */
    async getPlansIdCreditgrants(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, credit_grants_get_plans_id_creditgrants_js_1.creditGrantsGetPlansIdCreditgrants)(this, id, options));
    }
}
exports.CreditGrants = CreditGrants;
//# sourceMappingURL=credit-grants.js.map