"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Customers = void 0;
const customers_delete_customers_id_js_1 = require("../funcs/customers-delete-customers-id.js");
const customers_get_customers_external_external_id_js_1 = require("../funcs/customers-get-customers-external-external-id.js");
const customers_get_customers_id_entitlements_js_1 = require("../funcs/customers-get-customers-id-entitlements.js");
const customers_get_customers_id_grants_upcoming_js_1 = require("../funcs/customers-get-customers-id-grants-upcoming.js");
const customers_get_customers_id_js_1 = require("../funcs/customers-get-customers-id.js");
const customers_get_customers_usage_js_1 = require("../funcs/customers-get-customers-usage.js");
const customers_get_customers_js_1 = require("../funcs/customers-get-customers.js");
const customers_post_customers_search_js_1 = require("../funcs/customers-post-customers-search.js");
const customers_post_customers_js_1 = require("../funcs/customers-post-customers.js");
const customers_put_customers_js_1 = require("../funcs/customers-put-customers.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Customers extends sdks_js_1.ClientSDK {
    /**
     * Get customers
     *
     * @remarks
     * Get customers
     */
    async getCustomers(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_get_customers_js_1.customersGetCustomers)(this, request, options));
    }
    /**
     * Update a customer
     *
     * @remarks
     * Update a customer by id or external_customer_id
     */
    async putCustomers(body, id, externalCustomerId, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_put_customers_js_1.customersPutCustomers)(this, body, id, externalCustomerId, options));
    }
    /**
     * Create a customer
     *
     * @remarks
     * Create a customer
     */
    async postCustomers(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_post_customers_js_1.customersPostCustomers)(this, request, options));
    }
    /**
     * Get a customer by external id
     *
     * @remarks
     * Get a customer by external id
     */
    async getCustomersExternalExternalId(externalId, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_get_customers_external_external_id_js_1.customersGetCustomersExternalExternalId)(this, externalId, options));
    }
    /**
     * List customers by filter
     *
     * @remarks
     * List customers by filter
     */
    async postCustomersSearch(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_post_customers_search_js_1.customersPostCustomersSearch)(this, request, options));
    }
    /**
     * Get customer usage summary
     *
     * @remarks
     * Get customer usage summary by customer_id or customer_lookup_key (external_customer_id)
     */
    async getCustomersUsage(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_get_customers_usage_js_1.customersGetCustomersUsage)(this, request, options));
    }
    /**
     * Get a customer
     *
     * @remarks
     * Get a customer
     */
    async getCustomersId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_get_customers_id_js_1.customersGetCustomersId)(this, id, options));
    }
    /**
     * Delete a customer
     *
     * @remarks
     * Delete a customer
     */
    async deleteCustomersId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_delete_customers_id_js_1.customersDeleteCustomersId)(this, id, options));
    }
    /**
     * Get customer entitlements
     *
     * @remarks
     * Get customer entitlements
     */
    async getCustomersIdEntitlements(id, featureIds, subscriptionIds, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_get_customers_id_entitlements_js_1.customersGetCustomersIdEntitlements)(this, id, featureIds, subscriptionIds, options));
    }
    /**
     * Get upcoming credit grant applications
     *
     * @remarks
     * Get upcoming credit grant applications for a customer
     */
    async getCustomersIdGrantsUpcoming(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, customers_get_customers_id_grants_upcoming_js_1.customersGetCustomersIdGrantsUpcoming)(this, id, options));
    }
}
exports.Customers = Customers;
//# sourceMappingURL=customers.js.map