"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Events = void 0;
const eventsGetEventsMonitoring_js_1 = require("../funcs/eventsGetEventsMonitoring.js");
const eventsPostEvents_js_1 = require("../funcs/eventsPostEvents.js");
const eventsPostEventsAnalytics_js_1 = require("../funcs/eventsPostEventsAnalytics.js");
const eventsPostEventsBulk_js_1 = require("../funcs/eventsPostEventsBulk.js");
const eventsPostEventsHuggingfaceInference_js_1 = require("../funcs/eventsPostEventsHuggingfaceInference.js");
const eventsPostEventsQuery_js_1 = require("../funcs/eventsPostEventsQuery.js");
const eventsPostEventsUsage_js_1 = require("../funcs/eventsPostEventsUsage.js");
const eventsPostEventsUsageMeter_js_1 = require("../funcs/eventsPostEventsUsageMeter.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Events extends sdks_js_1.ClientSDK {
    /**
     * Ingest event
     *
     * @remarks
     * Ingest a new event into the system
     */
    async postEvents(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEvents_js_1.eventsPostEvents)(this, request, options));
    }
    /**
     * Get usage analytics
     *
     * @remarks
     * Retrieve comprehensive usage analytics with filtering, grouping, and time-series data
     */
    async postEventsAnalytics(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEventsAnalytics_js_1.eventsPostEventsAnalytics)(this, request, options));
    }
    /**
     * Bulk Ingest events
     *
     * @remarks
     * Ingest bulk events into the system
     */
    async postEventsBulk(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEventsBulk_js_1.eventsPostEventsBulk)(this, request, options));
    }
    /**
     * Get hugging face inference data
     *
     * @remarks
     * Retrieve hugging face inference data for events
     */
    async postEventsHuggingfaceInference(options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEventsHuggingfaceInference_js_1.eventsPostEventsHuggingfaceInference)(this, options));
    }
    /**
     * Get monitoring data
     *
     * @remarks
     * Retrieve monitoring data for events including consumer lag and event metrics (last 24 hours by default)
     */
    async getEventsMonitoring(windowSize, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsGetEventsMonitoring_js_1.eventsGetEventsMonitoring)(this, windowSize, options));
    }
    /**
     * List raw events
     *
     * @remarks
     * Retrieve raw events with pagination and filtering
     */
    async postEventsQuery(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEventsQuery_js_1.eventsPostEventsQuery)(this, request, options));
    }
    /**
     * Get usage statistics
     *
     * @remarks
     * Retrieve aggregated usage statistics for events
     */
    async postEventsUsage(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEventsUsage_js_1.eventsPostEventsUsage)(this, request, options));
    }
    /**
     * Get usage by meter
     *
     * @remarks
     * Retrieve aggregated usage statistics using meter configuration
     */
    async postEventsUsageMeter(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, eventsPostEventsUsageMeter_js_1.eventsPostEventsUsageMeter)(this, request, options));
    }
}
exports.Events = Events;
//# sourceMappingURL=events.js.map