"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Features = void 0;
const featuresDeleteFeaturesId_js_1 = require("../funcs/featuresDeleteFeaturesId.js");
const featuresGetFeatures_js_1 = require("../funcs/featuresGetFeatures.js");
const featuresGetFeaturesId_js_1 = require("../funcs/featuresGetFeaturesId.js");
const featuresPostFeatures_js_1 = require("../funcs/featuresPostFeatures.js");
const featuresPostFeaturesSearch_js_1 = require("../funcs/featuresPostFeaturesSearch.js");
const featuresPutFeaturesId_js_1 = require("../funcs/featuresPutFeaturesId.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Features extends sdks_js_1.ClientSDK {
    /**
     * List features
     *
     * @remarks
     * List features with optional filtering
     */
    async getFeatures(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, featuresGetFeatures_js_1.featuresGetFeatures)(this, request, options));
    }
    /**
     * Create a new feature
     *
     * @remarks
     * Create a new feature
     */
    async postFeatures(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, featuresPostFeatures_js_1.featuresPostFeatures)(this, request, options));
    }
    /**
     * List features by filter
     *
     * @remarks
     * List features by filter
     */
    async postFeaturesSearch(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, featuresPostFeaturesSearch_js_1.featuresPostFeaturesSearch)(this, request, options));
    }
    /**
     * Get a feature by ID
     *
     * @remarks
     * Get a feature by ID
     */
    async getFeaturesId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, featuresGetFeaturesId_js_1.featuresGetFeaturesId)(this, id, options));
    }
    /**
     * Update a feature
     *
     * @remarks
     * Update a feature by ID
     */
    async putFeaturesId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, featuresPutFeaturesId_js_1.featuresPutFeaturesId)(this, id, body, options));
    }
    /**
     * Delete a feature
     *
     * @remarks
     * Delete a feature by ID
     */
    async deleteFeaturesId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, featuresDeleteFeaturesId_js_1.featuresDeleteFeaturesId)(this, id, options));
    }
}
exports.Features = Features;
//# sourceMappingURL=features.js.map