"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Groups = void 0;
const groupsDeleteGroupsId_js_1 = require("../funcs/groupsDeleteGroupsId.js");
const groupsGetGroupsId_js_1 = require("../funcs/groupsGetGroupsId.js");
const groupsPostGroups_js_1 = require("../funcs/groupsPostGroups.js");
const groupsPostGroupsSearch_js_1 = require("../funcs/groupsPostGroupsSearch.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Groups extends sdks_js_1.ClientSDK {
    /**
     * Create a group
     *
     * @remarks
     * Create a new group for organizing entities (prices, plans, customers, etc.)
     */
    async postGroups(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, groupsPostGroups_js_1.groupsPostGroups)(this, request, options));
    }
    /**
     * Get groups
     *
     * @remarks
     * Get groups with optional filtering via query parameters
     */
    async postGroupsSearch(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, groupsPostGroupsSearch_js_1.groupsPostGroupsSearch)(this, request, options));
    }
    /**
     * Get a group
     *
     * @remarks
     * Get a group by ID
     */
    async getGroupsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, groupsGetGroupsId_js_1.groupsGetGroupsId)(this, id, options));
    }
    /**
     * Delete a group
     *
     * @remarks
     * Delete a group and remove all entity associations
     */
    async deleteGroupsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, groupsDeleteGroupsId_js_1.groupsDeleteGroupsId)(this, id, options));
    }
}
exports.Groups = Groups;
//# sourceMappingURL=groups.js.map