"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PriceUnits = void 0;
const price_units_delete_prices_units_id_js_1 = require("../funcs/price-units-delete-prices-units-id.js");
const price_units_get_prices_units_code_code_js_1 = require("../funcs/price-units-get-prices-units-code-code.js");
const price_units_get_prices_units_id_js_1 = require("../funcs/price-units-get-prices-units-id.js");
const price_units_get_prices_units_js_1 = require("../funcs/price-units-get-prices-units.js");
const price_units_post_prices_units_search_js_1 = require("../funcs/price-units-post-prices-units-search.js");
const price_units_post_prices_units_js_1 = require("../funcs/price-units-post-prices-units.js");
const price_units_put_prices_units_id_js_1 = require("../funcs/price-units-put-prices-units-id.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class PriceUnits extends sdks_js_1.ClientSDK {
    /**
     * List price units
     *
     * @remarks
     * Get a paginated list of price units with optional filtering
     */
    async getPricesUnits(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_get_prices_units_js_1.priceUnitsGetPricesUnits)(this, request, options));
    }
    /**
     * Create a new price unit
     *
     * @remarks
     * Create a new price unit with the provided details
     */
    async postPricesUnits(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_post_prices_units_js_1.priceUnitsPostPricesUnits)(this, request, options));
    }
    /**
     * Get a price unit by code
     *
     * @remarks
     * Get a price unit by code
     */
    async getPricesUnitsCodeCode(code, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_get_prices_units_code_code_js_1.priceUnitsGetPricesUnitsCodeCode)(this, code, options));
    }
    /**
     * List price units by filter
     *
     * @remarks
     * List price units by filter
     */
    async postPricesUnitsSearch(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_post_prices_units_search_js_1.priceUnitsPostPricesUnitsSearch)(this, request, options));
    }
    /**
     * Get a price unit by ID
     *
     * @remarks
     * Get a price unit by ID
     */
    async getPricesUnitsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_get_prices_units_id_js_1.priceUnitsGetPricesUnitsId)(this, id, options));
    }
    /**
     * Update a price unit
     *
     * @remarks
     * Update an existing price unit with the provided details. Only name and metadata can be updated.
     */
    async putPricesUnitsId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_put_prices_units_id_js_1.priceUnitsPutPricesUnitsId)(this, id, body, options));
    }
    /**
     * Delete a price unit
     *
     * @remarks
     * Delete an existing price unit.
     */
    async deletePricesUnitsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, price_units_delete_prices_units_id_js_1.priceUnitsDeletePricesUnitsId)(this, id, options));
    }
}
exports.PriceUnits = PriceUnits;
//# sourceMappingURL=price-units.js.map