"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PriceUnits = void 0;
const priceUnitsDeletePricesUnitsId_js_1 = require("../funcs/priceUnitsDeletePricesUnitsId.js");
const priceUnitsGetPricesUnits_js_1 = require("../funcs/priceUnitsGetPricesUnits.js");
const priceUnitsGetPricesUnitsCodeCode_js_1 = require("../funcs/priceUnitsGetPricesUnitsCodeCode.js");
const priceUnitsGetPricesUnitsId_js_1 = require("../funcs/priceUnitsGetPricesUnitsId.js");
const priceUnitsPostPricesUnits_js_1 = require("../funcs/priceUnitsPostPricesUnits.js");
const priceUnitsPostPricesUnitsSearch_js_1 = require("../funcs/priceUnitsPostPricesUnitsSearch.js");
const priceUnitsPutPricesUnitsId_js_1 = require("../funcs/priceUnitsPutPricesUnitsId.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class PriceUnits extends sdks_js_1.ClientSDK {
    /**
     * List price units
     *
     * @remarks
     * Get a paginated list of price units with optional filtering
     */
    async getPricesUnits(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsGetPricesUnits_js_1.priceUnitsGetPricesUnits)(this, request, options));
    }
    /**
     * Create a new price unit
     *
     * @remarks
     * Create a new price unit with the provided details
     */
    async postPricesUnits(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsPostPricesUnits_js_1.priceUnitsPostPricesUnits)(this, request, options));
    }
    /**
     * Get a price unit by code
     *
     * @remarks
     * Get a price unit by code
     */
    async getPricesUnitsCodeCode(code, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsGetPricesUnitsCodeCode_js_1.priceUnitsGetPricesUnitsCodeCode)(this, code, options));
    }
    /**
     * List price units by filter
     *
     * @remarks
     * List price units by filter
     */
    async postPricesUnitsSearch(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsPostPricesUnitsSearch_js_1.priceUnitsPostPricesUnitsSearch)(this, request, options));
    }
    /**
     * Get a price unit by ID
     *
     * @remarks
     * Get a price unit by ID
     */
    async getPricesUnitsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsGetPricesUnitsId_js_1.priceUnitsGetPricesUnitsId)(this, id, options));
    }
    /**
     * Update a price unit
     *
     * @remarks
     * Update an existing price unit with the provided details. Only name and metadata can be updated.
     */
    async putPricesUnitsId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsPutPricesUnitsId_js_1.priceUnitsPutPricesUnitsId)(this, id, body, options));
    }
    /**
     * Delete a price unit
     *
     * @remarks
     * Delete an existing price unit.
     */
    async deletePricesUnitsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, priceUnitsDeletePricesUnitsId_js_1.priceUnitsDeletePricesUnitsId)(this, id, options));
    }
}
exports.PriceUnits = PriceUnits;
//# sourceMappingURL=priceunits.js.map