import { ClientSDK } from "../lib/sdks.js";
import { Addons } from "./addons.js";
import { AlertLogs } from "./alertlogs.js";
import { Auth } from "./auth.js";
import { Connections } from "./connections.js";
import { Costs } from "./costs.js";
import { Coupons } from "./coupons.js";
import { CreditGrants } from "./creditgrants.js";
import { CreditNotes } from "./creditnotes.js";
import { CustomerDashboard } from "./customerdashboard.js";
import { Customers } from "./customers.js";
import { Entitlements } from "./entitlements.js";
import { EntityIntegrationMappings } from "./entityintegrationmappings.js";
import { Environments } from "./environments.js";
import { Events } from "./events.js";
import { Features } from "./features.js";
import { Groups } from "./groups.js";
import { Integrations } from "./integrations.js";
import { Invoices } from "./invoices.js";
import { Payments } from "./payments.js";
import { Plans } from "./plans.js";
import { Prices } from "./prices.js";
import { PriceUnits } from "./priceunits.js";
import { Rbac } from "./rbac.js";
import { ScheduledTasks } from "./scheduledtasks.js";
import { Secrets } from "./secrets.js";
import { Subscriptions } from "./subscriptions.js";
import { Tasks } from "./tasks.js";
import { TaxAssociations } from "./taxassociations.js";
import { TaxRates } from "./taxrates.js";
import { Tenants } from "./tenants.js";
import { Users } from "./users.js";
import { Wallets } from "./wallets.js";
import { Webhooks } from "./webhooks.js";
export declare class FlexPrice extends ClientSDK {
    private _addons?;
    get addons(): Addons;
    private _entitlements?;
    get entitlements(): Entitlements;
    private _alertLogs?;
    get alertLogs(): AlertLogs;
    private _auth?;
    get auth(): Auth;
    private _connections?;
    get connections(): Connections;
    private _costs?;
    get costs(): Costs;
    private _coupons?;
    get coupons(): Coupons;
    private _creditGrants?;
    get creditGrants(): CreditGrants;
    private _creditNotes?;
    get creditNotes(): CreditNotes;
    private _customerDashboard?;
    get customerDashboard(): CustomerDashboard;
    private _customers?;
    get customers(): Customers;
    private _wallets?;
    get wallets(): Wallets;
    private _invoices?;
    get invoices(): Invoices;
    private _entityIntegrationMappings?;
    get entityIntegrationMappings(): EntityIntegrationMappings;
    private _environments?;
    get environments(): Environments;
    private _events?;
    get events(): Events;
    private _features?;
    get features(): Features;
    private _groups?;
    get groups(): Groups;
    private _payments?;
    get payments(): Payments;
    private _plans?;
    get plans(): Plans;
    private _prices?;
    get prices(): Prices;
    private _priceUnits?;
    get priceUnits(): PriceUnits;
    private _rbac?;
    get rbac(): Rbac;
    private _secrets?;
    get secrets(): Secrets;
    private _integrations?;
    get integrations(): Integrations;
    private _subscriptions?;
    get subscriptions(): Subscriptions;
    private _tasks?;
    get tasks(): Tasks;
    private _scheduledTasks?;
    get scheduledTasks(): ScheduledTasks;
    private _taxAssociations?;
    get taxAssociations(): TaxAssociations;
    private _taxRates?;
    get taxRates(): TaxRates;
    private _tenants?;
    get tenants(): Tenants;
    private _users?;
    get users(): Users;
    private _webhooks?;
    get webhooks(): Webhooks;
}
//# sourceMappingURL=sdk.d.ts.map