"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tasks = void 0;
const tasksGetTasks_js_1 = require("../funcs/tasksGetTasks.js");
const tasksGetTasksId_js_1 = require("../funcs/tasksGetTasksId.js");
const tasksGetTasksResult_js_1 = require("../funcs/tasksGetTasksResult.js");
const tasksPostTasks_js_1 = require("../funcs/tasksPostTasks.js");
const tasksPutTasksIdStatus_js_1 = require("../funcs/tasksPutTasksIdStatus.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Tasks extends sdks_js_1.ClientSDK {
    /**
     * List tasks
     *
     * @remarks
     * List tasks with optional filtering
     */
    async getTasks(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, tasksGetTasks_js_1.tasksGetTasks)(this, request, options));
    }
    /**
     * Create a new task
     *
     * @remarks
     * Create a new task for processing files asynchronously
     */
    async postTasks(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, tasksPostTasks_js_1.tasksPostTasks)(this, request, options));
    }
    /**
     * Get task processing result
     *
     * @remarks
     * Get the result of a task processing workflow
     */
    async getTasksResult(workflowId, options) {
        return (0, fp_js_1.unwrapAsync)((0, tasksGetTasksResult_js_1.tasksGetTasksResult)(this, workflowId, options));
    }
    /**
     * Get a task
     *
     * @remarks
     * Get a task by ID
     */
    async getTasksId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, tasksGetTasksId_js_1.tasksGetTasksId)(this, id, options));
    }
    /**
     * Update task status
     *
     * @remarks
     * Update a task's status
     */
    async putTasksIdStatus(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, tasksPutTasksIdStatus_js_1.tasksPutTasksIdStatus)(this, id, body, options));
    }
}
exports.Tasks = Tasks;
//# sourceMappingURL=tasks.js.map