"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wallets = void 0;
const walletsGetCustomersIdWallets_js_1 = require("../funcs/walletsGetCustomersIdWallets.js");
const walletsGetCustomersWallets_js_1 = require("../funcs/walletsGetCustomersWallets.js");
const walletsGetWallets_js_1 = require("../funcs/walletsGetWallets.js");
const walletsGetWalletsId_js_1 = require("../funcs/walletsGetWalletsId.js");
const walletsGetWalletsIdBalanceRealTime_js_1 = require("../funcs/walletsGetWalletsIdBalanceRealTime.js");
const walletsGetWalletsIdTransactions_js_1 = require("../funcs/walletsGetWalletsIdTransactions.js");
const walletsPostWallets_js_1 = require("../funcs/walletsPostWallets.js");
const walletsPostWalletsIdTerminate_js_1 = require("../funcs/walletsPostWalletsIdTerminate.js");
const walletsPostWalletsIdTopUp_js_1 = require("../funcs/walletsPostWalletsIdTopUp.js");
const walletsPostWalletsSearch_js_1 = require("../funcs/walletsPostWalletsSearch.js");
const walletsPostWalletsTransactionsSearch_js_1 = require("../funcs/walletsPostWalletsTransactionsSearch.js");
const walletsPutWalletsId_js_1 = require("../funcs/walletsPutWalletsId.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Wallets extends sdks_js_1.ClientSDK {
    /**
     * Get Customer Wallets
     *
     * @remarks
     * Get all wallets for a customer by lookup key or id
     */
    async getCustomersWallets(id, includeRealTimeBalance, lookupKey, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsGetCustomersWallets_js_1.walletsGetCustomersWallets)(this, id, includeRealTimeBalance, lookupKey, options));
    }
    /**
     * Get wallets by customer ID
     *
     * @remarks
     * Get all wallets for a customer
     */
    async getCustomersIdWallets(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsGetCustomersIdWallets_js_1.walletsGetCustomersIdWallets)(this, id, options));
    }
    /**
     * List wallets
     *
     * @remarks
     * List wallets with optional filtering
     */
    async getWallets(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsGetWallets_js_1.walletsGetWallets)(this, request, options));
    }
    /**
     * Create a new wallet
     *
     * @remarks
     * Create a new wallet for a customer
     */
    async postWallets(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsPostWallets_js_1.walletsPostWallets)(this, request, options));
    }
    /**
     * List wallets by filter
     *
     * @remarks
     * List wallets by filter
     */
    async postWalletsSearch(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsPostWalletsSearch_js_1.walletsPostWalletsSearch)(this, request, options));
    }
    /**
     * List wallet transactions by filter
     *
     * @remarks
     * List wallet transactions by filter
     */
    async postWalletsTransactionsSearch(expand, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsPostWalletsTransactionsSearch_js_1.walletsPostWalletsTransactionsSearch)(this, expand, body, options));
    }
    /**
     * Get wallet by ID
     *
     * @remarks
     * Get a wallet by its ID
     */
    async getWalletsId(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsGetWalletsId_js_1.walletsGetWalletsId)(this, id, options));
    }
    /**
     * Update a wallet
     *
     * @remarks
     * Update a wallet's details including auto top-up configuration
     */
    async putWalletsId(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsPutWalletsId_js_1.walletsPutWalletsId)(this, id, body, options));
    }
    /**
     * Get wallet balance
     *
     * @remarks
     * Get real-time balance of a wallet
     */
    async getWalletsIdBalanceRealTime(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsGetWalletsIdBalanceRealTime_js_1.walletsGetWalletsIdBalanceRealTime)(this, id, options));
    }
    /**
     * Terminate a wallet
     *
     * @remarks
     * Terminates a wallet by closing it and debiting remaining balance
     */
    async postWalletsIdTerminate(id, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsPostWalletsIdTerminate_js_1.walletsPostWalletsIdTerminate)(this, id, options));
    }
    /**
     * Top up wallet
     *
     * @remarks
     * Add credits to a wallet
     */
    async postWalletsIdTopUp(id, body, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsPostWalletsIdTopUp_js_1.walletsPostWalletsIdTopUp)(this, id, body, options));
    }
    /**
     * Get wallet transactions
     *
     * @remarks
     * Get transactions for a wallet with pagination
     */
    async getWalletsIdTransactions(request, options) {
        return (0, fp_js_1.unwrapAsync)((0, walletsGetWalletsIdTransactions_js_1.walletsGetWalletsIdTransactions)(this, request, options));
    }
}
exports.Wallets = Wallets;
//# sourceMappingURL=wallets.js.map