"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Webhooks = void 0;
const webhooksPostWebhooksChargebeeTenantIdEnvironmentId_js_1 = require("../funcs/webhooksPostWebhooksChargebeeTenantIdEnvironmentId.js");
const webhooksPostWebhooksHubspotTenantIdEnvironmentId_js_1 = require("../funcs/webhooksPostWebhooksHubspotTenantIdEnvironmentId.js");
const webhooksPostWebhooksNomodTenantIdEnvironmentId_js_1 = require("../funcs/webhooksPostWebhooksNomodTenantIdEnvironmentId.js");
const webhooksPostWebhooksQuickbooksTenantIdEnvironmentId_js_1 = require("../funcs/webhooksPostWebhooksQuickbooksTenantIdEnvironmentId.js");
const webhooksPostWebhooksRazorpayTenantIdEnvironmentId_js_1 = require("../funcs/webhooksPostWebhooksRazorpayTenantIdEnvironmentId.js");
const webhooksPostWebhooksStripeTenantIdEnvironmentId_js_1 = require("../funcs/webhooksPostWebhooksStripeTenantIdEnvironmentId.js");
const sdks_js_1 = require("../lib/sdks.js");
const fp_js_1 = require("../types/fp.js");
class Webhooks extends sdks_js_1.ClientSDK {
    /**
     * Handle Chargebee webhook events
     *
     * @remarks
     * Process incoming Chargebee webhook events for payment status updates
     */
    async postWebhooksChargebeeTenantIdEnvironmentId(tenantId, environmentId, options) {
        return (0, fp_js_1.unwrapAsync)((0, webhooksPostWebhooksChargebeeTenantIdEnvironmentId_js_1.webhooksPostWebhooksChargebeeTenantIdEnvironmentId)(this, tenantId, environmentId, options));
    }
    /**
     * Handle HubSpot webhook events
     *
     * @remarks
     * Process incoming HubSpot webhook events for deal closed won and customer creation
     */
    async postWebhooksHubspotTenantIdEnvironmentId(tenantId, environmentId, xHubSpotSignatureV3, options) {
        return (0, fp_js_1.unwrapAsync)((0, webhooksPostWebhooksHubspotTenantIdEnvironmentId_js_1.webhooksPostWebhooksHubspotTenantIdEnvironmentId)(this, tenantId, environmentId, xHubSpotSignatureV3, options));
    }
    /**
     * Handle Nomod webhook events
     *
     * @remarks
     * Process incoming Nomod webhook events for payment and invoice payments
     */
    async postWebhooksNomodTenantIdEnvironmentId(tenantId, environmentId, xApiKey, options) {
        return (0, fp_js_1.unwrapAsync)((0, webhooksPostWebhooksNomodTenantIdEnvironmentId_js_1.webhooksPostWebhooksNomodTenantIdEnvironmentId)(this, tenantId, environmentId, xApiKey, options));
    }
    /**
     * Handle QuickBooks webhook events
     *
     * @remarks
     * Process incoming QuickBooks webhook events for payment sync
     */
    async postWebhooksQuickbooksTenantIdEnvironmentId(tenantId, environmentId, intuitSignature, options) {
        return (0, fp_js_1.unwrapAsync)((0, webhooksPostWebhooksQuickbooksTenantIdEnvironmentId_js_1.webhooksPostWebhooksQuickbooksTenantIdEnvironmentId)(this, tenantId, environmentId, intuitSignature, options));
    }
    /**
     * Handle Razorpay webhook events
     *
     * @remarks
     * Process incoming Razorpay webhook events for payment capture and failure
     */
    async postWebhooksRazorpayTenantIdEnvironmentId(tenantId, environmentId, xRazorpaySignature, options) {
        return (0, fp_js_1.unwrapAsync)((0, webhooksPostWebhooksRazorpayTenantIdEnvironmentId_js_1.webhooksPostWebhooksRazorpayTenantIdEnvironmentId)(this, tenantId, environmentId, xRazorpaySignature, options));
    }
    /**
     * Handle Stripe webhook events
     *
     * @remarks
     * Process incoming Stripe webhook events for payment status updates and customer creation
     */
    async postWebhooksStripeTenantIdEnvironmentId(tenantId, environmentId, stripeSignature, options) {
        return (0, fp_js_1.unwrapAsync)((0, webhooksPostWebhooksStripeTenantIdEnvironmentId_js_1.webhooksPostWebhooksStripeTenantIdEnvironmentId)(this, tenantId, environmentId, stripeSignature, options));
    }
}
exports.Webhooks = Webhooks;
//# sourceMappingURL=webhooks.js.map