/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DtoAlertLogResponse,
  DtoAlertLogResponse$inboundSchema,
} from "./dto-alert-log-response.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListAlertLogsResponse = {
  items?: Array<DtoAlertLogResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListAlertLogsResponse$inboundSchema: z.ZodType<
  DtoListAlertLogsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoAlertLogResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function dtoListAlertLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListAlertLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListAlertLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListAlertLogsResponse' from JSON`,
  );
}
