/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DtoEntityIntegrationMappingResponse,
  DtoEntityIntegrationMappingResponse$inboundSchema,
} from "./dto-entity-integration-mapping-response.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListEntityIntegrationMappingsResponse = {
  items?: Array<DtoEntityIntegrationMappingResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListEntityIntegrationMappingsResponse$inboundSchema: z.ZodType<
  DtoListEntityIntegrationMappingsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoEntityIntegrationMappingResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function dtoListEntityIntegrationMappingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DtoListEntityIntegrationMappingsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DtoListEntityIntegrationMappingsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DtoListEntityIntegrationMappingsResponse' from JSON`,
  );
}
