/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  TypesSecretProvider,
  TypesSecretProvider$inboundSchema,
} from "./types-secret-provider.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./types-status.js";
import {
  TypesSyncConfig,
  TypesSyncConfig$inboundSchema,
} from "./types-sync-config.js";

export type DtoConnectionResponse = {
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  name?: string | undefined;
  providerType?: TypesSecretProvider | undefined;
  status?: TypesStatus | undefined;
  syncConfig?: TypesSyncConfig | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoConnectionResponse$inboundSchema: z.ZodType<
  DtoConnectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  name: z.string().optional(),
  provider_type: TypesSecretProvider$inboundSchema.optional(),
  status: TypesStatus$inboundSchema.optional(),
  sync_config: TypesSyncConfig$inboundSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "created_by": "createdBy",
    "environment_id": "environmentId",
    "provider_type": "providerType",
    "sync_config": "syncConfig",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function dtoConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoConnectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoConnectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoConnectionResponse' from JSON`,
  );
}
