/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DtoPlanResponse,
  DtoPlanResponse$inboundSchema,
} from "./dto-plan-response.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type DtoListPlansResponse = {
  items?: Array<DtoPlanResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListPlansResponse$inboundSchema: z.ZodType<
  DtoListPlansResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoPlanResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function dtoListPlansResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListPlansResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListPlansResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListPlansResponse' from JSON`,
  );
}
