/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DtoAuthResponse = {
  tenantId?: string | undefined;
  token?: string | undefined;
  userId?: string | undefined;
};

/** @internal */
export const DtoAuthResponse$inboundSchema: z.ZodType<
  DtoAuthResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  tenant_id: z.string().optional(),
  token: z.string().optional(),
  user_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "tenant_id": "tenantId",
    "user_id": "userId",
  });
});

export function dtoAuthResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoAuthResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoAuthResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoAuthResponse' from JSON`,
  );
}
