/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoConnectionResponse,
  DtoConnectionResponse$inboundSchema,
} from "./dtoconnectionresponse.js";

export type DtoListConnectionsResponse = {
  connections?: Array<DtoConnectionResponse> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  total?: number | undefined;
};

/** @internal */
export const DtoListConnectionsResponse$inboundSchema: z.ZodType<
  DtoListConnectionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  connections: z.array(DtoConnectionResponse$inboundSchema).optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  total: z.number().int().optional(),
});

export function dtoListConnectionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListConnectionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListConnectionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListConnectionsResponse' from JSON`,
  );
}
