/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoTaxRateResponse,
  DtoTaxRateResponse$inboundSchema,
} from "./dtotaxrateresponse.js";
import {
  TypesTaxRateEntityType,
  TypesTaxRateEntityType$inboundSchema,
} from "./typestaxrateentitytype.js";

export type DtoTaxAssociationResponse = {
  autoApply?: boolean | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  currency?: string | undefined;
  entityId?: string | undefined;
  entityType?: TypesTaxRateEntityType | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  status?: string | undefined;
  taxRate?: DtoTaxRateResponse | undefined;
  taxRateId?: string | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
  validFrom?: string | undefined;
  validTo?: string | undefined;
};

/** @internal */
export const DtoTaxAssociationResponse$inboundSchema: z.ZodType<
  DtoTaxAssociationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  auto_apply: z.boolean().optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: TypesTaxRateEntityType$inboundSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  priority: z.number().int().optional(),
  status: z.string().optional(),
  tax_rate: DtoTaxRateResponse$inboundSchema.optional(),
  tax_rate_id: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
  valid_from: z.string().optional(),
  valid_to: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "auto_apply": "autoApply",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "entity_id": "entityId",
    "entity_type": "entityType",
    "environment_id": "environmentId",
    "tax_rate": "taxRate",
    "tax_rate_id": "taxRateId",
    "tenant_id": "tenantId",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
    "valid_from": "validFrom",
    "valid_to": "validTo",
  });
});

export function dtoTaxAssociationResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoTaxAssociationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoTaxAssociationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoTaxAssociationResponse' from JSON`,
  );
}
