/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesInvoiceCadence = {
  Arrear: "ARREAR",
  Advance: "ADVANCE",
} as const;
export type TypesInvoiceCadence = ClosedEnum<typeof TypesInvoiceCadence>;

/** @internal */
export const TypesInvoiceCadence$inboundSchema: z.ZodNativeEnum<
  typeof TypesInvoiceCadence
> = z.nativeEnum(TypesInvoiceCadence);
/** @internal */
export const TypesInvoiceCadence$outboundSchema: z.ZodNativeEnum<
  typeof TypesInvoiceCadence
> = TypesInvoiceCadence$inboundSchema;
