/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesSubscriptionScheduleChangeType = {
  PlanChange: "plan_change",
  Cancellation: "cancellation",
} as const;
export type TypesSubscriptionScheduleChangeType = ClosedEnum<
  typeof TypesSubscriptionScheduleChangeType
>;

/** @internal */
export const TypesSubscriptionScheduleChangeType$inboundSchema: z.ZodNativeEnum<
  typeof TypesSubscriptionScheduleChangeType
> = z.nativeEnum(TypesSubscriptionScheduleChangeType);
/** @internal */
export const TypesSubscriptionScheduleChangeType$outboundSchema:
  z.ZodNativeEnum<typeof TypesSubscriptionScheduleChangeType> =
    TypesSubscriptionScheduleChangeType$inboundSchema;
