/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  GithubComFlexpriceFlexpriceInternalTypesValue,
  GithubComFlexpriceFlexpriceInternalTypesValue$Outbound,
  GithubComFlexpriceFlexpriceInternalTypesValue$outboundSchema,
} from "./github-com-flexprice-flexprice-internal-types-value.js";
import {
  TypesDataType,
  TypesDataType$outboundSchema,
} from "./types-data-type.js";
import {
  TypesFilterOperatorType,
  TypesFilterOperatorType$outboundSchema,
} from "./types-filter-operator-type.js";

export type TypesFilterCondition = {
  dataType?: TypesDataType | undefined;
  field?: string | undefined;
  operator?: TypesFilterOperatorType | undefined;
  value?: GithubComFlexpriceFlexpriceInternalTypesValue | undefined;
};

/** @internal */
export type TypesFilterCondition$Outbound = {
  data_type?: string | undefined;
  field?: string | undefined;
  operator?: string | undefined;
  value?: GithubComFlexpriceFlexpriceInternalTypesValue$Outbound | undefined;
};

/** @internal */
export const TypesFilterCondition$outboundSchema: z.ZodType<
  TypesFilterCondition$Outbound,
  z.ZodTypeDef,
  TypesFilterCondition
> = z.object({
  dataType: TypesDataType$outboundSchema.optional(),
  field: z.string().optional(),
  operator: TypesFilterOperatorType$outboundSchema.optional(),
  value: GithubComFlexpriceFlexpriceInternalTypesValue$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    dataType: "data_type",
  });
});

export function typesFilterConditionToJSON(
  typesFilterCondition: TypesFilterCondition,
): string {
  return JSON.stringify(
    TypesFilterCondition$outboundSchema.parse(typesFilterCondition),
  );
}
