/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesCreditGrantExpiryDurationUnit = {
  Day: "DAY",
  Week: "WEEK",
  Month: "MONTH",
  Year: "YEAR",
} as const;
export type TypesCreditGrantExpiryDurationUnit = ClosedEnum<
  typeof TypesCreditGrantExpiryDurationUnit
>;

/** @internal */
export const TypesCreditGrantExpiryDurationUnit$inboundSchema: z.ZodNativeEnum<
  typeof TypesCreditGrantExpiryDurationUnit
> = z.nativeEnum(TypesCreditGrantExpiryDurationUnit);
/** @internal */
export const TypesCreditGrantExpiryDurationUnit$outboundSchema: z.ZodNativeEnum<
  typeof TypesCreditGrantExpiryDurationUnit
> = TypesCreditGrantExpiryDurationUnit$inboundSchema;
