/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesPaymentMethodType = {
  Card: "CARD",
  Ach: "ACH",
  Offline: "OFFLINE",
  Credits: "CREDITS",
  PaymentLink: "PAYMENT_LINK",
} as const;
export type TypesPaymentMethodType = ClosedEnum<typeof TypesPaymentMethodType>;

/** @internal */
export const TypesPaymentMethodType$inboundSchema: z.ZodNativeEnum<
  typeof TypesPaymentMethodType
> = z.nativeEnum(TypesPaymentMethodType);
/** @internal */
export const TypesPaymentMethodType$outboundSchema: z.ZodNativeEnum<
  typeof TypesPaymentMethodType
> = TypesPaymentMethodType$inboundSchema;
