/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesBillingCadence = {
  Recurring: "RECURRING",
  Onetime: "ONETIME",
} as const;
export type TypesBillingCadence = ClosedEnum<typeof TypesBillingCadence>;

/** @internal */
export const TypesBillingCadence$inboundSchema: z.ZodNativeEnum<
  typeof TypesBillingCadence
> = z.nativeEnum(TypesBillingCadence);
/** @internal */
export const TypesBillingCadence$outboundSchema: z.ZodNativeEnum<
  typeof TypesBillingCadence
> = TypesBillingCadence$inboundSchema;
