/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesScheduledTaskEntityType = {
  Events: "events",
  Invoice: "invoice",
  CreditTopups: "credit_topups",
  CreditUsage: "credit_usage",
} as const;
export type TypesScheduledTaskEntityType = ClosedEnum<
  typeof TypesScheduledTaskEntityType
>;

/** @internal */
export const TypesScheduledTaskEntityType$inboundSchema: z.ZodNativeEnum<
  typeof TypesScheduledTaskEntityType
> = z.nativeEnum(TypesScheduledTaskEntityType);
/** @internal */
export const TypesScheduledTaskEntityType$outboundSchema: z.ZodNativeEnum<
  typeof TypesScheduledTaskEntityType
> = TypesScheduledTaskEntityType$inboundSchema;
