/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesAggregationType = {
  Count: "COUNT",
  Sum: "SUM",
  Avg: "AVG",
  CountUnique: "COUNT_UNIQUE",
  Latest: "LATEST",
  SumWithMultiplier: "SUM_WITH_MULTIPLIER",
  Max: "MAX",
  WeightedSum: "WEIGHTED_SUM",
} as const;
export type TypesAggregationType = ClosedEnum<typeof TypesAggregationType>;

/** @internal */
export const TypesAggregationType$inboundSchema: z.ZodNativeEnum<
  typeof TypesAggregationType
> = z.nativeEnum(TypesAggregationType);
/** @internal */
export const TypesAggregationType$outboundSchema: z.ZodNativeEnum<
  typeof TypesAggregationType
> = TypesAggregationType$inboundSchema;
