/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesCreditNoteStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type TypesCreditNoteStatus = ClosedEnum<typeof TypesCreditNoteStatus>;

/** @internal */
export const TypesCreditNoteStatus$inboundSchema: z.ZodNativeEnum<
  typeof TypesCreditNoteStatus
> = z.nativeEnum(TypesCreditNoteStatus);
