/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesCancellationType = {
  Immediate: "immediate",
  EndOfPeriod: "end_of_period",
} as const;
export type TypesCancellationType = ClosedEnum<typeof TypesCancellationType>;

/** @internal */
export const TypesCancellationType$inboundSchema: z.ZodNativeEnum<
  typeof TypesCancellationType
> = z.nativeEnum(TypesCancellationType);
/** @internal */
export const TypesCancellationType$outboundSchema: z.ZodNativeEnum<
  typeof TypesCancellationType
> = TypesCancellationType$inboundSchema;
