/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DtoWalletResponse,
  DtoWalletResponse$inboundSchema,
} from "./dto-wallet-response.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./types-pagination-response.js";

export type TypesListResponseDtoWalletResponse = {
  items?: Array<DtoWalletResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const TypesListResponseDtoWalletResponse$inboundSchema: z.ZodType<
  TypesListResponseDtoWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(DtoWalletResponse$inboundSchema).optional(),
  pagination: TypesPaginationResponse$inboundSchema.optional(),
});

export function typesListResponseDtoWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<TypesListResponseDtoWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TypesListResponseDtoWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesListResponseDtoWalletResponse' from JSON`,
  );
}
