/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesWalletType = {
  PrePaid: "PRE_PAID",
  PostPaid: "POST_PAID",
} as const;
export type TypesWalletType = ClosedEnum<typeof TypesWalletType>;

/** @internal */
export const TypesWalletType$inboundSchema: z.ZodNativeEnum<
  typeof TypesWalletType
> = z.nativeEnum(TypesWalletType);
/** @internal */
export const TypesWalletType$outboundSchema: z.ZodNativeEnum<
  typeof TypesWalletType
> = TypesWalletType$inboundSchema;
