/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesTaxRateEntityType = {
  Customer: "customer",
  Subscription: "subscription",
  Invoice: "invoice",
  Tenant: "tenant",
} as const;
export type TypesTaxRateEntityType = ClosedEnum<typeof TypesTaxRateEntityType>;

/** @internal */
export const TypesTaxRateEntityType$inboundSchema: z.ZodNativeEnum<
  typeof TypesTaxRateEntityType
> = z.nativeEnum(TypesTaxRateEntityType);
/** @internal */
export const TypesTaxRateEntityType$outboundSchema: z.ZodNativeEnum<
  typeof TypesTaxRateEntityType
> = TypesTaxRateEntityType$inboundSchema;
