/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const TypesSecretProvider = {
  Flexprice: "flexprice",
  Stripe: "stripe",
  S3: "s3",
  Hubspot: "hubspot",
  Razorpay: "razorpay",
  Chargebee: "chargebee",
  Quickbooks: "quickbooks",
  Nomod: "nomod",
  Moyasar: "moyasar",
} as const;
export type TypesSecretProvider = ClosedEnum<typeof TypesSecretProvider>;

/** @internal */
export const TypesSecretProvider$inboundSchema: z.ZodNativeEnum<
  typeof TypesSecretProvider
> = z.nativeEnum(TypesSecretProvider);
/** @internal */
export const TypesSecretProvider$outboundSchema: z.ZodNativeEnum<
  typeof TypesSecretProvider
> = TypesSecretProvider$inboundSchema;
